//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/BerserkV3/Common/InputSystem/Assets/GamePlayInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GamePlayInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GamePlayInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GamePlayInput"",
    ""maps"": [
        {
            ""name"": ""HoveringSystem"",
            ""id"": ""7e93570f-db2a-425a-bbcc-7ea4aa58e592"",
            ""actions"": [
                {
                    ""name"": ""Pointer"",
                    ""type"": ""PassThrough"",
                    ""id"": ""e41cdf8e-e16d-43ed-a0e6-b3512a1a618d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""598b93c0-56b9-4938-9fa8-6817857f5a3b"",
                    ""path"": ""<Touchscreen>/primaryTouch"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mobile"",
                    ""action"": ""Pointer"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c75276ec-0ea4-4d82-9456-99f866a25be5"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Pointer"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""SelectionSystem"",
            ""id"": ""4333073a-b3b0-4ea9-85b4-b2bcd9c2cf20"",
            ""actions"": [
                {
                    ""name"": ""Select"",
                    ""type"": ""Button"",
                    ""id"": ""e1b2b433-e75b-4abb-8adb-2cbaad92d4d1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=1)"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Cancel"",
                    ""type"": ""Button"",
                    ""id"": ""fc7d68f6-3045-445d-afb0-a9354dc4e635"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""8a65ede9-93ae-47f2-9f2c-7a6a0ecaceae"",
                    ""path"": ""<Touchscreen>/touch1/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mobile"",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""15793133-2542-4f72-a424-1e7f287e7c76"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""82c6027a-50be-424e-b241-99709a40026f"",
                    ""path"": ""<Touchscreen>/primaryTouch/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mobile"",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1e8c294c-bdc9-4083-95b8-37332b4f0882"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""PreviewSystem"",
            ""id"": ""0d5320b8-9de2-4315-b3f4-0f8be074c58c"",
            ""actions"": [
                {
                    ""name"": ""Hand"",
                    ""type"": ""PassThrough"",
                    ""id"": ""8f30e7d1-3b24-4efe-bb14-0fcbd72981c2"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Creature"",
                    ""type"": ""PassThrough"",
                    ""id"": ""b92fc06a-27f5-4bd4-9df7-224759110a10"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Graveyard"",
                    ""type"": ""PassThrough"",
                    ""id"": ""b63af605-9c99-4c45-b56c-d2f0079ddcf3"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pile"",
                    ""type"": ""Value"",
                    ""id"": ""f2632a0f-1085-49eb-998a-a8d67986115b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Fit"",
                    ""type"": ""PassThrough"",
                    ""id"": ""0f0c3c01-8922-4e1f-9585-7e670991e81c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DeckValueInfo"",
                    ""type"": ""PassThrough"",
                    ""id"": ""5b8bd661-2303-496e-8995-6205cd17c87e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""2328e0ea-3538-4a30-9fe1-90aa65f257eb"",
                    ""path"": ""<Touchscreen>/primaryTouch"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mobile"",
                    ""action"": ""Graveyard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7cce0179-2fbf-4073-9a2d-8b2d9edb18d7"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Graveyard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""18fb2688-d634-411c-8d98-541d36e4859d"",
                    ""path"": ""<Touchscreen>/primaryTouch/press"",
                    ""interactions"": ""Hold(duration=0.25)"",
                    ""processors"": """",
                    ""groups"": ""Mobile"",
                    ""action"": ""Pile"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""844c4abc-67e3-4856-aa42-4299b336d5fe"",
                    ""path"": ""<Touchscreen>/primaryTouch"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mobile"",
                    ""action"": ""Hand"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""15c77aa1-ba74-477e-8379-57982238eaf5"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Hand"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b2c43ab2-55d1-4084-9920-027a1ea861dd"",
                    ""path"": ""<Touchscreen>/primaryTouch"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mobile"",
                    ""action"": ""Creature"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""17bfea42-cc62-44b7-be7d-3d71e79f89c2"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Creature"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bd5e8952-b0bd-433c-94b0-8186ec5fd261"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Pile"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""19ba0647-81f3-41d5-9323-cf6acee4d1fc"",
                    ""path"": ""<Touchscreen>/primaryTouch"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mobile"",
                    ""action"": ""Fit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a5b8ba69-5d3b-4dd9-8172-4544180ac773"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Fit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""81a0ded0-ba98-4225-854d-ccab826cfb4f"",
                    ""path"": ""<Touchscreen>/primaryTouch"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mobile"",
                    ""action"": ""DeckValueInfo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""07bf9b91-32f6-4be7-ac9d-d709e856d28a"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""DeckValueInfo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""DragSystem"",
            ""id"": ""15dd41f2-6c59-43c5-bec2-0225713c4b92"",
            ""actions"": [
                {
                    ""name"": ""Pointer"",
                    ""type"": ""PassThrough"",
                    ""id"": ""d2833ec6-3e6d-4cc6-a2e1-499ed88dc8ee"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Initiation"",
                    ""type"": ""Button"",
                    ""id"": ""63d45d9c-ba94-44e8-baca-53ceb7d5869e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Cancel"",
                    ""type"": ""Button"",
                    ""id"": ""1062d557-e0f8-410c-bc8b-bc8536fd113a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""0b4f3ca0-72ae-4c44-9a08-c9d7c29255e7"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Initiation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e736df12-f555-444e-9818-1f3aa33a1e5e"",
                    ""path"": ""<Touchscreen>/primaryTouch/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mobile"",
                    ""action"": ""Initiation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dab05240-0db5-4105-8202-81df527e2afc"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Pointer"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8b05439c-86a1-45d5-b80d-e3c160d443aa"",
                    ""path"": ""<Touchscreen>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mobile"",
                    ""action"": ""Pointer"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""626f0cf1-4a3d-4817-a7a4-eda20dc9a2e2"",
                    ""path"": ""<Touchscreen>/touch1/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mobile"",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a0fcab9d-6c5a-4df0-8135-0bbdd9e4541e"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""TargetSystem"",
            ""id"": ""04f78ef3-d4ed-483e-a524-b5e420a7d445"",
            ""actions"": [
                {
                    ""name"": ""Pointer"",
                    ""type"": ""PassThrough"",
                    ""id"": ""aa6919d5-2860-4275-9796-d8f246435e1a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""03d29d41-94de-4b26-a86b-fd73b4633c2b"",
                    ""path"": ""<Touchscreen>/primaryTouch/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mobile"",
                    ""action"": ""Pointer"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6a79aeac-a49a-4209-a96a-4f871fd46249"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""PC"",
                    ""action"": ""Pointer"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Mobile"",
            ""bindingGroup"": ""Mobile"",
            ""devices"": [
                {
                    ""devicePath"": ""<Touchscreen>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""PC"",
            ""bindingGroup"": ""PC"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Pointer>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // HoveringSystem
        m_HoveringSystem = asset.FindActionMap("HoveringSystem", throwIfNotFound: true);
        m_HoveringSystem_Pointer = m_HoveringSystem.FindAction("Pointer", throwIfNotFound: true);
        // SelectionSystem
        m_SelectionSystem = asset.FindActionMap("SelectionSystem", throwIfNotFound: true);
        m_SelectionSystem_Select = m_SelectionSystem.FindAction("Select", throwIfNotFound: true);
        m_SelectionSystem_Cancel = m_SelectionSystem.FindAction("Cancel", throwIfNotFound: true);
        // PreviewSystem
        m_PreviewSystem = asset.FindActionMap("PreviewSystem", throwIfNotFound: true);
        m_PreviewSystem_Hand = m_PreviewSystem.FindAction("Hand", throwIfNotFound: true);
        m_PreviewSystem_Creature = m_PreviewSystem.FindAction("Creature", throwIfNotFound: true);
        m_PreviewSystem_Graveyard = m_PreviewSystem.FindAction("Graveyard", throwIfNotFound: true);
        m_PreviewSystem_Pile = m_PreviewSystem.FindAction("Pile", throwIfNotFound: true);
        m_PreviewSystem_Fit = m_PreviewSystem.FindAction("Fit", throwIfNotFound: true);
        m_PreviewSystem_DeckValueInfo = m_PreviewSystem.FindAction("DeckValueInfo", throwIfNotFound: true);
        // DragSystem
        m_DragSystem = asset.FindActionMap("DragSystem", throwIfNotFound: true);
        m_DragSystem_Pointer = m_DragSystem.FindAction("Pointer", throwIfNotFound: true);
        m_DragSystem_Initiation = m_DragSystem.FindAction("Initiation", throwIfNotFound: true);
        m_DragSystem_Cancel = m_DragSystem.FindAction("Cancel", throwIfNotFound: true);
        // TargetSystem
        m_TargetSystem = asset.FindActionMap("TargetSystem", throwIfNotFound: true);
        m_TargetSystem_Pointer = m_TargetSystem.FindAction("Pointer", throwIfNotFound: true);
    }

    ~@GamePlayInput()
    {
        UnityEngine.Debug.Assert(!m_HoveringSystem.enabled, "This will cause a leak and performance issues, GamePlayInput.HoveringSystem.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_SelectionSystem.enabled, "This will cause a leak and performance issues, GamePlayInput.SelectionSystem.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_PreviewSystem.enabled, "This will cause a leak and performance issues, GamePlayInput.PreviewSystem.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_DragSystem.enabled, "This will cause a leak and performance issues, GamePlayInput.DragSystem.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_TargetSystem.enabled, "This will cause a leak and performance issues, GamePlayInput.TargetSystem.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // HoveringSystem
    private readonly InputActionMap m_HoveringSystem;
    private List<IHoveringSystemActions> m_HoveringSystemActionsCallbackInterfaces = new List<IHoveringSystemActions>();
    private readonly InputAction m_HoveringSystem_Pointer;
    public struct HoveringSystemActions
    {
        private @GamePlayInput m_Wrapper;
        public HoveringSystemActions(@GamePlayInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Pointer => m_Wrapper.m_HoveringSystem_Pointer;
        public InputActionMap Get() { return m_Wrapper.m_HoveringSystem; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(HoveringSystemActions set) { return set.Get(); }
        public void AddCallbacks(IHoveringSystemActions instance)
        {
            if (instance == null || m_Wrapper.m_HoveringSystemActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_HoveringSystemActionsCallbackInterfaces.Add(instance);
            @Pointer.started += instance.OnPointer;
            @Pointer.performed += instance.OnPointer;
            @Pointer.canceled += instance.OnPointer;
        }

        private void UnregisterCallbacks(IHoveringSystemActions instance)
        {
            @Pointer.started -= instance.OnPointer;
            @Pointer.performed -= instance.OnPointer;
            @Pointer.canceled -= instance.OnPointer;
        }

        public void RemoveCallbacks(IHoveringSystemActions instance)
        {
            if (m_Wrapper.m_HoveringSystemActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IHoveringSystemActions instance)
        {
            foreach (var item in m_Wrapper.m_HoveringSystemActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_HoveringSystemActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public HoveringSystemActions @HoveringSystem => new HoveringSystemActions(this);

    // SelectionSystem
    private readonly InputActionMap m_SelectionSystem;
    private List<ISelectionSystemActions> m_SelectionSystemActionsCallbackInterfaces = new List<ISelectionSystemActions>();
    private readonly InputAction m_SelectionSystem_Select;
    private readonly InputAction m_SelectionSystem_Cancel;
    public struct SelectionSystemActions
    {
        private @GamePlayInput m_Wrapper;
        public SelectionSystemActions(@GamePlayInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Select => m_Wrapper.m_SelectionSystem_Select;
        public InputAction @Cancel => m_Wrapper.m_SelectionSystem_Cancel;
        public InputActionMap Get() { return m_Wrapper.m_SelectionSystem; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(SelectionSystemActions set) { return set.Get(); }
        public void AddCallbacks(ISelectionSystemActions instance)
        {
            if (instance == null || m_Wrapper.m_SelectionSystemActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_SelectionSystemActionsCallbackInterfaces.Add(instance);
            @Select.started += instance.OnSelect;
            @Select.performed += instance.OnSelect;
            @Select.canceled += instance.OnSelect;
            @Cancel.started += instance.OnCancel;
            @Cancel.performed += instance.OnCancel;
            @Cancel.canceled += instance.OnCancel;
        }

        private void UnregisterCallbacks(ISelectionSystemActions instance)
        {
            @Select.started -= instance.OnSelect;
            @Select.performed -= instance.OnSelect;
            @Select.canceled -= instance.OnSelect;
            @Cancel.started -= instance.OnCancel;
            @Cancel.performed -= instance.OnCancel;
            @Cancel.canceled -= instance.OnCancel;
        }

        public void RemoveCallbacks(ISelectionSystemActions instance)
        {
            if (m_Wrapper.m_SelectionSystemActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ISelectionSystemActions instance)
        {
            foreach (var item in m_Wrapper.m_SelectionSystemActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_SelectionSystemActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public SelectionSystemActions @SelectionSystem => new SelectionSystemActions(this);

    // PreviewSystem
    private readonly InputActionMap m_PreviewSystem;
    private List<IPreviewSystemActions> m_PreviewSystemActionsCallbackInterfaces = new List<IPreviewSystemActions>();
    private readonly InputAction m_PreviewSystem_Hand;
    private readonly InputAction m_PreviewSystem_Creature;
    private readonly InputAction m_PreviewSystem_Graveyard;
    private readonly InputAction m_PreviewSystem_Pile;
    private readonly InputAction m_PreviewSystem_Fit;
    private readonly InputAction m_PreviewSystem_DeckValueInfo;
    public struct PreviewSystemActions
    {
        private @GamePlayInput m_Wrapper;
        public PreviewSystemActions(@GamePlayInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Hand => m_Wrapper.m_PreviewSystem_Hand;
        public InputAction @Creature => m_Wrapper.m_PreviewSystem_Creature;
        public InputAction @Graveyard => m_Wrapper.m_PreviewSystem_Graveyard;
        public InputAction @Pile => m_Wrapper.m_PreviewSystem_Pile;
        public InputAction @Fit => m_Wrapper.m_PreviewSystem_Fit;
        public InputAction @DeckValueInfo => m_Wrapper.m_PreviewSystem_DeckValueInfo;
        public InputActionMap Get() { return m_Wrapper.m_PreviewSystem; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PreviewSystemActions set) { return set.Get(); }
        public void AddCallbacks(IPreviewSystemActions instance)
        {
            if (instance == null || m_Wrapper.m_PreviewSystemActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PreviewSystemActionsCallbackInterfaces.Add(instance);
            @Hand.started += instance.OnHand;
            @Hand.performed += instance.OnHand;
            @Hand.canceled += instance.OnHand;
            @Creature.started += instance.OnCreature;
            @Creature.performed += instance.OnCreature;
            @Creature.canceled += instance.OnCreature;
            @Graveyard.started += instance.OnGraveyard;
            @Graveyard.performed += instance.OnGraveyard;
            @Graveyard.canceled += instance.OnGraveyard;
            @Pile.started += instance.OnPile;
            @Pile.performed += instance.OnPile;
            @Pile.canceled += instance.OnPile;
            @Fit.started += instance.OnFit;
            @Fit.performed += instance.OnFit;
            @Fit.canceled += instance.OnFit;
            @DeckValueInfo.started += instance.OnDeckValueInfo;
            @DeckValueInfo.performed += instance.OnDeckValueInfo;
            @DeckValueInfo.canceled += instance.OnDeckValueInfo;
        }

        private void UnregisterCallbacks(IPreviewSystemActions instance)
        {
            @Hand.started -= instance.OnHand;
            @Hand.performed -= instance.OnHand;
            @Hand.canceled -= instance.OnHand;
            @Creature.started -= instance.OnCreature;
            @Creature.performed -= instance.OnCreature;
            @Creature.canceled -= instance.OnCreature;
            @Graveyard.started -= instance.OnGraveyard;
            @Graveyard.performed -= instance.OnGraveyard;
            @Graveyard.canceled -= instance.OnGraveyard;
            @Pile.started -= instance.OnPile;
            @Pile.performed -= instance.OnPile;
            @Pile.canceled -= instance.OnPile;
            @Fit.started -= instance.OnFit;
            @Fit.performed -= instance.OnFit;
            @Fit.canceled -= instance.OnFit;
            @DeckValueInfo.started -= instance.OnDeckValueInfo;
            @DeckValueInfo.performed -= instance.OnDeckValueInfo;
            @DeckValueInfo.canceled -= instance.OnDeckValueInfo;
        }

        public void RemoveCallbacks(IPreviewSystemActions instance)
        {
            if (m_Wrapper.m_PreviewSystemActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPreviewSystemActions instance)
        {
            foreach (var item in m_Wrapper.m_PreviewSystemActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PreviewSystemActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PreviewSystemActions @PreviewSystem => new PreviewSystemActions(this);

    // DragSystem
    private readonly InputActionMap m_DragSystem;
    private List<IDragSystemActions> m_DragSystemActionsCallbackInterfaces = new List<IDragSystemActions>();
    private readonly InputAction m_DragSystem_Pointer;
    private readonly InputAction m_DragSystem_Initiation;
    private readonly InputAction m_DragSystem_Cancel;
    public struct DragSystemActions
    {
        private @GamePlayInput m_Wrapper;
        public DragSystemActions(@GamePlayInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Pointer => m_Wrapper.m_DragSystem_Pointer;
        public InputAction @Initiation => m_Wrapper.m_DragSystem_Initiation;
        public InputAction @Cancel => m_Wrapper.m_DragSystem_Cancel;
        public InputActionMap Get() { return m_Wrapper.m_DragSystem; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DragSystemActions set) { return set.Get(); }
        public void AddCallbacks(IDragSystemActions instance)
        {
            if (instance == null || m_Wrapper.m_DragSystemActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_DragSystemActionsCallbackInterfaces.Add(instance);
            @Pointer.started += instance.OnPointer;
            @Pointer.performed += instance.OnPointer;
            @Pointer.canceled += instance.OnPointer;
            @Initiation.started += instance.OnInitiation;
            @Initiation.performed += instance.OnInitiation;
            @Initiation.canceled += instance.OnInitiation;
            @Cancel.started += instance.OnCancel;
            @Cancel.performed += instance.OnCancel;
            @Cancel.canceled += instance.OnCancel;
        }

        private void UnregisterCallbacks(IDragSystemActions instance)
        {
            @Pointer.started -= instance.OnPointer;
            @Pointer.performed -= instance.OnPointer;
            @Pointer.canceled -= instance.OnPointer;
            @Initiation.started -= instance.OnInitiation;
            @Initiation.performed -= instance.OnInitiation;
            @Initiation.canceled -= instance.OnInitiation;
            @Cancel.started -= instance.OnCancel;
            @Cancel.performed -= instance.OnCancel;
            @Cancel.canceled -= instance.OnCancel;
        }

        public void RemoveCallbacks(IDragSystemActions instance)
        {
            if (m_Wrapper.m_DragSystemActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IDragSystemActions instance)
        {
            foreach (var item in m_Wrapper.m_DragSystemActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_DragSystemActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public DragSystemActions @DragSystem => new DragSystemActions(this);

    // TargetSystem
    private readonly InputActionMap m_TargetSystem;
    private List<ITargetSystemActions> m_TargetSystemActionsCallbackInterfaces = new List<ITargetSystemActions>();
    private readonly InputAction m_TargetSystem_Pointer;
    public struct TargetSystemActions
    {
        private @GamePlayInput m_Wrapper;
        public TargetSystemActions(@GamePlayInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Pointer => m_Wrapper.m_TargetSystem_Pointer;
        public InputActionMap Get() { return m_Wrapper.m_TargetSystem; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TargetSystemActions set) { return set.Get(); }
        public void AddCallbacks(ITargetSystemActions instance)
        {
            if (instance == null || m_Wrapper.m_TargetSystemActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_TargetSystemActionsCallbackInterfaces.Add(instance);
            @Pointer.started += instance.OnPointer;
            @Pointer.performed += instance.OnPointer;
            @Pointer.canceled += instance.OnPointer;
        }

        private void UnregisterCallbacks(ITargetSystemActions instance)
        {
            @Pointer.started -= instance.OnPointer;
            @Pointer.performed -= instance.OnPointer;
            @Pointer.canceled -= instance.OnPointer;
        }

        public void RemoveCallbacks(ITargetSystemActions instance)
        {
            if (m_Wrapper.m_TargetSystemActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ITargetSystemActions instance)
        {
            foreach (var item in m_Wrapper.m_TargetSystemActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_TargetSystemActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public TargetSystemActions @TargetSystem => new TargetSystemActions(this);
    private int m_MobileSchemeIndex = -1;
    public InputControlScheme MobileScheme
    {
        get
        {
            if (m_MobileSchemeIndex == -1) m_MobileSchemeIndex = asset.FindControlSchemeIndex("Mobile");
            return asset.controlSchemes[m_MobileSchemeIndex];
        }
    }
    private int m_PCSchemeIndex = -1;
    public InputControlScheme PCScheme
    {
        get
        {
            if (m_PCSchemeIndex == -1) m_PCSchemeIndex = asset.FindControlSchemeIndex("PC");
            return asset.controlSchemes[m_PCSchemeIndex];
        }
    }
    public interface IHoveringSystemActions
    {
        void OnPointer(InputAction.CallbackContext context);
    }
    public interface ISelectionSystemActions
    {
        void OnSelect(InputAction.CallbackContext context);
        void OnCancel(InputAction.CallbackContext context);
    }
    public interface IPreviewSystemActions
    {
        void OnHand(InputAction.CallbackContext context);
        void OnCreature(InputAction.CallbackContext context);
        void OnGraveyard(InputAction.CallbackContext context);
        void OnPile(InputAction.CallbackContext context);
        void OnFit(InputAction.CallbackContext context);
        void OnDeckValueInfo(InputAction.CallbackContext context);
    }
    public interface IDragSystemActions
    {
        void OnPointer(InputAction.CallbackContext context);
        void OnInitiation(InputAction.CallbackContext context);
        void OnCancel(InputAction.CallbackContext context);
    }
    public interface ITargetSystemActions
    {
        void OnPointer(InputAction.CallbackContext context);
    }
}
