/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using UnityEngine.UI;
using RR.UI;
using RR.UI.FrameSystem;

namespace BerserkV3.Common.UIKit
{
    public partial class HexagoneItemView : RR.UI.FrameSystem.BaseView //Autogenerated
    {
        public static BerserkV3.Common.UIKit.HexagoneItemView Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        [Header("Controls (auto capture)")]
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Button HexButton = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.RawImage MainImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.RawImage HexBorderImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.RawImage HexMaskImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image HexBottomImg = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI BottomText = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image HexLockImage = default;
        #pragma warning restore 0414
        
        protected override void AutoInit()
        {
            Instance = this;
        }
        
        protected override void AutoSubscribe()
        {
            SubscribeOnChanged(HexButton);
            SubscribeOnChanged(MainImage);
            SubscribeOnChanged(HexMaskImage);
            SubscribeOnChanged(HexBorderImage);
            SubscribeOnChanged(HexBottomImg);
            SubscribeOnChanged(BottomText);
            SubscribeOnChanged(HexLockImage);
        }
        
        [VisibleInGraph(false)]
        public BerserkV3.Common.UIKit.HexagoneItemView Build()
        {
            OnBuildSafe(true);
            return this;
        }
        #region Static Methods
        public static void ShowInstance() => Instance.Show();
        public static void HideInstance() => Instance.Hide();
        public static void CloseInstance() => Instance.Close();
        #endregion
    }
}