/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using BerserkV3.GameCore.UI;
using BerserkV3.Lobby.UI;
using UnityEngine.UI;
using RR.UI;
using RR.UI.FrameSystem;
using UnityEngine.Serialization;

namespace BerserkV3.Common.PreviewSystem
{
    public partial class PreviewView : RR.UI.FrameSystem.BaseView //Autogenerated
    {
	    [AutoGenerated,SerializeField] protected RectTransform CenterContainer;
	    [AutoGenerated,SerializeField] protected RectTransform SideContainer;
	    [AutoGenerated,SerializeField] protected RectTransform CornerContainer;
	    [AutoGenerated,SerializeField] protected CardHandArtView CardHandArtView;
	    [AutoGenerated, SerializeField] protected DeckValuePreviewView DeckValuePreviewView;
	    
        public static Common.PreviewSystem.PreviewView Instance { get; private set; }
        // Controls
        
        protected override void AutoInit()
        {
            Instance = this;
        }
        
        protected override void AutoSubscribe()
        {
        }
        
        [VisibleInGraph(false)]
        public Common.PreviewSystem.PreviewView Build()
        {
            OnBuildSafe(true);
            return this;
        }
        #region Static Methods
        public static void ShowInstance() => Instance.Show();
        public static void HideInstance() => Instance.Hide();
        public static void CloseInstance() => Instance.Close();
        #endregion
    }
}