/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using BerserkV3.Startup;
using BerserkV3.Startup.Authorization;
using BerserkV3.Startup.UI;
using UnityEngine.UI;
using RR.UI;
using RR.UI.FrameSystem;

namespace BerserkV3.Common.TutorialSystem
{
    public partial class TutorialPopupView : SafeView //Autogenerated
    {
        public static TutorialPopupView Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        [Header("Controls (auto capture)")]
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform Container = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform Unmask_unused = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform TutorHider_unused = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image TutorHintView = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform TutorHintTitle_unused = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform TutorHintText_unused = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI TutorHintTitle = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI TutorHintText = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform ButtonsLayout = default;
        [AutoGenerated, SerializeField] protected BerserkV3.Common.UIKit.ComplexButton AcceptButton = default;
        [AutoGenerated, SerializeField] protected BerserkV3.Common.UIKit.ComplexButton DeclineButton = default;
        #pragma warning restore 0414
        
        protected override void AutoInit()
        {
            Instance = this;
        }
        
        protected override void AutoSubscribe()
        {
            SubscribeOnChanged(Container);
            SubscribeOnChanged(Unmask_unused);
            SubscribeOnChanged(TutorHider_unused);
            SubscribeOnChanged(TutorHintView);
            SubscribeOnChanged(TutorHintTitle_unused);
            SubscribeOnChanged(TutorHintText_unused);
            SubscribeOnChanged(TutorHintTitle);
            SubscribeOnChanged(TutorHintText);
            SubscribeOnChanged(ButtonsLayout);
            SubscribeOnChanged(AcceptButton);
            SubscribeOnChanged(DeclineButton);
        }
        
        [VisibleInGraph(false)]
        public TutorialPopupView Build()
        {
            OnBuildSafe(true);
            return this;
        }
        #region Static Methods
        public static void ShowInstance() => Instance.Show();
        public static void HideInstance() => Instance.Hide();
        public static void CloseInstance() => Instance.Close();
        #endregion
    }
}