/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using BerserkV3.Startup;
using BerserkV3.Startup.Authorization;
using BerserkV3.Startup.UI;
using UnityEngine.UI;
using RR.UI;
using RR.UI.FrameSystem;

namespace BerserkV3.Common.TutorialSystem
{
    public partial class TutorialGenericView : SafeView //Autogenerated
    {
        public static TutorialGenericView Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        #pragma warning restore 0414
        
        protected override void AutoInit()
        {
            Instance = this;
        }
        
        protected override void AutoSubscribe()
        {
        }
        
        [VisibleInGraph(false)]
        public TutorialGenericView Build()
        {
            OnBuildSafe(true);
            return this;
        }
        #region Static Methods
        public static void ShowInstance() => Instance.Show();
        public static void HideInstance() => Instance.Hide();
        public static void CloseInstance() => Instance.Close();
        #endregion
    }
}