/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////

using System.Linq;
using UnityEditor;

namespace Vulcan.VFX
{
    internal sealed class VFXMapImporter : AssetPostprocessor
    {
        private static void OnPostprocessAllAssets(string[] importedAssets, string[] deletedAssets, string[] movedAssets, string[] movedFromAssetPaths)
        {
            if (CheckAssets(movedFromAssetPaths)) RequestRemapping();
            else if (CheckAssets(importedAssets)) RequestRemapping();
            else if (CheckAssets(deletedAssets))  RequestRemapping();
            else if (CheckAssets(movedAssets))    RequestRemapping();
        }
        
        private static bool CheckAssets(string[] assets) =>
            assets.Any(path => VFXMap.HasAllowedExtension(path) 
                            && path.Contains(VFXMap.GetPath()));

        private static void RequestRemapping() =>
            UnityEditor.EditorApplication.delayCall += VFXMap.MapObjects;
    }
}