/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using BerserkV3.Startup.Authorization;
using UnityEngine.UI;
using RR.UI;
using RR.UI.FrameSystem;

namespace BerserkV3.Startup.UI
{
    public partial class AuthSignUpGuestView : SafeView //Autogenerated
    {
        public static AuthSignUpGuestView Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        [Header("Controls (auto capture)")]
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform Container = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image Background = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI HeaderText = default;
        [AutoGenerated, SerializeField] protected BerserkV3.Common.UIKit.ComplexButton CancelButton = default;
        [AutoGenerated, SerializeField] protected BerserkV3.Common.UIKit.SocialWidget SocialLayout = default;
        [AutoGenerated, SerializeField] protected UnityEngine.CanvasGroup SeparateLayout = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image DottedLineLeft = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI SeparateText = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image DottedLineRigth = default;
        [AutoGenerated, SerializeField] protected BerserkV3.Common.UIKit.ComplexInputField UserNameInputField = default;
        [AutoGenerated, SerializeField] protected BerserkV3.Common.UIKit.ComplexInputField EmailInputField = default;
        [AutoGenerated, SerializeField] protected BerserkV3.Common.UIKit.ComplexInputField PassInputField = default;
        [AutoGenerated, SerializeField] protected BerserkV3.Common.UIKit.ComplexButton ContinueButton = default;
        [AutoGenerated, SerializeField] protected BerserkV3.Common.UIKit.ComplexButton GuestButton = default;
        [AutoGenerated, SerializeField] protected BerserkV3.Common.UIKit.ComplexButton LoginButton = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform PoweredByLayout = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI PoweredByText = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image PoweredByImage = default;
        #pragma warning restore 0414
        
        protected override void AutoInit()
        {
            Instance = this;
        }
        
        protected override void AutoSubscribe()
        {
            SubscribeOnChanged(Container);
            SubscribeOnChanged(Background);
            SubscribeOnChanged(HeaderText);
            SubscribeOnChanged(CancelButton);
            SubscribeOnChanged(SocialLayout);
            SubscribeOnChanged(SeparateLayout);
            SubscribeOnChanged(DottedLineLeft);
            SubscribeOnChanged(SeparateText);
            SubscribeOnChanged(DottedLineRigth);
            SubscribeOnChanged(UserNameInputField);
            SubscribeOnChanged(EmailInputField);
            SubscribeOnChanged(PassInputField);
            SubscribeOnChanged(ContinueButton);
            SubscribeOnChanged(GuestButton);
            SubscribeOnChanged(LoginButton);
            SubscribeOnChanged(PoweredByLayout);
            SubscribeOnChanged(PoweredByText);
            SubscribeOnChanged(PoweredByImage);
        }
        
        [VisibleInGraph(false)]
        public AuthSignUpGuestView Build()
        {
            OnBuildSafe(true);
            return this;
        }
        #region Static Methods
        public static void ShowInstance() => Instance.Show();
        public static void HideInstance() => Instance.Hide();
        public static void CloseInstance() => Instance.Close();
        #endregion
    }
}