/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using BerserkV3.Common.UIKit;
using BerserkV3.Startup.Authorization;
using UnityEngine.UI;
using RR.UI;
using RR.UI.FrameSystem;

namespace BerserkV3.Startup.UI
{
    public partial class AuthVerifyPassView : SafeView //Autogenerated
    {
        public static AuthVerifyPassView Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        [Header("Controls (auto capture)")]
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image Background = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI HeaderText = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI MessageText = default;
        [AutoGenerated, SerializeField] protected BerserkV3.Common.UIKit.ComplexButton FooterButton = default;
        [AutoGenerated, SerializeField] protected BerserkV3.Common.UIKit.ComplexButton ReturnButton = default;
        #pragma warning restore 0414
        
        protected override void AutoInit()
        {
            Instance = this;
        }
        
        protected override void AutoSubscribe()
        {
            SubscribeOnChanged(Background);
            SubscribeOnChanged(HeaderText);
            SubscribeOnChanged(MessageText);
            SubscribeOnChanged(FooterButton);
            SubscribeOnChanged(ReturnButton);
        }
        
        [VisibleInGraph(false)]
        public AuthVerifyPassView Build()
        {
            OnBuildSafe(true);
            return this;
        }
        #region Static Methods
        public static void ShowInstance() => Instance.Show();
        public static void HideInstance() => Instance.Hide();
        public static void CloseInstance() => Instance.Close();
        #endregion
    }
}