/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using BerserkV3.Startup.Authorization;
using UnityEngine.UI;
using RR.UI;
using RR.UI.FrameSystem;

namespace BerserkV3.Startup.UI
{
    public partial class AuthChooseView : SafeView //Autogenerated
    {
        public static AuthChooseView Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        [Header("Controls (auto capture)")]
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform Container = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image Background = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image LogoImage = default;
        [AutoGenerated, SerializeField] protected BerserkV3.Common.UIKit.ComplexButton GuestButton = default;
        [AutoGenerated, SerializeField] protected UnityEngine.CanvasGroup SeparatorLayout = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image DottedLineLeft = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI SeparateText = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image DottedLineRigth = default;
        [AutoGenerated, SerializeField] protected BerserkV3.Common.UIKit.ComplexButton SignInButton = default;
        [AutoGenerated, SerializeField] protected BerserkV3.Common.UIKit.ComplexButton SignUpButton = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform PoweredByLayout = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI PoweredByText = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image PoweredByImage = default;
        #pragma warning restore 0414
        
        protected override void AutoInit()
        {
            Instance = this;
        }
        
        protected override void AutoSubscribe()
        {
            SubscribeOnChanged(Container);
            SubscribeOnChanged(Background);
            SubscribeOnChanged(LogoImage);
            SubscribeOnChanged(GuestButton);
            SubscribeOnChanged(SeparatorLayout);
            SubscribeOnChanged(DottedLineLeft);
            SubscribeOnChanged(SeparateText);
            SubscribeOnChanged(DottedLineRigth);
            SubscribeOnChanged(SignInButton);
            SubscribeOnChanged(SignUpButton);
            SubscribeOnChanged(PoweredByLayout);
            SubscribeOnChanged(PoweredByText);
            SubscribeOnChanged(PoweredByImage);
        }
        
        [VisibleInGraph(false)]
        public AuthChooseView Build()
        {
            OnBuildSafe(true);
            return this;
        }
        #region Static Methods
        public static void ShowInstance() => Instance.Show();
        public static void HideInstance() => Instance.Hide();
        public static void CloseInstance() => Instance.Close();
        #endregion
    }
}