/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using BerserkV3.Startup.Authorization;
using UnityEngine.UI;
using RR.UI;
using RR.UI.FrameSystem;
using UnityEngine.Serialization;

namespace BerserkV3.Startup.UI
{
    public partial class AuthSaveView : SafeView //Autogenerated
    {
        public static AuthSaveView Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        [Header("Controls (auto capture)")]
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform Container = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image Background = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI HeaderText = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI MessageText = default;
        [AutoGenerated, SerializeField] protected BerserkV3.Common.UIKit.TimerWidget SkipTimerWidget = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform ButtonsLayout = default;
        [AutoGenerated, SerializeField] protected BerserkV3.Common.UIKit.ComplexButton CancelButton = default;
        [AutoGenerated, SerializeField] protected BerserkV3.Common.UIKit.ComplexButton AcceptButton = default;
        #pragma warning restore 0414
        
        protected override void AutoInit()
        {
            Instance = this;
        }
        
        protected override void AutoSubscribe()
        {
            SubscribeOnChanged(Container);
            SubscribeOnChanged(Background);
            SubscribeOnChanged(HeaderText);
            SubscribeOnChanged(MessageText);
            SubscribeOnChanged(SkipTimerWidget);
            SubscribeOnChanged(ButtonsLayout);
            SubscribeOnChanged(CancelButton);
            SubscribeOnChanged(AcceptButton);
        }
        
        [VisibleInGraph(false)]
        public AuthSaveView Build()
        {
            OnBuildSafe(true);
            return this;
        }
        #region Static Methods
        public static void ShowInstance() => Instance.Show();
        public static void HideInstance() => Instance.Hide();
        public static void CloseInstance() => Instance.Close();
        #endregion
    }
}