/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using BerserkV3.Startup.Authorization;
using UnityEngine.UI;
using RR.UI;
using RR.UI.FrameSystem;
using UnityEngine.Serialization;

namespace BerserkV3.Startup.UI
{
    public partial class AuthSignInView : SafeView //Autogenerated
    {
        public static AuthSignInView Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        [Header("Controls (auto capture)")]
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform Container = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image Background = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform HeaderLayout = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI HeaderText = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI AuthText = default;
        [AutoGenerated, SerializeField] protected BerserkV3.Common.UIKit.SocialWidget SocialLayout = default;
        [AutoGenerated, SerializeField] protected UnityEngine.CanvasGroup SeparatorLayout = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image DottedLineLeft = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI SeparateText = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image DottedLineRigth = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform ButtonsLayout = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform InputsLayout = default;
        [AutoGenerated, SerializeField] protected BerserkV3.Common.UIKit.ComplexInputField EmailInputField = default;
        [AutoGenerated, SerializeField] protected BerserkV3.Common.UIKit.ComplexInputField PassInputField = default;
        [AutoGenerated, SerializeField] protected BerserkV3.Common.UIKit.ComplexInputField TestPassInputField = default;
        [AutoGenerated, SerializeField] protected BerserkV3.Common.UIKit.ComplexButton SignInButton = default;
        [AutoGenerated, SerializeField] protected BerserkV3.Common.UIKit.ComplexButton GuestButton = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform PoweredByLayout = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI PoweredByText = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image PoweredByImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform LinksLayout = default;
        [AutoGenerated, SerializeField] protected BerserkV3.Common.UIKit.ComplexButton SignUpButton = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI Separator0Text = default;
        [AutoGenerated, SerializeField] protected BerserkV3.Common.UIKit.ComplexButton DeleteAccountButton = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI Separator1Text = default;
        [AutoGenerated, SerializeField] protected BerserkV3.Common.UIKit.ComplexButton ForgotPassButton = default;
        #pragma warning restore 0414
        
        protected override void AutoInit()
        {
            Instance = this;
        }
        
        protected override void AutoSubscribe()
        {
            SubscribeOnChanged(Container);
            SubscribeOnChanged(Background);
            SubscribeOnChanged(HeaderLayout);
            SubscribeOnChanged(HeaderText);
            SubscribeOnChanged(AuthText);
            SubscribeOnChanged(SocialLayout);
            SubscribeOnChanged(SeparatorLayout);
            SubscribeOnChanged(DottedLineLeft);
            SubscribeOnChanged(SeparateText);
            SubscribeOnChanged(DottedLineRigth);
            SubscribeOnChanged(ButtonsLayout);
            SubscribeOnChanged(InputsLayout);
            SubscribeOnChanged(EmailInputField);
            SubscribeOnChanged(PassInputField);
            SubscribeOnChanged(TestPassInputField);
            SubscribeOnChanged(SignInButton);
            SubscribeOnChanged(GuestButton);
            SubscribeOnChanged(PoweredByLayout);
            SubscribeOnChanged(PoweredByText);
            SubscribeOnChanged(PoweredByImage);
            SubscribeOnChanged(LinksLayout);
            SubscribeOnChanged(SignUpButton);
            SubscribeOnChanged(Separator0Text);
            SubscribeOnChanged(DeleteAccountButton);
            SubscribeOnChanged(Separator1Text);
            SubscribeOnChanged(ForgotPassButton);
        }
        
        [VisibleInGraph(false)]
        public AuthSignInView Build()
        {
            OnBuildSafe(true);
            return this;
        }
        #region Static Methods
        public static void ShowInstance() => Instance.Show();
        public static void HideInstance() => Instance.Hide();
        public static void CloseInstance() => Instance.Close();
        #endregion
    }
}