using Sirenix.OdinInspector;
using RR.Core.DebugSystem;
using RR.Core.Extensions;
using UnityEngine;
using System.Linq;
using System.IO;

namespace UI
{
	public abstract partial class AutoMap<T> : SerializedScriptableObject
	{
		[Space(), Header("Automapper settings")]
		[SerializeField] private TextAsset importerTemplate = default;
		[SerializeField] private string importExtensions = "png|jpg";
		[SerializeField] private string generationPath = "Assets/Scripts/_autogenerated/";

		private static AutoMap<T> instance;
		public static AutoMap<T> Instance
		{
			get
			{
				return instance ?? (instance = Resources.FindObjectsOfTypeAll<AutoMap<T>>().FirstOrDefault());
			}
		}

		[Button]
		public static void MapObjects()
		{
			RRLogger.Log($"[{Instance.GetType().Name.Maroon()}] : Mapping folder {Instance.assetsPath}");
			Instance.map.Clear();
			Resources.LoadAll<T>(GetPath()).ForEach(r => Instance.map.Add(r.name, r));

			Instance.SaveAsset();
			Instance.OnMapped();
		}

		[Button]
		public static void InitializeAutomapper()
		{
			var type = Instance.GetType();
			var importerClass = Instance.importerTemplate.text
				.Replace("#NAMESPACE#", type.Namespace)
				.Replace("#CLASS#", type.Name);

			File.WriteAllText(Instance.generationPath + $"{type.Name}Importer.cs", importerClass);
		}

		public static string GetPath()
			=> Instance?.assetsPath ?? "";

		public static bool HasAllowedExtension(string file)
			=> Instance.Value()?.importExtensions.Contains(file.Split('.').LastOrDefault()) ?? false; // todo: bug: instance is null in editmode, fixme

		protected virtual void OnMapped() { }

		private void SaveAsset()
		{
#if UNITY_EDITOR
			UnityEditor.EditorUtility.SetDirty(instance);
#endif
		}
	}
}