using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using RR.Core.DebugSystem;
using RR.Core.Extensions;
using RR.UI.Custom;
using RR.UI.FrameSystem;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.UI;
using Object = UnityEngine.Object;

namespace RR.UI.Editor
{
	internal static class ScriptBuilder
	{
		private static readonly string AutogeneratedDirectory = "_autogenerated";
		private static readonly string DefaultUIPath = "Scripts/UI";
		private static Templates templates;

		private static Template GetTemplate(string name)
		{
			return templates.GetTemplate(name);
		}

		public static void CreateUserScript(RectTransform rt, bool replaceIfExists)
		{
			LoadTemplates();

			var viewInfo = GrabInfoAboutView(rt);
			//get list of UI controls (not views and not Buttons)
			var selectables = viewInfo.Members.Values
				.Where(m => m.Component is Selectable sel && !(sel is Button));

			//get template
			var res = GetTemplate("ViewClassUser");
			if (selectables.Any())
				res.Add("#METHODS#", GetTemplate("OnChanged").ToString());

			//prepare Set methods in OnBuild
			//get list of UI controls (not views and not Buttons)
			var controls = viewInfo.Members.Values
				.Where(m => m.Component != null && !(m.Component is Button) && !(m.Component is RRButton));

			foreach (var sel in controls)
				res.Add("#OnBuildBody#", $"            //Set({sel.Name}, default);");

			//prepare Subscribe methods in Start
			//get list of buttons w/o bindings
			var buttons = viewInfo.Members.Values.Where(m => m.Component is Button or RRButton);

			foreach (var bt in buttons)
				res.Add("#StartBody#", $"            Subscribe({bt.Name}, () => {{;}});");

			//replace class name
			res.Add("#CLASSNAME#", rt.name);

			//save
			CreateNeededFolders();

			var filePath = Path.Combine(Application.dataPath, "Scripts/UI/" + rt.name + ".cs");
			res.Add("#NAMESPACE#", filePath.Substring(filePath.IndexOf("Assets"))
				.Replace(Path.GetFileName(filePath), "")
				.Replace("Scripts", "")
				.Replace("Assets", "")
				.Replace("_autogenerated", "")
				.Trim('/', '\\')
				.Replace("/", ".")
				.Replace("\\", ".")
			);

			if (File.Exists(filePath) && !replaceIfExists)
				return;

			var scriptText = CSharpPreparer.Prepare(res.ToString());
			File.WriteAllText(filePath, scriptText);
			AssetDatabase.Refresh();
		}

		public static void OpenOrCreateUserScript(RectTransform rt)
		{
			//find script 
			var fullPath = Directory
				.GetFiles(Application.dataPath, rt.name + ".cs", SearchOption.AllDirectories)
				.FirstOrDefault(p => !p.Contains(AutogeneratedDirectory));

			if (fullPath != null)
				fullPath = "Assets" + fullPath.Split(new[] { "Assets" }, StringSplitOptions.None)[1];

			var script = fullPath != null
				? AssetDatabase.LoadAssetAtPath(fullPath, typeof(MonoScript))
				: null;

			if (script == null)
			{
				if (!EditorUtility.DisplayDialog("User Script " + rt.name,
					    $"Script {rt.name}.cs does not exists.\r\nDo you want to create?", "Create", "Cancel"))
					return;

				fullPath = $"Assets/{DefaultUIPath}/" + rt.name + ".cs";
				CreateUserScript(rt, false);
				script = AssetDatabase.LoadAssetAtPath(fullPath, typeof(MonoScript));
			}

			if (script != null)
				AssetDatabase.OpenAsset(script);
		}

		public static bool TryCreateScript(RectTransform rt)
		{
			LoadTemplates();

			var res = GetTemplate("ViewClass");
			var fieldsTemplate = GetTemplate("Fields");

			var viewInfo = GrabInfoAboutView(rt);

			RRLogger.Log($"Building fields and generating script for {rt.name}");

			rt.TryGetComponent(out BaseView view);

			var type = view?.GetType();
			if (type != null)
				rt.name = type.Name;

			var baseType = type?.BaseType;
			var baseVariables = GetBaseVariables(baseType);
			var baseNamespace = type?.Namespace;

			// static instance only in base type
			if (type == null || type.IsSubclassOf(typeof(BaseView)))
			{
				res.Add("#INSTANCE#", $"public static {rt.name} Instance {{ get; private set; }}");
				res.Add("#AUTOINIT#", "Instance = this;");
			}
			else
			{
				res.Add("#INSTANCE#", $"public static {rt.name} I => ({rt.name})Instance;");
			}

			var wasFields = false;
			foreach (var item in viewInfo.Members.Values)
			{
				if (item.Type == rt.name) // todo: bad comparing with names
					continue; //myself

				if ((item.FieldInfo == null || !item.IsAutogenerated) &&
				    (item.Binded == null || !item.IsAutogenerated) && item.Component == null)
					continue;

				// don't create same vars if they persist in base class
				if (baseVariables.Any(x => x.Name == item.Name))
					continue;

				wasFields = true;
				fieldsTemplate.Add("#FIELDS#",
					$"    [AutoGenerated, SerializeField] protected {item.Type} {item.Name} = default;");
				res.Add("#INIT#", $"        SubscribeOnChanged({item.Name});");
			}

			//method Build
			CreateBuildMethod(view, res);

			//prepare
			if (wasFields)
				res.Add("#FIELDS#", fieldsTemplate.ToString());

			//replace class name
			res.Add("#CLASSNAME#", rt.name);

			//add base class
			res.Add("#BASECLASS#", baseType?.ToString() ?? "BaseView");

			//set namespace
			res.Add("#NAMESPACE#", baseNamespace ?? "UI");

			//save
			CreateNeededFolders();

			// new unity design
			// https://issuetracker.unity3d.com/issues/partial-monobehaviour-script-can-not-be-attached-to-a-gameobject-when-another-one-exists-with-the-same-file-and-class-name
#if UNITY_2022_2_OR_NEWER
			var autogenScriptName = $"{rt.name}Autogen.cs";
#else
	        var autogenScriptName = $"{rt.name}.cs";
#endif

			//find script 
			var fullPath = Directory
				.GetFiles(Application.dataPath, rt.name + ".cs", SearchOption.AllDirectories)
				.FirstOrDefault(p => !p.Contains(AutogeneratedDirectory)) ?? DefaultUIPath;

			var directoryName = Path.GetDirectoryName(fullPath);
			var autogeneratedPath = Path.Combine(directoryName, AutogeneratedDirectory);

			// Try locating existing script file in project
			var existingScriptsWithSameName =
				Directory.GetFiles(Application.dataPath, autogenScriptName, SearchOption.AllDirectories);

			var filePath = existingScriptsWithSameName
				               .FirstOrDefault(file => File.ReadLines(file)
					               .Any(x => x.Contains("autogen", StringComparison.OrdinalIgnoreCase)))
			               ?? Path.Combine(Application.dataPath, autogeneratedPath, autogenScriptName);

			var dirPath = Path.GetDirectoryName(filePath);

			if (!Directory.Exists(dirPath))
				Directory.CreateDirectory(dirPath);

			var scriptText = CSharpPreparer.Prepare(res.ToString());
			File.WriteAllText(filePath, scriptText);

			AssetDatabase.Refresh(ImportAssetOptions.Default);
			return true;

			List<FieldInfo> GetBaseVariables(Type @base)
			{
				var result = new List<FieldInfo>();
				while (@base != null && @base != typeof(BaseView))
				{
					var fieldInfos = @base
						.GetFields(BindingFlags.NonPublic | BindingFlags.Public | BindingFlags.Instance)
						.Where(field => field.IsDefined(typeof(AutoGeneratedAttribute), false));

					result.AddRange(fieldInfos);
					@base = @base.BaseType;
				}

				return result;
			}
		}

		private static void CreateBuildMethod(BaseView view, Template template)
		{
			var signature = view == null ? "" : view.SignatureOfBuildMethod;

			var args = Argument.Parse(signature).ToArray();

			foreach (var arg in args)
				if (!arg.CheckIsTypeExists())
					if (EditorUtility.DisplayDialog("Error",
						    "Unknown type in Build signature: " + arg.Type + $"\r\nIn view {view.GetType().Name}.",
						    "Do not create script", "Ignore"))
						throw new Exception("Unknown type in Build signature: " + arg.Type);

			var rn = args.Length > 0 ? Environment.NewLine : "";
			var summary = args.Length > 0 ? "    ///<summary>Data</summary>" + rn : "";

			template.Add("#BUILDFIELDS#",
				summary + string.Join(rn, args.Select(a => $"    public {a.Type} {a.Name}{{ get; protected set; }}")) +
				rn);
			template.Add("#BUILDSIGNATURE#", signature);
			template.Add("#BUILDBODY#", string.Join(rn, args.Select(a => $"        this.{a.Name} = {a.Name};")) + rn);

			//clone method
			if (args.Length > 0)
			{
				var cloneTemplate = GetTemplate("Clone");
				cloneTemplate.Add("#CLASSNAME#", view.GetType().Name);
				cloneTemplate.Add("#COPYFIELDS#",
					string.Join(rn, args.Select(a => $"        clone.{a.Name} = {a.Name};")) + rn);
				template.Add("#CLONE#", rn + cloneTemplate);
			}
		}

		public static ViewInfo GrabInfoAboutView(RectTransform rt)
		{
			var viewInfo = new ViewInfo();

			void GrabMethods(Type type, bool checkAttr)
			{
				var methods = type.GetMethods(BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly);
				foreach (var mi in methods)
				{
					if (mi.Name.StartsWith("get_") ||
					    mi.Name.StartsWith("<"))
						continue; //property getter

					var attr = mi.GetCustomAttribute<VisibleInGraphAttribute>();
					if (attr == null && checkAttr)
						continue;
					if (attr != null && !attr.Visible)
						continue;

					var parameters = mi.GetParameters();
					var count = parameters.Count(p => !p.HasDefaultValue);
					if (count != 0)
						if (attr == null || !attr.Visible)
							continue;

					viewInfo.Members[mi.Name] = new ViewInfoItem { Name = mi.Name, MethodInfo = mi };
				}
			}

			//grab components from scene
			foreach (var info in SceneInfoGrabber<BaseView>.GrabInfo(rt, false))
				viewInfo.Members[info.Key] = new ViewInfoItem { Name = info.Key, Component = info.Value };

			//grab exists fileds
			Type viewType = null;
			var view = rt.GetComponent<BaseView>();
			if (view != null)
				viewType = view.GetType();
			else
				viewType = GetTypeByName(rt.name);

			if (viewType != null)
			{
				var fields = viewType.GetFields(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance |
				                                BindingFlags.DeclaredOnly);
				foreach (var fi in fields)
					if (SceneInfoGrabber<BaseView>.WellKnownTypes.Contains(fi.FieldType) ||
					    typeof(BaseView).IsAssignableFrom(fi.FieldType))
					{
						var isAutogenerated = fi.GetCustomAttribute<AutoGeneratedAttribute>();
						if (isAutogenerated != null)
							//skip isAutogenerated fields => they will recreated
							continue;

						viewInfo.Members[fi.Name] = new ViewInfoItem { Name = fi.Name, FieldInfo = fi };
					}

				//grab argless public methods
				GrabMethods(viewType, false);
			}

			//grab argless public methods of base class
			GrabMethods(typeof(BaseView), true);

			return viewInfo;
		}

		public static Type GetTypeByName(string nodeClassName, string prefix = "UI.")
		{
			var type = AppDomain.CurrentDomain
				.GetAssemblies()
				.Where(x => !x.FullName.Contains(".Editor")
				            && !x.FullName.Contains("-Editor")
				            && !x.FullName.Contains(".Tests")
				            && !x.FullName.Contains("-Tests")
				            && !x.FullName.Contains("Unity-")
				            && !x.FullName.Contains("Unity."))
				.Select(x => x.GetType(prefix + nodeClassName))
				.FirstOrDefault(x => x != null);

			return type;
		}

		public static void RebuildAll()
		{
			var autogenScripts = Directory
				.GetFiles(Application.dataPath, "*.cs", SearchOption.AllDirectories)
				.Where(path => path.Contains(AutogeneratedDirectory))
				.Select(Path.GetFileNameWithoutExtension)
				.ToArray();

			var scenes = Directory
				.GetFiles(Path.Combine(Application.dataPath, "Scenes"), "*.unity");

			foreach (var scene in scenes)
			{
				EditorSceneManager.OpenScene(scene);

				var rectTransforms = Object
					.FindObjectsOfType<RectTransform>()
					.Where(rectTransform => autogenScripts.Contains(rectTransform.name))
					.ToArray();

				rectTransforms.ForEach(baseView => TryCreateScript(baseView));
			}
		}

		private static void LoadTemplates()
		{
			var textAsset = Resources.Load<TextAsset>("RR.UI_Templates");
			var text = textAsset.text;
			templates = Templates.Parse(text);
		}

		private static void CreateNeededFolders()
		{
			var assetFolder = Application.dataPath;
			var scriptsFolder = Path.Combine(assetFolder, "Scripts");
			if (!Directory.Exists(scriptsFolder))
				Directory.CreateDirectory(scriptsFolder);
			var viewsFolder = Path.Combine(scriptsFolder, "UI");
			if (!Directory.Exists(viewsFolder))
				Directory.CreateDirectory(viewsFolder);
			var autoFolder = Path.Combine(viewsFolder, "_autogenerated");
			if (!Directory.Exists(autoFolder))
				Directory.CreateDirectory(autoFolder);
		}
	}

	public class ViewInfo
	{
		public Dictionary<string, ViewInfoItem> Members = new();
	}

	public class ViewInfoItem
	{
		public string Binded;
		public Component Component;
		public FieldInfo FieldInfo;
		public bool IsAutogenerated;
		public bool IsAutogeneratedReallyExists;
		public MethodInfo MethodInfo;
		public string Name;

		public string Type => Component != null ? Component.GetType().FullName :
			FieldInfo != null ? FieldInfo.FieldType.FullName :
			Binded != null ? Binded : "void";
	}

	public class Argument
	{
		private static HashSet<string> wellKnownTypes = new();
		public string DefaultValue;
		public string Name;
		public string Type;

		static Argument()
		{
			GrabTypes(typeof(string).Assembly);
			GrabTypes(typeof(Vector2).Assembly);

			wellKnownTypes.Add("string");
			wellKnownTypes.Add("int");
			wellKnownTypes.Add("float");
			wellKnownTypes.Add("double");
			wellKnownTypes.Add("byte");
			wellKnownTypes.Add("decimal");
			wellKnownTypes.Add("char");
			wellKnownTypes.Add("bool");
		}

		public static IEnumerable<Argument> Parse(string signature)
		{
			if (string.IsNullOrWhiteSpace(signature))
				yield break;

			var parts = (signature ?? "").Split(',');
			foreach (var part in parts)
			{
				var parts2 = part.Trim().Split('=');
				var parts3 = parts2[0].Trim().Split(' ');
				string defaultVal = null;
				if (parts2.Length > 1)
					defaultVal = parts2[1].Trim();

				if (parts3.Length == 2)
					yield return new Argument { Name = parts3[1], Type = parts3[0], DefaultValue = defaultVal };
			}
		}

		private static void GrabTypes(Assembly ass)
		{
			foreach (var type in ass.GetTypes().Select(t => t.Name.ToLower()))
				wellKnownTypes.Add(type);
		}

		public bool CheckIsTypeExists()
		{
			var parts = Type.Split('.');
			var lastPart = parts[parts.Length - 1].ToLower();
			var bracketIndex = lastPart.IndexOf('[');
			if (bracketIndex >= 0)
				lastPart = lastPart.Substring(0, bracketIndex);

			if (wellKnownTypes.Contains(lastPart))
				return true;

			return ScriptBuilder.GetTypeByName(Type, "") != null;
		}
	}
}