/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using UnityEngine.UI;
using RR.UI;
using RR.UI.FrameSystem;

namespace BerserkV3.Lobby.UI.Duels
{
    public partial class LobbyDuelSelectDeckView : BerserkV3.Startup.UI.SafeView //Autogenerated
    {
        public static LobbyDuelSelectDeckView Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        [Header("Controls (auto capture)")]
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image ModalImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image LineImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image LineImg = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image Shadow = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform TitleImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image MaskImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BackgroundImageWhite = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI TitleText = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BorderImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image ContentMask = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform DecksLayout = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform DescriptionPanel = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI DeckTitleText = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform AvatarLayout = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image AvatarMaskImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.RawImage AvatarImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.RawImage FrameImage = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI NameText = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform DescriptionContainer = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI LableText = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image LevelImage = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI LevelText = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI DescriptionText = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform ButtonsLayout = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Button SaveButton = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image MaskImage1 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BackgroundImageWhite1 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BorderImage1 = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI OKText = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Button BackButton = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image MaskImage2 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BackgroundImageWhite2 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BorderImage2 = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI OKText1 = default;
        #pragma warning restore 0414
        
        protected override void AutoInit()
        {
            Instance = this;
        }
        
        protected override void AutoSubscribe()
        {
            SubscribeOnChanged(ModalImage);
            SubscribeOnChanged(LineImage);
            SubscribeOnChanged(LineImg);
            SubscribeOnChanged(Shadow);
            SubscribeOnChanged(TitleImage);
            SubscribeOnChanged(MaskImage);
            SubscribeOnChanged(BackgroundImageWhite);
            SubscribeOnChanged(TitleText);
            SubscribeOnChanged(BorderImage);
            SubscribeOnChanged(ContentMask);
            SubscribeOnChanged(DecksLayout);
            SubscribeOnChanged(DescriptionPanel);
            SubscribeOnChanged(DeckTitleText);
            SubscribeOnChanged(AvatarLayout);
            SubscribeOnChanged(AvatarMaskImage);
            SubscribeOnChanged(AvatarImage);
            SubscribeOnChanged(FrameImage);
            SubscribeOnChanged(NameText);
            SubscribeOnChanged(DescriptionContainer);
            SubscribeOnChanged(LableText);
            SubscribeOnChanged(LevelImage);
            SubscribeOnChanged(LevelText);
            SubscribeOnChanged(DescriptionText);
            SubscribeOnChanged(ButtonsLayout);
            SubscribeOnChanged(SaveButton);
            SubscribeOnChanged(MaskImage1);
            SubscribeOnChanged(BackgroundImageWhite1);
            SubscribeOnChanged(BorderImage1);
            SubscribeOnChanged(OKText);
            SubscribeOnChanged(BackButton);
            SubscribeOnChanged(MaskImage2);
            SubscribeOnChanged(BackgroundImageWhite2);
            SubscribeOnChanged(BorderImage2);
            SubscribeOnChanged(OKText1);
        }
        
        [VisibleInGraph(false)]
        public LobbyDuelSelectDeckView Build()
        {
            OnBuildSafe(true);
            return this;
        }
        #region Static Methods
        public static void ShowInstance() => Instance.Show();
        public static void HideInstance() => Instance.Hide();
        public static void CloseInstance() => Instance.Close();
        #endregion
    }
}