/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using UnityEngine.UI;
using RR.UI;
using RR.UI.FrameSystem;
using UI;

namespace BerserkV3.Lobby.UI.Leagues
{
    public partial class LobbyLeaguesView : RR.UI.FrameSystem.BaseView //Autogenerated
    {
        public static BerserkV3.Lobby.UI.Leagues.LobbyLeaguesView Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        [Header("Controls (auto capture)")]
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform LeftPanel = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI InfoText = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform DecksPanel = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform RightPanel = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image PlayerInfo = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI NameText = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI MMRText = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform LeaguesPanel = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Button League1 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image SelectionImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Button League2 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image SelectionImage1 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Button League3 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image SelectionImage2 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image LeagueInfo = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI NameText1 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Button InfoButton = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI MMRText1 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform ButtonsPanel = default;
        [AutoGenerated, SerializeField] protected ButtonView BackButton = default;
        [AutoGenerated, SerializeField] protected ButtonView PlayButton = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image DividerImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image ShadowImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform TitleImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image MaskImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BackgroundImageWhite = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI TitleText = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BorderImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform TutorialLeagueMMR = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform TutorialLeagueFlags = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform TutorialLeagueDecks = default;
        #pragma warning restore 0414
        
        protected override void AutoInit()
        {
            Instance = this;
        }
        
        protected override void AutoSubscribe()
        {
            SubscribeOnChanged(LeftPanel);
            SubscribeOnChanged(InfoText);
            SubscribeOnChanged(DecksPanel);
            SubscribeOnChanged(RightPanel);
            SubscribeOnChanged(PlayerInfo);
            SubscribeOnChanged(NameText);
            SubscribeOnChanged(MMRText);
            SubscribeOnChanged(LeaguesPanel);
            SubscribeOnChanged(League1);
            SubscribeOnChanged(SelectionImage);
            SubscribeOnChanged(League2);
            SubscribeOnChanged(SelectionImage1);
            SubscribeOnChanged(League3);
            SubscribeOnChanged(SelectionImage2);
            SubscribeOnChanged(LeagueInfo);
            SubscribeOnChanged(NameText1);
            SubscribeOnChanged(InfoButton);
            SubscribeOnChanged(MMRText1);
            SubscribeOnChanged(ButtonsPanel);
            SubscribeOnChanged(BackButton);
            SubscribeOnChanged(PlayButton);
            SubscribeOnChanged(DividerImage);
            SubscribeOnChanged(ShadowImage);
            SubscribeOnChanged(TitleImage);
            SubscribeOnChanged(MaskImage);
            SubscribeOnChanged(BackgroundImageWhite);
            SubscribeOnChanged(TitleText);
            SubscribeOnChanged(BorderImage);
            SubscribeOnChanged(TutorialLeagueMMR);
            SubscribeOnChanged(TutorialLeagueFlags);
            SubscribeOnChanged(TutorialLeagueDecks);
        }
        
        [VisibleInGraph(false)]
        public BerserkV3.Lobby.UI.Leagues.LobbyLeaguesView Build()
        {
            OnBuildSafe(true);
            return this;
        }
        #region Static Methods
        public static void ShowInstance() => Instance.Show();
        public static void HideInstance() => Instance.Hide();
        public static void CloseInstance() => Instance.Close();
        #endregion
    }
}