/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using UnityEngine.UI;
using RR.UI;
using RR.UI.FrameSystem;
using UI;

namespace BerserkV3.Lobby.UI.Leagues
{
    public partial class LobbyLeagueMatchSearchView : RR.UI.FrameSystem.BaseView //Autogenerated
    {
        public static LobbyLeagueMatchSearchView Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        [Header("Controls (auto capture)")]
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform Container = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image Background = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI TitleText = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI TimerText = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform ButtonsLayout = default;
        [AutoGenerated, SerializeField] protected ButtonView CancelBtn = default;
        [AutoGenerated, SerializeField] protected ButtonView DeclineBtn = default;
        [AutoGenerated, SerializeField] protected ButtonView AcceptBtn = default;
        #pragma warning restore 0414
        
        protected override void AutoInit()
        {
            Instance = this;
        }
        
        protected override void AutoSubscribe()
        {
            SubscribeOnChanged(Container);
            SubscribeOnChanged(Background);
            SubscribeOnChanged(TitleText);
            SubscribeOnChanged(TimerText);
            SubscribeOnChanged(ButtonsLayout);
            SubscribeOnChanged(CancelBtn);
            SubscribeOnChanged(DeclineBtn);
            SubscribeOnChanged(AcceptBtn);
        }
        
        [VisibleInGraph(false)]
        public LobbyLeagueMatchSearchView Build()
        {
            OnBuildSafe(true);
            return this;
        }
        #region Static Methods
        public static void ShowInstance() => Instance.Show();
        public static void HideInstance() => Instance.Hide();
        public static void CloseInstance() => Instance.Close();
        #endregion
    }
}