/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using UnityEngine.UI;
using RR.UI;
using RR.UI.FrameSystem;
using TMPro;

namespace BerserkV3.Lobby.UI.Duels
{
    public partial class LobbyDuelJoinView : BerserkV3.Startup.UI.SafeView //Autogenerated
    {
        public static LobbyDuelJoinView Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        [Header("Controls (auto capture)")]
        [AutoGenerated, SerializeField] protected UnityEngine.CanvasGroup Content = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform TitleImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image MaskImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BackgroundImageWhite = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI TitleText = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BorderImage = default;
        [AutoGenerated, SerializeField] protected TMP_InputField RoomCodeInput = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image RoomCodeInputBackground = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image RoomCodeTextArea = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI RoomCodePlaceholder = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI RoomCodeText = default;
        [AutoGenerated, SerializeField] protected TMP_InputField PasswordInput = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image PasswordInputBackground = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image PasswordTextArea = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI PasswordPlaceholder = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI PasswordText = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform ButtonsLayout = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Button CancelButton = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image MaskImage1 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BackgroundImageRed = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BorderImage1 = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI CancelTxt = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Button OKButton = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image MaskImage2 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BackgroundImageRed1 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BorderImage2 = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI OKText = default;
        #pragma warning restore 0414
        
        protected override void AutoInit()
        {
            Instance = this;
        }
        
        protected override void AutoSubscribe()
        {
            SubscribeOnChanged(Content);
            SubscribeOnChanged(TitleImage);
            SubscribeOnChanged(MaskImage);
            SubscribeOnChanged(BackgroundImageWhite);
            SubscribeOnChanged(TitleText);
            SubscribeOnChanged(BorderImage);
            SubscribeOnChanged(RoomCodeInput);
            SubscribeOnChanged(RoomCodeInputBackground);
            SubscribeOnChanged(RoomCodeTextArea);
            SubscribeOnChanged(RoomCodePlaceholder);
            SubscribeOnChanged(RoomCodeText);
            SubscribeOnChanged(PasswordInput);
            SubscribeOnChanged(PasswordInputBackground);
            SubscribeOnChanged(PasswordTextArea);
            SubscribeOnChanged(PasswordPlaceholder);
            SubscribeOnChanged(PasswordText);
            SubscribeOnChanged(ButtonsLayout);
            SubscribeOnChanged(CancelButton);
            SubscribeOnChanged(MaskImage1);
            SubscribeOnChanged(BackgroundImageRed);
            SubscribeOnChanged(BorderImage1);
            SubscribeOnChanged(CancelTxt);
            SubscribeOnChanged(OKButton);
            SubscribeOnChanged(MaskImage2);
            SubscribeOnChanged(BackgroundImageRed1);
            SubscribeOnChanged(BorderImage2);
            SubscribeOnChanged(OKText);
        }
        
        [VisibleInGraph(false)]
        public LobbyDuelJoinView Build()
        {
            OnBuildSafe(true);
            return this;
        }
        #region Static Methods
        public static void ShowInstance() => Instance.Show();
        public static void HideInstance() => Instance.Hide();
        public static void CloseInstance() => Instance.Close();
        #endregion
    }
}