/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using UnityEngine.UI;
using RR.UI;
using RR.UI.FrameSystem;
using UI;

namespace BerserkV3.Lobby.UI
{
    public partial class SelectFirstVulcaniteView : Global.View //Autogenerated
    {
        public static SelectFirstVulcaniteView Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        [Header("Controls (auto capture)")]
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform Container = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image Background = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform TitleImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image MaskImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BackgroundImageWhite = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI TitleText = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BorderImage = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI HeaderText = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.ScrollRect ScrollRect = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform ScrollViewport = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image ScrollBackground = default;
        [AutoGenerated, SerializeField] protected BerserkV3.Common.UIKit.HorizontalHexagoneLayout ScrollHexagoneLayout = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Scrollbar ScrollbarVertical = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform SlidingArea = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image Handle = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform ButtonsPnl = default;
        [AutoGenerated, SerializeField] protected ButtonView OKButton = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI DesriptionText = default;
        #pragma warning restore 0414
        
        protected override void AutoInit()
        {
            Instance = this;
        }
        
        protected override void AutoSubscribe()
        {
            SubscribeOnChanged(Container);
            SubscribeOnChanged(Background);
            SubscribeOnChanged(TitleImage);
            SubscribeOnChanged(MaskImage);
            SubscribeOnChanged(BackgroundImageWhite);
            SubscribeOnChanged(TitleText);
            SubscribeOnChanged(BorderImage);
            SubscribeOnChanged(HeaderText);
            SubscribeOnChanged(ScrollRect);
            SubscribeOnChanged(ScrollViewport);
            SubscribeOnChanged(ScrollBackground);
            SubscribeOnChanged(ScrollHexagoneLayout);
            SubscribeOnChanged(ScrollbarVertical);
            SubscribeOnChanged(SlidingArea);
            SubscribeOnChanged(Handle);
            SubscribeOnChanged(ButtonsPnl);
            SubscribeOnChanged(OKButton);
            SubscribeOnChanged(DesriptionText);
        }
        
        [VisibleInGraph(false)]
        public SelectFirstVulcaniteView Build()
        {
            OnBuildSafe(true);
            return this;
        }
        #region Static Methods
        public static void ShowInstance() => Instance.Show();
        public static void HideInstance() => Instance.Hide();
        public static void CloseInstance() => Instance.Close();
        #endregion
    }
}