using System.IO;
using RR.Core.DebugSystem;
using RR.Core.Editor;
using RR.Core.Editor.Extensions;
using RR.Game.Editor.SettingSystem;
using RR.Game.SettingSystem;
using Sirenix.OdinInspector;
using Sirenix.OdinInspector.Editor;
using Sirenix.Utilities;
using UnityEditor;
using UnityEngine;

namespace Assets.RR.Game.Editor
{
	[CustomEditor(typeof(GameSettings), true)]
	public class GameSettingsEditor : OdinEditor
	{
		private GameSettings self;

		protected override void OnEnable()
		{
			self = target as GameSettings;

			self.OnChanged += GenerateSettingsClass;
		}

		public override void OnInspectorGUI()
		{
			DrawTree();
			GUILayout.Space(24);

			if (GUILayout.Button("Generate Settings"))
				GenerateSettingsClass();

			var _className = EditorGUILayout.TextField(nameof(className).SplitPascalCase(), className);
			if (className != _className)
			{
				className = _className;
				ValidateScriptFilePath();
			}

			namespaceName = EditorGUILayout.TextField(nameof(namespaceName).SplitPascalCase(), namespaceName);
			folderPath = EditorGUILayout.TextField(nameof(folderPath).SplitPascalCase(), folderPath);
		}

		private void GenerateSettingsClass()
		{
			SettingsClassGenerator.Generate(self.ParameterGroups, className, namespaceName, folderPath);
		}

		[SerializeField]
		private string className = "Settings";

		[SerializeField]
		private string namespaceName = "RR.Settings";

		[SerializeField, FolderPath]
		private string folderPath = "Assets/Scripts/_autogenerated/";

		private void ValidateScriptFilePath()
		{
			RRLogger.Log(nameof(ValidateScriptFilePath));

			var obj = AssetDatabase.LoadAssetAtPath<Object>(Path.Combine(folderPath, className + ".cs"));
			if (obj != null)
				EditorUtility.DisplayDialog("Warning", "There is another file on the same path. That file will be overwritten!", "Okay");
		}

		// TODO Add import/export
		[TabGroup("Import & Export")]
		[Space]
		[InfoBox("Coming soon: Import properties from static class fields")]
		[AssetSelector(Paths = "Assets/Scripts", Filter = "t: Script")]
		[ShowInInspector]
		private UnityEngine.Object scriptReference;
	}
}