using RR.Core.Editor.CodeGeneration;
using RR.Core.Utilities;
using System.Collections.Generic;
using System.Text;
using RR.Game.SettingSystem;

namespace RR.Game.Editor.SettingSystem
{
	public static class SettingsClassGenerator
    {
        private const string Extension = ".cs";

        private static readonly string SettingsNamespace = typeof(SettingsManager).Namespace;
        
        public static void Generate(IEnumerable<SettingParameterGroup> settingGroups, string className, string namespaceName, string folderPath)
        {
            var sb = new StringBuilder();

            foreach (var group in settingGroups)
            {
                if (group.Parameters == null || group.Parameters.Count == 0)
                    continue;
                
                var groupStr = GetSettingsGroupStr(group);
                
                sb.AppendLine(groupStr);
            }

            var contentStr = sb.ToString();
            var classBuilder = new ClassTextBuilder(className);

            var classText = classBuilder
                .AddUsingNamespace(SettingsNamespace)
                .SetNamespace(namespaceName)
                .SetAsStatic()
                .AddSummary("\nThis script is autogenerated!\nDO NOT MODIFY DIRECTLY!\n")
                .InsertContent(contentStr)
                .Build();

            FileUtility.CreateAssetFile(className, Extension, classText, folderPath, true);
        }

        private static string GetSettingsGroupStr(SettingParameterGroup group)
        {
            var sb = new StringBuilder();

            var groupClassBuilder = new ClassTextBuilder(group.Name);

            if (!string.IsNullOrWhiteSpace(group.Description))
            {
                sb.AppendLine($"\t/// <summary>");
                sb.AppendLine($"\t/// {group.Description}");
                sb.Append($"\t/// </summary>");
            }

            var preclassContent = sb.ToString();
            sb.Clear();
            
            for (var i = 0; i < group.Parameters.Count - 1; i++)
                sb.AppendLine(GetParametrStr(group.Parameters[i], group));
            
            sb.Append(GetParametrStr(group.Parameters[group.Parameters.Count - 1], group));

            var groupClassText = groupClassBuilder
                .SetPreclassContent(preclassContent)
                .SetIndentLevel(1)
                .SetAsStatic()
                .InsertContent(sb.ToString())
                .Build();

            return groupClassText;
        }
        
        private static string GetParametrStr(SettingParameter parameter, SettingParameterGroup group)
        {
            var sb = new StringBuilder();
            
            var name = parameter.Name;
            var key = SettingsHelper.CreateKey(parameter.Name, group.Name);
            var description = parameter.Description;
            var typeStr = parameter.ParameterValue.ValueType.ToString().ToLower();
            var getMehtodNameStr = "Get" + parameter.ParameterValue.ValueType;

            if (!string.IsNullOrWhiteSpace(description))
            {
                sb.AppendLine($"\t/// <summary>");
                sb.AppendLine($"\t/// {description}");
                sb.AppendLine($"\t/// </summary>");
            }
            
            sb.Append($"\tpublic static {typeStr} {name} => {nameof(SettingsManager)}.{getMehtodNameStr}(\"{key}\");");

            return sb.ToString();
        }
    }
}
