/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using UnityEngine.UI;
using RR.UI;
using RR.UI.FrameSystem;

namespace RR.UI.Predefined
{
    public partial class DataEditorView : BaseView //Autogenerated
    {
        /// <summary>Static instance of the view</summary>
        public static DataEditorView Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        [Header("Controls (auto capture)")]
        [AutoGenerated, SerializeField] UnityEngine.RectTransform TopPanel = default;
        [AutoGenerated, SerializeField] TMPro.TextMeshProUGUI Title = default;
        [AutoGenerated, SerializeField] UnityEngine.RectTransform MidPannel = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.Image InputOneLine = default;
        [AutoGenerated, SerializeField] TMPro.TextMeshProUGUI InputOneLineFieldName = default;
        [AutoGenerated, SerializeField] TMPro.TMP_InputField InputOneLineInputField = default;
        [AutoGenerated, SerializeField] UnityEngine.RectTransform TextArea = default;
        [AutoGenerated, SerializeField] TMPro.TextMeshProUGUI Placeholder = default;
        [AutoGenerated, SerializeField] TMPro.TextMeshProUGUI Text = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.Image InputMultyLine = default;
        [AutoGenerated, SerializeField] TMPro.TextMeshProUGUI InputMultyLineFieldName = default;
        [AutoGenerated, SerializeField] TMPro.TMP_InputField InputMultyLineInputField = default;
        [AutoGenerated, SerializeField] UnityEngine.RectTransform TextArea1 = default;
        [AutoGenerated, SerializeField] TMPro.TextMeshProUGUI Placeholder1 = default;
        [AutoGenerated, SerializeField] TMPro.TextMeshProUGUI Text1 = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.Scrollbar Scrollbar = default;
        [AutoGenerated, SerializeField] UnityEngine.RectTransform SlidingArea = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.Image Handle = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.Image InputBool = default;
        [AutoGenerated, SerializeField] TMPro.TextMeshProUGUI InputBoolFieldName = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.Toggle InputBoolToggle = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.Image Background = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.Image Checkmark = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.Image InputDecimal = default;
        [AutoGenerated, SerializeField] TMPro.TextMeshProUGUI InputDecimalFieldName = default;
        [AutoGenerated, SerializeField] TMPro.TMP_InputField InputDecimalInputField = default;
        [AutoGenerated, SerializeField] UnityEngine.RectTransform TextArea2 = default;
        [AutoGenerated, SerializeField] TMPro.TextMeshProUGUI Placeholder2 = default;
        [AutoGenerated, SerializeField] TMPro.TextMeshProUGUI Text2 = default;
        [AutoGenerated, SerializeField] UnityEngine.RectTransform Placeholder3 = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.Image InputDropdown = default;
        [AutoGenerated, SerializeField] TMPro.TextMeshProUGUI InputDropdownFieldName = default;
        [AutoGenerated, SerializeField] TMPro.TMP_Dropdown InputDropdownDropdown = default;
        [AutoGenerated, SerializeField] TMPro.TextMeshProUGUI Label = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.Image Arrow = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.ScrollRect Template = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.Image Viewport = default;
        [AutoGenerated, SerializeField] UnityEngine.RectTransform Content = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.Toggle Item = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.Image ItemBackground = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.Image ItemCheckmark = default;
        [AutoGenerated, SerializeField] TMPro.TextMeshProUGUI ItemLabel = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.Scrollbar Scrollbar1 = default;
        [AutoGenerated, SerializeField] UnityEngine.RectTransform SlidingArea1 = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.Image Handle1 = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.Image InputFile = default;
        [AutoGenerated, SerializeField] TMPro.TextMeshProUGUI InputFileFieldName = default;
        [AutoGenerated, SerializeField] UnityEngine.RectTransform Panel = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.Button InputFileButton = default;
        [AutoGenerated, SerializeField] TMPro.TextMeshProUGUI InputFileButtonText = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.Text InputFileLinkHidden = default;
        [AutoGenerated, SerializeField] TMPro.TMP_InputField InputFileInputField = default;
        [AutoGenerated, SerializeField] UnityEngine.RectTransform TextArea3 = default;
        [AutoGenerated, SerializeField] TMPro.TextMeshProUGUI Placeholder4 = default;
        [AutoGenerated, SerializeField] TMPro.TextMeshProUGUI Text3 = default;
        [AutoGenerated, SerializeField] UnityEngine.RectTransform BottomPanel = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.Button DeleteBtn = default;
        [AutoGenerated, SerializeField] TMPro.TextMeshProUGUI deleteText = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.Button ResetBtn = default;
        [AutoGenerated, SerializeField] TMPro.TextMeshProUGUI Text4 = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.Button btCancel = default;
        [AutoGenerated, SerializeField] TMPro.TextMeshProUGUI Text5 = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.Button btOk = default;
        [AutoGenerated, SerializeField] TMPro.TextMeshProUGUI okText = default;
        [AutoGenerated, SerializeField] UnityEngine.RectTransform Border = default;
        #pragma warning restore 0414
        
        protected override void AutoInit()
        {
            Instance = this;
        }
        
        protected override void AutoSubscribe()
        {
            SubscribeOnChanged(TopPanel);
            SubscribeOnChanged(Title);
            SubscribeOnChanged(MidPannel);
            SubscribeOnChanged(InputOneLine);
            SubscribeOnChanged(InputOneLineFieldName);
            SubscribeOnChanged(InputOneLineInputField);
            SubscribeOnChanged(TextArea);
            SubscribeOnChanged(Placeholder);
            SubscribeOnChanged(Text);
            SubscribeOnChanged(InputMultyLine);
            SubscribeOnChanged(InputMultyLineFieldName);
            SubscribeOnChanged(InputMultyLineInputField);
            SubscribeOnChanged(TextArea1);
            SubscribeOnChanged(Placeholder1);
            SubscribeOnChanged(Text1);
            SubscribeOnChanged(Scrollbar);
            SubscribeOnChanged(SlidingArea);
            SubscribeOnChanged(Handle);
            SubscribeOnChanged(InputBool);
            SubscribeOnChanged(InputBoolFieldName);
            SubscribeOnChanged(InputBoolToggle);
            SubscribeOnChanged(Background);
            SubscribeOnChanged(Checkmark);
            SubscribeOnChanged(InputDecimal);
            SubscribeOnChanged(InputDecimalFieldName);
            SubscribeOnChanged(InputDecimalInputField);
            SubscribeOnChanged(TextArea2);
            SubscribeOnChanged(Placeholder2);
            SubscribeOnChanged(Text2);
            SubscribeOnChanged(Placeholder3);
            SubscribeOnChanged(InputDropdown);
            SubscribeOnChanged(InputDropdownFieldName);
            SubscribeOnChanged(InputDropdownDropdown);
            SubscribeOnChanged(Label);
            SubscribeOnChanged(Arrow);
            SubscribeOnChanged(Template);
            SubscribeOnChanged(Viewport);
            SubscribeOnChanged(Content);
            SubscribeOnChanged(Item);
            SubscribeOnChanged(ItemBackground);
            SubscribeOnChanged(ItemCheckmark);
            SubscribeOnChanged(ItemLabel);
            SubscribeOnChanged(Scrollbar1);
            SubscribeOnChanged(SlidingArea1);
            SubscribeOnChanged(Handle1);
            SubscribeOnChanged(InputFile);
            SubscribeOnChanged(InputFileFieldName);
            SubscribeOnChanged(Panel);
            SubscribeOnChanged(InputFileButton);
            SubscribeOnChanged(InputFileButtonText);
            SubscribeOnChanged(InputFileLinkHidden);
            SubscribeOnChanged(InputFileInputField);
            SubscribeOnChanged(TextArea3);
            SubscribeOnChanged(Placeholder4);
            SubscribeOnChanged(Text3);
            SubscribeOnChanged(BottomPanel);
            SubscribeOnChanged(DeleteBtn);
            SubscribeOnChanged(deleteText);
            SubscribeOnChanged(ResetBtn);
            SubscribeOnChanged(Text4);
            SubscribeOnChanged(btCancel);
            SubscribeOnChanged(Text5);
            SubscribeOnChanged(btOk);
            SubscribeOnChanged(okText);
            SubscribeOnChanged(Border);
        }
        ///<summary>Data</summary>
        public object Data{ get; private set; }
        public Action<object> OnSaved{ get; private set; }
        public Action OnDelete{ get; private set; }
        
        [VisibleInGraph(false)]
        public DataEditorView Build(object Data, Action<object> OnSaved=null, Action OnDelete=null)
        {
            this.Data = Data;
            this.OnSaved = OnSaved;
            this.OnDelete = OnDelete;
            OnBuildSafe(true);
            return this;
        }
        
        public override BaseView Clone()
        {
            var clone = (DataEditorView)base.Clone();
            clone.Data = Data;
            clone.OnSaved = OnSaved;
            clone.OnDelete = OnDelete;
            return clone;
        }
    }
}