/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using UnityEngine.UI;
using RR.UI;
using RR.UI.FrameSystem;

namespace RR.UI.Predefined
{
	public partial class DialogInput : BaseView //Autogenerated
	{
		/// <summary>Static instance of the view</summary>
		public static DialogInput Instance { get; private set; }
		// Controls
#pragma warning disable 0414
		[Header("Controls (auto capture)")]
		[AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI txMessage = default;
		[AutoGenerated, SerializeField] protected UnityEngine.RectTransform BottomPanel1 = default;
		[AutoGenerated, SerializeField] protected UnityEngine.UI.Button btOk = default;
		[AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI okText = default;
		[AutoGenerated, SerializeField] protected UnityEngine.UI.Button btCancel = default;
		[AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI cancelText = default;
		[AutoGenerated, SerializeField] protected TMPro.TMP_InputField InputFieldTMP = default;
		[AutoGenerated, SerializeField] protected UnityEngine.RectTransform TextArea = default;
		[AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI txPlaceholder = default;
		[AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI Text = default;
		[AutoGenerated, SerializeField] protected UnityEngine.RectTransform ProceduralImage = default;
#pragma warning restore 0414

		protected override void AutoInit()
		{
			Instance = this;
		}

		protected override void AutoSubscribe()
		{
			Subscribe(btOk, () => { Result = InputFieldTMP.text; Close(() => Destroy(gameObject)); });
			Subscribe(btCancel, () => { Result = null; Close(() => Destroy(gameObject)); });

			SubscribeOnChanged(txMessage);
			SubscribeOnChanged(BottomPanel1);
			SubscribeOnChanged(btOk);
			SubscribeOnChanged(okText);
			SubscribeOnChanged(btCancel);
			SubscribeOnChanged(cancelText);
			SubscribeOnChanged(InputFieldTMP);
			SubscribeOnChanged(TextArea);
			SubscribeOnChanged(txPlaceholder);
			SubscribeOnChanged(Text);
			SubscribeOnChanged(ProceduralImage);
		}
		///<summary>Data</summary>
		public string message { get; private set; }
		public string okTxt { get; private set; }
		public string cancelTxt { get; private set; }
		public string placeholderText { get; private set; }
		public string Result { get; protected set; }

		[VisibleInGraph(false)]
		public DialogInput Build(string message, string okTxt, string cancelTxt, string placeholderText, string Result = null)
		{
			this.message = message;
			this.okTxt = okTxt;
			this.cancelTxt = cancelTxt;
			this.placeholderText = placeholderText;
			this.Result = Result;

			if (!string.IsNullOrEmpty(message))
				txMessage.SetText(message);

			if (!string.IsNullOrEmpty(okTxt))
				okText.SetText(okTxt);

			if (!string.IsNullOrEmpty(cancelTxt))
				cancelText.SetText(cancelTxt);

			if (!string.IsNullOrEmpty(placeholderText))
				InputFieldTMP.text = placeholderText;

			OnBuildSafe(true);
			return this;
		}

		public override BaseView Clone()
		{
			var clone = (DialogInput)base.Clone();
			clone.message = message;
			clone.okTxt = okTxt;
			clone.cancelTxt = cancelTxt;
			clone.placeholderText = placeholderText;
			clone.Result = Result;
			return clone;
		}
	}
}