/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using UnityEngine.UI;
using RR.UI;
using RR.UI.FrameSystem;

namespace BerserkV3.Lobby.UI.LeaderBoard
{
    public partial class LeaderBoardPanelItem : RR.UI.FrameSystem.BaseView //Autogenerated
    {
        public static LeaderBoardPanelItem Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        [Header("Controls (auto capture)")]
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BorderImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BlackImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image OutlineImg = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform AllText = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI PlacePlayerText = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI NicknamePlayerText = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI ELOPlayerText = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI WinsPlayerText = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI GamesPlayerText = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI AverageSessionLengthPlayerText = default;
        #pragma warning restore 0414
        
        protected override void AutoInit()
        {
            Instance = this;
        }
        
        protected override void AutoSubscribe()
        {
            SubscribeOnChanged(BorderImage);
            SubscribeOnChanged(BlackImage);
            SubscribeOnChanged(OutlineImg);
            SubscribeOnChanged(AllText);
            SubscribeOnChanged(PlacePlayerText);
            SubscribeOnChanged(NicknamePlayerText);
            SubscribeOnChanged(ELOPlayerText);
            SubscribeOnChanged(WinsPlayerText);
            SubscribeOnChanged(GamesPlayerText);
            SubscribeOnChanged(AverageSessionLengthPlayerText);
        }
        
        [VisibleInGraph(false)]
        public LeaderBoardPanelItem Build()
        {
            OnBuildSafe(true);
            return this;
        }
        #region Static Methods
        public static void ShowInstance() => Instance.Show();
        public static void HideInstance() => Instance.Hide();
        public static void CloseInstance() => Instance.Close();
        #endregion
    }
}