/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using UnityEngine.UI;
using RR.UI;
using RR.UI.FrameSystem;
using UI;

namespace BerserkV3.Lobby.UI.LeaderBoard
{
    public partial class LeaderBoardLeagueView : RR.UI.FrameSystem.BaseView //Autogenerated
    {
        public static LeaderBoardLeagueView Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        [Header("Controls (auto capture)")]
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image ContentMask = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image VerticalLine = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image VerticalDividingLine = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform LeagueStatsHeader = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI PlacePlayerText = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI NicknamePlayerText = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI ELOPlayerText = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI WinsPlayerText = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI GamesPlayerText = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI AverageSessionLengthPlayerText = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform LeagueHeader = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image LeagueHeaderUnderline = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI LeagueName = default;
        [AutoGenerated, SerializeField] protected BerserkV3.Lobby.UI.LeaderBoard.PlayersInLeaderBoardPanel PlayersInLeaderBoardPanel = default;
        [AutoGenerated, SerializeField] protected BerserkV3.Lobby.UI.LeaderBoard.WhoBeatsWhoLeaderBoardPanel WhoBeatsWhoLeaderBoardPanel = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform WhoBeatsWhoButtons = default;
        [AutoGenerated, SerializeField] protected ButtonView GlobalButton = default;
        [AutoGenerated, SerializeField] protected ButtonView LocalButton = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image GlobalOutlineImg = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image LocalOutlineImg = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform Buttons = default;
        [AutoGenerated, SerializeField] protected ButtonView LastSeasonButton = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI LastSeasonButtonText = default;
        [AutoGenerated, SerializeField] protected ButtonView BackButton = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform TitleImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image MaskImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BackgroundImageWhite = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI TitleText = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BorderImage = default;
        #pragma warning restore 0414
        
        protected override void AutoInit()
        {
            Instance = this;
        }
        
        protected override void AutoSubscribe()
        {
            SubscribeOnChanged(ContentMask);
            SubscribeOnChanged(VerticalLine);
            SubscribeOnChanged(VerticalDividingLine);
            SubscribeOnChanged(LeagueStatsHeader);
            SubscribeOnChanged(PlacePlayerText);
            SubscribeOnChanged(NicknamePlayerText);
            SubscribeOnChanged(ELOPlayerText);
            SubscribeOnChanged(WinsPlayerText);
            SubscribeOnChanged(GamesPlayerText);
            SubscribeOnChanged(AverageSessionLengthPlayerText);
            SubscribeOnChanged(LeagueHeader);
            SubscribeOnChanged(LeagueHeaderUnderline);
            SubscribeOnChanged(LeagueName);
            SubscribeOnChanged(PlayersInLeaderBoardPanel);
            SubscribeOnChanged(WhoBeatsWhoLeaderBoardPanel);
            SubscribeOnChanged(WhoBeatsWhoButtons);
            SubscribeOnChanged(GlobalButton);
            SubscribeOnChanged(LocalOutlineImg);
            SubscribeOnChanged(GlobalOutlineImg);
            SubscribeOnChanged(LocalButton);
            SubscribeOnChanged(Buttons);
            SubscribeOnChanged(LastSeasonButton);
            SubscribeOnChanged(LastSeasonButtonText);
            SubscribeOnChanged(BackButton);
            SubscribeOnChanged(TitleImage);
            SubscribeOnChanged(MaskImage);
            SubscribeOnChanged(BackgroundImageWhite);
            SubscribeOnChanged(TitleText);
            SubscribeOnChanged(BorderImage);
        }
        
        [VisibleInGraph(false)]
        public LeaderBoardLeagueView Build()
        {
            OnBuildSafe(true);
            return this;
        }
        #region Static Methods
        public static void ShowInstance() => Instance.Show();
        public static void HideInstance() => Instance.Hide();
        public static void CloseInstance() => Instance.Close();
        #endregion
    }
}