/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using UnityEngine.UI;
using RR.UI;
using RR.UI.FrameSystem;

namespace BerserkV3.Lobby.UI.LeaderBoard
{
    public partial class WhoBeatsWhoLeaderBoardPanel : RR.UI.FrameSystem.BaseView //Autogenerated
    {
        public static WhoBeatsWhoLeaderBoardPanel Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        [Header("Controls (auto capture)")]
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform ScrollView = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Scrollbar Scrollbar = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform SlidingArea = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image Handle = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image Content = default;
        #pragma warning restore 0414
        
        protected override void AutoInit()
        {
            Instance = this;
        }
        
        protected override void AutoSubscribe()
        {
            SubscribeOnChanged(ScrollView);
            SubscribeOnChanged(Scrollbar);
            SubscribeOnChanged(SlidingArea);
            SubscribeOnChanged(Handle);
            SubscribeOnChanged(Content);
        }
        
        [VisibleInGraph(false)]
        public WhoBeatsWhoLeaderBoardPanel Build()
        {
            OnBuildSafe(true);
            return this;
        }
        #region Static Methods
        public static void ShowInstance() => Instance.Show();
        public static void HideInstance() => Instance.Hide();
        public static void CloseInstance() => Instance.Close();
        #endregion
    }
}