/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using UnityEngine.UI;
using RR.UI;
using RR.UI.FrameSystem;

namespace BerserkV3.Lobby.UI.LeaderBoard
{
    public partial class WhoBeatsWhoPanelItem : RR.UI.FrameSystem.BaseView //Autogenerated
    {
        public static WhoBeatsWhoPanelItem Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        [Header("Controls (auto capture)")]
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BorderImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BlackImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image OutlineImg = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image VS = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform WinnerPlayerText = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform AllText = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI WinnerPlayerMatchResultText = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI WinnerPlayerNicknamePlayerText = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI WinnerPlayerDeltaScoreText = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform LoserPlayerText = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform AllText1 = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI LoserPlayerMatchResultText = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI LoserPlayerNicknamePlayerText = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI LoserPlayerDeltaScoreText = default;
        #pragma warning restore 0414
        
        protected override void AutoInit()
        {
            Instance = this;
        }
        
        protected override void AutoSubscribe()
        {
            SubscribeOnChanged(BorderImage);
            SubscribeOnChanged(BlackImage);
            SubscribeOnChanged(OutlineImg);
            SubscribeOnChanged(VS);
            SubscribeOnChanged(WinnerPlayerText);
            SubscribeOnChanged(AllText);
            SubscribeOnChanged(WinnerPlayerMatchResultText);
            SubscribeOnChanged(WinnerPlayerNicknamePlayerText);
            SubscribeOnChanged(WinnerPlayerDeltaScoreText);
            SubscribeOnChanged(LoserPlayerText);
            SubscribeOnChanged(AllText1);
            SubscribeOnChanged(LoserPlayerMatchResultText);
            SubscribeOnChanged(LoserPlayerNicknamePlayerText);
            SubscribeOnChanged(LoserPlayerDeltaScoreText);
        }
        
        [VisibleInGraph(false)]
        public WhoBeatsWhoPanelItem Build()
        {
            OnBuildSafe(true);
            return this;
        }
        #region Static Methods
        public static void ShowInstance() => Instance.Show();
        public static void HideInstance() => Instance.Hide();
        public static void CloseInstance() => Instance.Close();
        #endregion
    }
}