/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using UnityEngine.UI;
using RR.UI;
using RR.UI.FrameSystem;

namespace BerserkV3.GameCore.UI
{
    public partial class CardHandArtLayout : RR.UI.FrameSystem.BaseView //Autogenerated
    {
        public static CardHandArtLayout Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        [Header("Controls (auto capture)")]
        [AutoGenerated, SerializeField] protected UnityEngine.UI.RawImage ShineImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.RawImage OutlineImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.RawImage ArtImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.RawImage FrameImage = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI TitleText = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI RaceFactionText = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI DescriptionText = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI EffectText = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.RawImage AttackImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.RawImage ArmorImage = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI AttackText = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI ArmorText = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.RawImage HealthImage = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI HealthText = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI LavaText = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.RawImage ArtistBrushImage = default;
        [AutoGenerated, SerializeField] protected RectTransform ArtistLayout = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI ArtistText = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.RawImage RarityImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.RawImage LavaFrameImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.RawImage LavaImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.RawImage FactionFrameImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.RawImage FactionImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.RawImage SeasonFrameImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.RawImage SeasonImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.RawImage QuadrantFrameImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.RawImage QuadrantImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.RawImage ExtraImage = default;
#pragma warning restore 0414
        
        protected override void AutoInit()
        {
            Instance = this;
        }
        
        protected override void AutoSubscribe()
        {
            SubscribeOnChanged(ShineImage);
            SubscribeOnChanged(OutlineImage);
            SubscribeOnChanged(FrameImage);
            SubscribeOnChanged(ArtImage);
            SubscribeOnChanged(TitleText);
            SubscribeOnChanged(RaceFactionText);
            SubscribeOnChanged(DescriptionText);
            SubscribeOnChanged(EffectText);
            SubscribeOnChanged(AttackImage);
            SubscribeOnChanged(AttackText);
            SubscribeOnChanged(HealthImage);
            SubscribeOnChanged(HealthText);
            SubscribeOnChanged(LavaImage);
            SubscribeOnChanged(LavaText);
            SubscribeOnChanged(ArtistBrushImage);
            SubscribeOnChanged(ArtistText);
            SubscribeOnChanged(RarityImage);
            SubscribeOnChanged(LavaFrameImage);
            SubscribeOnChanged(FactionFrameImage);
            SubscribeOnChanged(FactionImage);
            SubscribeOnChanged(SeasonFrameImage);
            SubscribeOnChanged(SeasonImage);
            SubscribeOnChanged(QuadrantFrameImage);
            SubscribeOnChanged(QuadrantImage);
            SubscribeOnChanged(ExtraImage);
            SubscribeOnChanged(ArtistLayout);
        }
        
        [VisibleInGraph(false)]
        public CardHandArtLayout Build()
        {
            OnBuildSafe(true);
            return this;
        }
        #region Static Methods
        public static void ShowInstance() => Instance.Show();
        public static void HideInstance() => Instance.Hide();
        public static void CloseInstance() => Instance.Close();
        #endregion
    }
}