/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using BerserkV3.GameCore.UI;
using UnityEngine.UI;
using RR.UI;
using RR.UI.FrameSystem;

namespace BerserkV3.GameCore.Cards
{
    public partial class CardHandLayout : BerserkV3.GameCore.Cards.BaseCardLayout //Autogenerated
    {
        public static CardHandLayout Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
	    [Header("Controls (auto capture)")]
	    [AutoGenerated, SerializeField] protected BerserkV3.GameCore.UI.CardHandArtView HandCardArtView = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI ExchangeTxt = default;
        #pragma warning restore 0414
        
        protected override void AutoInit()
        {
            Instance = this;
        }
        
        protected override void AutoSubscribe()
        {
            SubscribeOnChanged(HandCardArtView);
            SubscribeOnChanged(ExchangeTxt);
        }
        
        [VisibleInGraph(false)]
        public CardHandLayout Build()
        {
            OnBuildSafe(true);
            return this;
        }
        #region Static Methods
        public static void ShowInstance() => Instance.Show();
        public static void HideInstance() => Instance.Hide();
        public static void CloseInstance() => Instance.Close();
        #endregion
    }
}