/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using UnityEngine.UI;
using RR.UI;
using RR.UI.FrameSystem;

namespace BerserkV3.GameCore.Cards
{
    public partial class CardCreatureLayout : BerserkV3.GameCore.Cards.BaseCardLayout //Autogenerated
    {
        public static CardCreatureLayout Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        [Header("Controls (auto capture)")]
        [AutoGenerated, SerializeField] protected UnityEngine.UI.RawImage TurnGlowImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.RawImage TargetingGlowImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.RawImage SelectionGlowImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.RawImage ArtMaskImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.RawImage ArtImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.RawImage FullArtImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.RawImage ArtBorderImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.RawImage AttackStatImage = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI AttackText = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.RawImage HealthStatImage = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI HealthText = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.RawImage ArmorStatImage = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI ArmorText = default;
        #pragma warning restore 0414
        
        protected override void AutoInit()
        {
            Instance = this;
        }
        
        protected override void AutoSubscribe()
        {
            SubscribeOnChanged(TurnGlowImage);
            SubscribeOnChanged(TargetingGlowImage);
            SubscribeOnChanged(SelectionGlowImage);
            SubscribeOnChanged(ArtMaskImage);
            SubscribeOnChanged(ArtImage);
            SubscribeOnChanged(FullArtImage);
            SubscribeOnChanged(ArtBorderImage);
            SubscribeOnChanged(AttackStatImage);
            SubscribeOnChanged(AttackText);
            SubscribeOnChanged(HealthStatImage);
            SubscribeOnChanged(HealthText);
            SubscribeOnChanged(ArmorStatImage);
            SubscribeOnChanged(ArmorText);
        }
        
        [VisibleInGraph(false)]
        public CardCreatureLayout Build()
        {
            OnBuildSafe(true);
            return this;
        }
        #region Static Methods
        public static void ShowInstance() => Instance.Show();
        public static void HideInstance() => Instance.Hide();
        public static void CloseInstance() => Instance.Close();
        #endregion
    }
}