/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using UnityEngine.UI;
using RR.UI;
using RR.UI.FrameSystem;

namespace BerserkV3.GameCore.UI
{
    public partial class DiscardHandView : RR.UI.FrameSystem.BaseView //Autogenerated
    {
        public static DiscardHandView Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        [Header("Controls (auto capture)")]
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform Container = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI HeaderText = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform MiddleLayout = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform ButtonsLayout = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Button ConfirmBtn = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image MaskImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BackgroundImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BorderImage = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI OKText = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform BottomLayout = default;
        #pragma warning restore 0414
        
        protected override void AutoInit()
        {
            Instance = this;
        }
        
        protected override void AutoSubscribe()
        {
            SubscribeOnChanged(Container);
            SubscribeOnChanged(HeaderText);
            SubscribeOnChanged(MiddleLayout);
            SubscribeOnChanged(ButtonsLayout);
            SubscribeOnChanged(ConfirmBtn);
            SubscribeOnChanged(MaskImage);
            SubscribeOnChanged(BackgroundImage);
            SubscribeOnChanged(BorderImage);
            SubscribeOnChanged(OKText);
            SubscribeOnChanged(BottomLayout);
        }
        
        [VisibleInGraph(false)]
        public DiscardHandView Build()
        {
            OnBuildSafe(true);
            return this;
        }
        #region Static Methods
        public static void ShowInstance() => Instance.Show();
        public static void HideInstance() => Instance.Hide();
        public static void CloseInstance() => Instance.Close();
        #endregion
    }
}