/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using UnityEngine.UI;
using RR.UI;
using RR.UI.FrameSystem;

namespace BerserkV3.GameCore.Cards.EffectHints
{
    public partial class EffectWindowView : RR.UI.FrameSystem.BaseView //Autogenerated
    {
        public static Cards.EffectHints.EffectWindowView Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        [Header("Controls (auto capture)")]
        [AutoGenerated, SerializeField] protected UnityEngine.CanvasGroup ToltipEffectsView = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image ContentMask = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image VerticalLine = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image DeckCardListPanel = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI TitleText = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI TitleText1 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.ScrollRect ScrollView = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image Viewport = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform GainedEffectContainer = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Scrollbar ScrollbarVertical = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform SlidingArea = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image Handle = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.ScrollRect ScrollView2 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image Viewport1 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform InnateEffectContainer = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Scrollbar ScrollbarVertical1 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform SlidingArea1 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image Handle1 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform CardHoverElement = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image CardСover = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI TitleText2 = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI Description = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform ImageContainer = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform TitleImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image Background = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI TitleText3 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Button ExitButton = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image Border = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image CrossImage = default;
        [AutoGenerated, SerializeField] protected BerserkV3.GameCore.UI.CardHandArtView CardHandArtView = default;
        #pragma warning restore 0414
        
        protected override void AutoInit()
        {
            Instance = this;
        }
        
        protected override void AutoSubscribe()
        {
            SubscribeOnChanged(ToltipEffectsView);
            SubscribeOnChanged(ContentMask);
            SubscribeOnChanged(VerticalLine);
            SubscribeOnChanged(DeckCardListPanel);
            SubscribeOnChanged(TitleText);
            SubscribeOnChanged(TitleText1);
            SubscribeOnChanged(ScrollView);
            SubscribeOnChanged(Viewport);
            SubscribeOnChanged(GainedEffectContainer);
            SubscribeOnChanged(ScrollbarVertical);
            SubscribeOnChanged(SlidingArea);
            SubscribeOnChanged(Handle);
            SubscribeOnChanged(ScrollView2);
            SubscribeOnChanged(Viewport1);
            SubscribeOnChanged(InnateEffectContainer);
            SubscribeOnChanged(ScrollbarVertical1);
            SubscribeOnChanged(SlidingArea1);
            SubscribeOnChanged(Handle1);
            SubscribeOnChanged(CardHoverElement);
            SubscribeOnChanged(CardСover);
            SubscribeOnChanged(TitleText2);
            SubscribeOnChanged(Description);
            SubscribeOnChanged(ImageContainer);
            SubscribeOnChanged(TitleImage);
            SubscribeOnChanged(Background);
            SubscribeOnChanged(TitleText3);
            SubscribeOnChanged(ExitButton);
            SubscribeOnChanged(Border);
            SubscribeOnChanged(CrossImage);
            SubscribeOnChanged(CardHandArtView);
        }
        
        [VisibleInGraph(false)]
        public Cards.EffectHints.EffectWindowView Build()
        {
            OnBuildSafe(true);
            return this;
        }
        #region Static Methods
        public static void ShowInstance() => Instance.Show();
        public static void HideInstance() => Instance.Hide();
        public static void CloseInstance() => Instance.Close();
        #endregion
    }
}