/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using UnityEngine.UI;
using RR.UI;
using RR.UI.FrameSystem;

namespace BerserkV3.GameCore.UI
{
    public partial class GameEndPlayerLayout : RR.UI.FrameSystem.BaseView //Autogenerated
    {
        public static GameEndPlayerLayout Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        [Header("Controls (auto capture)")]
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image Background = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.RawImage MaskImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.RawImage AvatarImage = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI StateText = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.RawImage FrameImage = default;
        #pragma warning restore 0414
        
        protected override void AutoInit()
        {
            Instance = this;
        }
        
        protected override void AutoSubscribe()
        {
            SubscribeOnChanged(Background);
            SubscribeOnChanged(MaskImage);
            SubscribeOnChanged(AvatarImage);
            SubscribeOnChanged(StateText);
            SubscribeOnChanged(FrameImage);
        }
        
        [VisibleInGraph(false)]
        public GameEndPlayerLayout Build()
        {
            OnBuildSafe(true);
            return this;
        }
        #region Static Methods
        public static void ShowInstance() => Instance.Show();
        public static void HideInstance() => Instance.Hide();
        public static void CloseInstance() => Instance.Close();
        #endregion
    }
}