/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using UnityEngine.UI;
using RR.UI;
using RR.UI.FrameSystem;

namespace BerserkV3.GameCore.UI
{
    public partial class GameView : RR.UI.FrameSystem.BaseView //Autogenerated
    {
        public static GameView Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        [Header("Controls (auto capture)")]
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform GameContainer = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform HandSelfContainer = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform HandOpponentContainer = default;
        [AutoGenerated, SerializeField] protected UnityEngine.CanvasGroup YourTurnPanelOverlay = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image YourTurnBgImg = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI CommendLevel = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform OpponentSpawnPoint = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform SelfSpawnPoint = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform PlayFieldContainer;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform inShowFirstRow;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform inShowSecondRow;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform SelfContainer;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform SelfHeroPoint;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform OpponentHeroPoint;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform TutorialGameBoardRect;
        #pragma warning restore 0414
        
        protected override void AutoInit()
        {
            Instance = this;
        }
        
        protected override void AutoSubscribe()
        {
            SubscribeOnChanged(GameContainer);
            SubscribeOnChanged(HandSelfContainer);
            SubscribeOnChanged(HandOpponentContainer);
            SubscribeOnChanged(YourTurnPanelOverlay);
            SubscribeOnChanged(YourTurnBgImg);
            SubscribeOnChanged(CommendLevel);
            SubscribeOnChanged(OpponentSpawnPoint);
        }
        
        [VisibleInGraph(false)]
        public GameView Build()
        {
            OnBuildSafe(true);
            return this;
        }
        #region Static Methods
        public static void ShowInstance() => Instance.Show();
        public static void HideInstance() => Instance.Hide();
        public static void CloseInstance() => Instance.Close();
        #endregion
    }
}