/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using BerserkV3.Startup;
using BerserkV3.Startup.Authorization;
using BerserkV3.Startup.UI;
using UnityEngine.UI;
using RR.UI;
using RR.UI.FrameSystem;

namespace BerserkV3.GameCore.UI
{
    public partial class GameSettingsView : SafeView //Autogenerated
    {
        public static GameSettingsView Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        [Header("Controls (auto capture)")]
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform Container = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image Backgound = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform TitleImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image MaskImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BackgroundImage = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI TitleText = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BorderImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform ButtonsPnl = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform MusicContainer = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Slider MusicSlider = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image Background = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image Image = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform HandleSlideArea = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform Handle = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image Handle1 = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI MusicLabel = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform AudioContainer = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Slider AudioSlider = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image Background1 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image Image1 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform HandleSlideArea1 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform Handle2 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image Handle11 = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI AudioLabel = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform BattleButtonsPanel = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Button SurrenderBtn = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image MaskImage1 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BackgroundImage1 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image WhiteFlagImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BorderImage1 = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI OKText = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Button QuitBtn = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image MaskImage2 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BackgroundImage2 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image WhiteFlagImage1 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BorderImage2 = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI OKText1 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Button ReportBtn = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image MaskImage3 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BackgroundImage3 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BorderImage3 = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI OKText2 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Button CloseBtn = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image MaskImage4 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BackgroundImage4 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BorderImage4 = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI OKText3 = default;
        #pragma warning restore 0414
        
        protected override void AutoInit()
        {
            Instance = this;
        }
        
        protected override void AutoSubscribe()
        {
            SubscribeOnChanged(Container);
            SubscribeOnChanged(Backgound);
            SubscribeOnChanged(TitleImage);
            SubscribeOnChanged(MaskImage);
            SubscribeOnChanged(BackgroundImage);
            SubscribeOnChanged(TitleText);
            SubscribeOnChanged(BorderImage);
            SubscribeOnChanged(ButtonsPnl);
            SubscribeOnChanged(MusicContainer);
            SubscribeOnChanged(MusicSlider);
            SubscribeOnChanged(Background);
            SubscribeOnChanged(Image);
            SubscribeOnChanged(HandleSlideArea);
            SubscribeOnChanged(Handle);
            SubscribeOnChanged(Handle1);
            SubscribeOnChanged(MusicLabel);
            SubscribeOnChanged(AudioContainer);
            SubscribeOnChanged(AudioSlider);
            SubscribeOnChanged(Background1);
            SubscribeOnChanged(Image1);
            SubscribeOnChanged(HandleSlideArea1);
            SubscribeOnChanged(Handle2);
            SubscribeOnChanged(Handle11);
            SubscribeOnChanged(AudioLabel);
            SubscribeOnChanged(BattleButtonsPanel);
            SubscribeOnChanged(SurrenderBtn);
            SubscribeOnChanged(MaskImage1);
            SubscribeOnChanged(BackgroundImage1);
            SubscribeOnChanged(WhiteFlagImage);
            SubscribeOnChanged(BorderImage1);
            SubscribeOnChanged(OKText);
            SubscribeOnChanged(QuitBtn);
            SubscribeOnChanged(MaskImage2);
            SubscribeOnChanged(BackgroundImage2);
            SubscribeOnChanged(WhiteFlagImage1);
            SubscribeOnChanged(BorderImage2);
            SubscribeOnChanged(OKText1);
            SubscribeOnChanged(ReportBtn);
            SubscribeOnChanged(MaskImage3);
            SubscribeOnChanged(BackgroundImage3);
            SubscribeOnChanged(BorderImage3);
            SubscribeOnChanged(OKText2);
            SubscribeOnChanged(CloseBtn);
            SubscribeOnChanged(MaskImage4);
            SubscribeOnChanged(BackgroundImage4);
            SubscribeOnChanged(BorderImage4);
            SubscribeOnChanged(OKText3);
        }
        
        [VisibleInGraph(false)]
        public GameSettingsView Build()
        {
            OnBuildSafe(true);
            return this;
        }
        #region Static Methods
        public static void ShowInstance() => Instance.Show();
        public static void HideInstance() => Instance.Hide();
        public static void CloseInstance() => Instance.Close();
        #endregion
    }
}