/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using BerserkV3.Startup;
using BerserkV3.Startup.Authorization;
using BerserkV3.Startup.UI;
using UnityEngine.UI;
using RR.UI;
using RR.UI.FrameSystem;
using UI;
using UnityEngine.Serialization;

namespace BerserkV3.GameCore.UI
{
    public partial class GameEndView : SafeView //Autogenerated
    {
        public static GameEndView Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        [Header("Controls (auto capture)")]
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform Container = default;
        [AutoGenerated, SerializeField] protected GameEndPlayerLayout PlayerDefeatLayout = default;
        [AutoGenerated, SerializeField] protected GameEndPlayerLayout PlayerVictoryLayout = default;
        [AutoGenerated, SerializeField] protected VersusLayout VersusLayout = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI DefeatCommendText = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI VictoryCommendText = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI EndGameReasonText = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform ButtonsLayout = default;
        [AutoGenerated, SerializeField] protected ButtonView CommendButton = default;
        [AutoGenerated, SerializeField] protected ButtonView PlayAgainButton = default;
        [AutoGenerated, SerializeField] protected ButtonView MenuButton = default;
        #pragma warning restore 0414
        
        protected override void AutoInit()
        {
            Instance = this;
        }
        
        protected override void AutoSubscribe()
        {
            SubscribeOnChanged(Container);
            SubscribeOnChanged(PlayerDefeatLayout);
            SubscribeOnChanged(PlayerVictoryLayout);
            SubscribeOnChanged(VersusLayout);
            SubscribeOnChanged(DefeatCommendText);
            SubscribeOnChanged(VictoryCommendText);
            SubscribeOnChanged(EndGameReasonText);
            SubscribeOnChanged(ButtonsLayout);
            SubscribeOnChanged(CommendButton);
            SubscribeOnChanged(PlayAgainButton);
            SubscribeOnChanged(MenuButton);
        }
        
        [VisibleInGraph(false)]
        public GameEndView Build()
        {
            OnBuildSafe(true);
            return this;
        }
        #region Static Methods
        public static void ShowInstance() => Instance.Show();
        public static void HideInstance() => Instance.Hide();
        public static void CloseInstance() => Instance.Close();
        #endregion
    }
}