/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////

using UnityEngine;
using RR.UI.FrameSystem;

namespace BerserkV3.GameCore.Cards
{
    public partial class HeroLayout : BerserkV3.GameCore.Cards.CardCreatureLayout //Autogenerated
    {
        public new static HeroLayout Instance { get; private set; }
        
        protected override void AutoInit()
        {
            Instance = this;
        }
        
        protected override void AutoSubscribe()
        {
        }
        
        [VisibleInGraph(false)]
        public HeroLayout Build()
        {
            OnBuildSafe(true);
            return this;
        }
        #region Static Methods
        public static void ShowInstance() => Instance.Show();
        public static void HideInstance() => Instance.Hide();
        public static void CloseInstance() => Instance.Close();
        #endregion
    }
}