/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using UnityEngine.UI;
using RR.UI;
using RR.UI.FrameSystem;

namespace BerserkV3.GameCore.UI
{
    public partial class MulliganView : RR.UI.FrameSystem.BaseView //Autogenerated
    {
        public static MulliganView Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        [Header("Controls (auto capture)")]
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI TitleText = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI InfoText = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform CardsContainer = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform ReplaceCardsContainer = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI WaitingOpponentText = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI TimerText = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Button DoneBtn = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image MaskImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BackgroundImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BorderImage = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI OKText = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI SelfTurnText = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI OpponentTurnText = default;
        #pragma warning restore 0414
        
        protected override void AutoInit()
        {
            Instance = this;
        }
        
        protected override void AutoSubscribe()
        {
            SubscribeOnChanged(TitleText);
            SubscribeOnChanged(InfoText);
            SubscribeOnChanged(CardsContainer);
            SubscribeOnChanged(WaitingOpponentText);
            SubscribeOnChanged(TimerText);
            SubscribeOnChanged(DoneBtn);
            SubscribeOnChanged(MaskImage);
            SubscribeOnChanged(BackgroundImage);
            SubscribeOnChanged(BorderImage);
            SubscribeOnChanged(OKText);
            SubscribeOnChanged(SelfTurnText);
            SubscribeOnChanged(OpponentTurnText);
        }
        
        [VisibleInGraph(false)]
        public MulliganView Build()
        {
            OnBuildSafe(true);
            return this;
        }
        #region Static Methods
        public static void ShowInstance() => Instance.Show();
        public static void HideInstance() => Instance.Hide();
        public static void CloseInstance() => Instance.Close();
        #endregion
    }
}