/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using UnityEngine.UI;
using RR.UI;
using RR.UI.FrameSystem;

namespace BerserkV3.GameCore.UI
{
    public partial class ReportView : RR.UI.FrameSystem.BaseView //Autogenerated
    {
        public static ReportView Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        [Header("Controls (auto capture)")]
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image ModalImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform TitleImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image MaskImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BackgroundImage = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI TitleText = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BorderImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform ButtonsPnl = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Button BackBtn = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image MaskImage1 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BackgroundImage1 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BorderImage1 = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI BackText = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Button ReportBtn = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image MaskImage2 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BackgroundImage2 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BorderImage2 = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI ReportText = default;
        [AutoGenerated, SerializeField] protected TMPro.TMP_Dropdown ReasonDropdown = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image MaskImage3 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BackgroundImage3 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BorderImage3 = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI Label = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image Arrow = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.ScrollRect Template = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image Viewport = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform Content = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Toggle Item = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image ItemBackground = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI ItemLabel = default;
        #pragma warning restore 0414
        
        protected override void AutoInit()
        {
            Instance = this;
        }
        
        protected override void AutoSubscribe()
        {
            SubscribeOnChanged(ModalImage);
            SubscribeOnChanged(TitleImage);
            SubscribeOnChanged(MaskImage);
            SubscribeOnChanged(BackgroundImage);
            SubscribeOnChanged(TitleText);
            SubscribeOnChanged(BorderImage);
            SubscribeOnChanged(ButtonsPnl);
            SubscribeOnChanged(BackBtn);
            SubscribeOnChanged(MaskImage1);
            SubscribeOnChanged(BackgroundImage1);
            SubscribeOnChanged(BorderImage1);
            SubscribeOnChanged(BackText);
            SubscribeOnChanged(ReportBtn);
            SubscribeOnChanged(MaskImage2);
            SubscribeOnChanged(BackgroundImage2);
            SubscribeOnChanged(BorderImage2);
            SubscribeOnChanged(ReportText);
            SubscribeOnChanged(ReasonDropdown);
            SubscribeOnChanged(MaskImage3);
            SubscribeOnChanged(BackgroundImage3);
            SubscribeOnChanged(BorderImage3);
            SubscribeOnChanged(Label);
            SubscribeOnChanged(Arrow);
            SubscribeOnChanged(Template);
            SubscribeOnChanged(Viewport);
            SubscribeOnChanged(Content);
            SubscribeOnChanged(Item);
            SubscribeOnChanged(ItemBackground);
            SubscribeOnChanged(ItemLabel);
        }
        
        [VisibleInGraph(false)]
        public ReportView Build()
        {
            OnBuildSafe(true);
            return this;
        }
        #region Static Methods
        public static void ShowInstance() => Instance.Show();
        public static void HideInstance() => Instance.Hide();
        public static void CloseInstance() => Instance.Close();
        #endregion
    }
}