/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using UnityEngine.UI;
using RR.UI;
using RR.UI.FrameSystem;

namespace BerserkV3.GameCore.UI
{
    public partial class ResurrectXHandView : RR.UI.FrameSystem.BaseView //Autogenerated
    {
        public static ResurrectXHandView Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        [Header("Controls (auto capture)")]
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image FullfadeScreen = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform Container = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI HeaderText = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.ScrollRect ScrollRect = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image ScrollRectViewport = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform ScrollRectContent = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Scrollbar ScrollbarVertical = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform SlidingArea = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image Handle = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform ButtonsLayout = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Button ConfirmBtn = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image MaskImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BackgroundImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BorderImage = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI OKText = default;
        #pragma warning restore 0414
        
        protected override void AutoInit()
        {
            Instance = this;
        }
        
        protected override void AutoSubscribe()
        {
            SubscribeOnChanged(FullfadeScreen);
            SubscribeOnChanged(Container);
            SubscribeOnChanged(HeaderText);
            SubscribeOnChanged(ScrollRect);
            SubscribeOnChanged(ScrollRectViewport);
            SubscribeOnChanged(ScrollRectContent);
            SubscribeOnChanged(ScrollbarVertical);
            SubscribeOnChanged(SlidingArea);
            SubscribeOnChanged(Handle);
            SubscribeOnChanged(ButtonsLayout);
            SubscribeOnChanged(ConfirmBtn);
            SubscribeOnChanged(MaskImage);
            SubscribeOnChanged(BackgroundImage);
            SubscribeOnChanged(BorderImage);
            SubscribeOnChanged(OKText);
        }
        
        [VisibleInGraph(false)]
        public ResurrectXHandView Build()
        {
            OnBuildSafe(true);
            return this;
        }
        #region Static Methods
        public static void ShowInstance() => Instance.Show();
        public static void HideInstance() => Instance.Hide();
        public static void CloseInstance() => Instance.Close();
        #endregion
    }
}