/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using UnityEngine.UI;
using RR.UI;
using RR.UI.FrameSystem;

namespace BerserkV3.GameCore.UI
{
	public partial class TimerView : RR.UI.FrameSystem.BaseView //Autogenerated
    {
        public static TimerView Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        [Header("Controls (auto capture)")]
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform SelfTurnPanel = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI EndTurnTxt = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image TimerImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image EndTurnImage = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI EndTurnTxt1 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image TimerImage1 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image EndTurnImage1 = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI EndTurnTxt2 = default;
        #pragma warning restore 0414
        
        protected override void AutoInit()
        {
            Instance = this;
        }
        
        protected override void AutoSubscribe()
        {
            SubscribeOnChanged(SelfTurnPanel);
            SubscribeOnChanged(EndTurnTxt);
            SubscribeOnChanged(TimerImage);
            SubscribeOnChanged(EndTurnImage);
            SubscribeOnChanged(EndTurnTxt1);
            SubscribeOnChanged(TimerImage1);
            SubscribeOnChanged(EndTurnImage1);
            SubscribeOnChanged(EndTurnTxt2);
        }
        
        [VisibleInGraph(false)]
        public TimerView Build()
        {
            OnBuildSafe(true);
            return this;
        }
        #region Static Methods
        public static void ShowInstance() => Instance.Show();
        public static void HideInstance() => Instance.Hide();
        public static void CloseInstance() => Instance.Close();
        #endregion
    }
}