/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using UnityEngine.UI;
using RR.UI;
using RR.UI.FrameSystem;

namespace BerserkV3.GameCore.UI
{
    public partial class VersusLayout : RR.UI.FrameSystem.BaseView //Autogenerated
    {
        public static VersusLayout Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        [Header("Controls (auto capture)")]
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image Background = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image VersusImage = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI Player1NameText = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI Player2NameText = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI Player1MMRText = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI Player2MMRText = default;
        #pragma warning restore 0414
        
        protected override void AutoInit()
        {
            Instance = this;
        }
        
        protected override void AutoSubscribe()
        {
            SubscribeOnChanged(Background);
            SubscribeOnChanged(VersusImage);
            SubscribeOnChanged(Player1NameText);
            SubscribeOnChanged(Player2NameText);
            SubscribeOnChanged(Player1MMRText);
            SubscribeOnChanged(Player2MMRText);
        }
        
        [VisibleInGraph(false)]
        public VersusLayout Build()
        {
            OnBuildSafe(true);
            return this;
        }
        #region Static Methods
        public static void ShowInstance() => Instance.Show();
        public static void HideInstance() => Instance.Hide();
        public static void CloseInstance() => Instance.Close();
        #endregion
    }
}