using BerserkV3.Common.PreviewSystem;
using RR.UI.FrameSystem;
using TMPro;
using UnityEngine;
using UnityEngine.Serialization;

namespace BerserkV3.Lobby.UI
{
	public partial class DeckValuePreviewView : RR.UI.FrameSystem.BaseView
	{
		public static BerserkV3.Lobby.UI.DeckValuePreviewView Instance { get; private set; }
		// Controls
#pragma warning disable 0414
		[Header("Controls (auto capture)")]
		[AutoGenerated, SerializeField] private TextMeshProUGUI Title;
		[AutoGenerated, SerializeField] private TextMeshProUGUI Description;
#pragma warning restore 0414

		protected override void AutoInit()
		{
			Instance = this;
		}

		protected override void AutoSubscribe()
		{
			SubscribeOnChanged(Title);
			SubscribeOnChanged(Description);
		}

		[VisibleInGraph(false)]
		public BerserkV3.Lobby.UI.DeckValuePreviewView Build()
		{
			OnBuildSafe(true);
			return this;
		}

		#region Static Methods

		public static void ShowInstance() => Instance.Show();
		public static void HideInstance() => Instance.Hide();
		public static void CloseInstance() => Instance.Close();

		#endregion
	}
}