using UnityEngine;
using RR.UI.FrameSystem;

namespace BerserkV3.Lobby.UI
{
	public partial class DeckValueView : RR.UI.FrameSystem.BaseView //Autogenerated
	{
		 public static BerserkV3.Lobby.UI.DeckValueView Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        [Header("Controls (auto capture)")]
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI DeckValueText = default;
        #pragma warning restore 0414
        
        protected override void AutoInit()
        {
            Instance = this;
        }
        
        protected override void AutoSubscribe()
        {
            SubscribeOnChanged(DeckValueText);
        }
        
        [VisibleInGraph(false)]
        public BerserkV3.Lobby.UI.DeckValueView Build()
        {
            OnBuildSafe(true);
            return this;
        }
        
        #region Static Methods
        public static void ShowInstance() => Instance.Show();
        public static void HideInstance() => Instance.Hide();
        public static void CloseInstance() => Instance.Close();
        #endregion
	}
}