/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using UnityEngine.UI;
using RR.UI;
using RR.UI.FrameSystem;

namespace BerserkV3.Lobby.UI
{
    public partial class DeckButtonView : RR.UI.FrameSystem.BaseView //Autogenerated
    {
        public static BerserkV3.Lobby.UI.DeckButtonView Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        [Header("Controls (auto capture)")]
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image OutlineImg = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image ButtonImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image MaskImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.RawImage VulcaniteImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image Image = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform Leagues = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.RawImage LeagueFlag = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.RawImage FactionFlag = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.RawImage CoatImage = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI NameText = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image CardsCountPanel = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI CardsCountText = default;
#pragma warning restore 0414
        
        protected override void AutoInit()
        {
            Instance = this;
        }
        
        protected override void AutoSubscribe()
        {
            SubscribeOnChanged(OutlineImg);
            SubscribeOnChanged(ButtonImage);
            SubscribeOnChanged(MaskImage);
            SubscribeOnChanged(VulcaniteImage);
            SubscribeOnChanged(Image);
            SubscribeOnChanged(Leagues);
            SubscribeOnChanged(LeagueFlag);
            SubscribeOnChanged(FactionFlag);
            SubscribeOnChanged(CoatImage);
            SubscribeOnChanged(NameText);
            SubscribeOnChanged(CardsCountPanel);
            SubscribeOnChanged(CardsCountText);
        }
        
        [VisibleInGraph(false)]
        public BerserkV3.Lobby.UI.DeckButtonView Build()
        {
            OnBuildSafe(true);
            return this;
        }
        #region Static Methods
        public static void ShowInstance() => Instance.Show();
        public static void HideInstance() => Instance.Hide();
        public static void CloseInstance() => Instance.Close();
        #endregion
    }
}