/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using UnityEngine.UI;
using RR.UI;
using RR.UI.FrameSystem;

namespace BerserkV3.Lobby.UI.Duels
{
    public partial class LobbyDuelView : BerserkV3.Startup.UI.SafeView //Autogenerated
    {
        public static LobbyDuelView Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        [Header("Controls (auto capture)")]
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform Content = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image ModalImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image LineImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image LineImg = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image LineImg1 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image Shadow = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform TitleImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image MaskImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BackgroundImageWhite = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI TitleText = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BorderImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image SearckBackground = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image SearchTextArea = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI SearchPlaceholder = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI SearchText = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform RoomsLayout = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.ScrollRect RoomsScroll = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image RoomsViewport = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform RoomsContainer = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Scrollbar Scrollbar = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform SlidingArea = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image Handle = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Button JoinRoomButton = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image MaskImage1 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BackgroundImageYellow = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BorderImage1 = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI OKText = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform AvatarLayout = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image AvatarMaskImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.RawImage AvatarImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.RawImage FrameImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform NameLayout = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image NameBackgroundImage = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI NameText = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform ButtonsLayout = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Button SelectDeckButton = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image MaskImage2 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BackgroundImageGreen = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BorderImage2 = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI OKText1 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Button PracticeButton = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image MaskImage3 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BackgroundImageGreen1 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BorderImage3 = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI OKText2 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Button CreateButton = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image MaskImage4 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BackgroundImageYellow1 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BorderImage4 = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI OKText3 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Button BackButton = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image MaskImage5 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BackgroundImageWhite1 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BorderImage5 = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI OKText4 = default;
        #pragma warning restore 0414
        
        protected override void AutoInit()
        {
            Instance = this;
        }
        
        protected override void AutoSubscribe()
        {
            SubscribeOnChanged(Content);
            SubscribeOnChanged(ModalImage);
            SubscribeOnChanged(LineImage);
            SubscribeOnChanged(LineImg);
            SubscribeOnChanged(LineImg1);
            SubscribeOnChanged(Shadow);
            SubscribeOnChanged(TitleImage);
            SubscribeOnChanged(MaskImage);
            SubscribeOnChanged(BackgroundImageWhite);
            SubscribeOnChanged(TitleText);
            SubscribeOnChanged(BorderImage);
            SubscribeOnChanged(SearckBackground);
            SubscribeOnChanged(SearchTextArea);
            SubscribeOnChanged(SearchPlaceholder);
            SubscribeOnChanged(SearchText);
            SubscribeOnChanged(RoomsLayout);
            SubscribeOnChanged(RoomsScroll);
            SubscribeOnChanged(RoomsViewport);
            SubscribeOnChanged(RoomsContainer);
            SubscribeOnChanged(Scrollbar);
            SubscribeOnChanged(SlidingArea);
            SubscribeOnChanged(Handle);
            SubscribeOnChanged(JoinRoomButton);
            SubscribeOnChanged(MaskImage1);
            SubscribeOnChanged(BackgroundImageYellow);
            SubscribeOnChanged(BorderImage1);
            SubscribeOnChanged(OKText);
            SubscribeOnChanged(AvatarLayout);
            SubscribeOnChanged(AvatarMaskImage);
            SubscribeOnChanged(AvatarImage);
            SubscribeOnChanged(FrameImage);
            SubscribeOnChanged(NameLayout);
            SubscribeOnChanged(NameBackgroundImage);
            SubscribeOnChanged(NameText);
            SubscribeOnChanged(ButtonsLayout);
            SubscribeOnChanged(SelectDeckButton);
            SubscribeOnChanged(MaskImage2);
            SubscribeOnChanged(BackgroundImageGreen);
            SubscribeOnChanged(BorderImage2);
            SubscribeOnChanged(OKText1);
            SubscribeOnChanged(PracticeButton);
            SubscribeOnChanged(MaskImage3);
            SubscribeOnChanged(BackgroundImageGreen1);
            SubscribeOnChanged(BorderImage3);
            SubscribeOnChanged(OKText2);
            SubscribeOnChanged(CreateButton);
            SubscribeOnChanged(MaskImage4);
            SubscribeOnChanged(BackgroundImageYellow1);
            SubscribeOnChanged(BorderImage4);
            SubscribeOnChanged(OKText3);
            SubscribeOnChanged(BackButton);
            SubscribeOnChanged(MaskImage5);
            SubscribeOnChanged(BackgroundImageWhite1);
            SubscribeOnChanged(BorderImage5);
            SubscribeOnChanged(OKText4);
        }
        
        [VisibleInGraph(false)]
        public LobbyDuelView Build()
        {
            OnBuildSafe(true);
            return this;
        }
        #region Static Methods
        public static void ShowInstance() => Instance.Show();
        public static void HideInstance() => Instance.Hide();
        public static void CloseInstance() => Instance.Close();
        #endregion
    }
}