/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////

using RR.UI.FrameSystem;
using UnityEngine;

namespace BerserkV3.Lobby.UI.Leagues
{
    public partial class LobbyLeagueInfoView : RR.UI.FrameSystem.BaseView //Autogenerated
    {
        public static Leagues.LobbyLeagueInfoView Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        [Header("Controls (auto capture)")]
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image Container = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform TitleLayout = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform TitleImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image MaskImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BackgroundImageWhite = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI TitleText = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BorderImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.ScrollRect ScrollView = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image Viewport = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform Content = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI TitleInfoText = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI ContentText = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Scrollbar ScrollbarVertical = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform SlidingArea = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image Handle = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform ButtonsPnl = default;
        [AutoGenerated, SerializeField] protected global::UI.ButtonView OkBtn = default;
        #pragma warning restore 0414
        
        protected override void AutoInit()
        {
            Instance = this;
        }
        
        protected override void AutoSubscribe()
        {
            SubscribeOnChanged(Container);
            SubscribeOnChanged(TitleLayout);
            SubscribeOnChanged(TitleImage);
            SubscribeOnChanged(MaskImage);
            SubscribeOnChanged(BackgroundImageWhite);
            SubscribeOnChanged(TitleText);
            SubscribeOnChanged(BorderImage);
            SubscribeOnChanged(ScrollView);
            SubscribeOnChanged(Viewport);
            SubscribeOnChanged(Content);
            SubscribeOnChanged(TitleInfoText);
            SubscribeOnChanged(ContentText);
            SubscribeOnChanged(ScrollbarVertical);
            SubscribeOnChanged(SlidingArea);
            SubscribeOnChanged(Handle);
            SubscribeOnChanged(ButtonsPnl);
            SubscribeOnChanged(OkBtn);
        }
        
        [VisibleInGraph(false)]
        public Leagues.LobbyLeagueInfoView Build()
        {
            OnBuildSafe(true);
            return this;
        }
        #region Static Methods
        public static void ShowInstance() => Instance.Show();
        public static void HideInstance() => Instance.Hide();
        public static void CloseInstance() => Instance.Close();
        #endregion
    }
}