/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using UnityEngine.UI;
using RR.UI;
using RR.UI.FrameSystem;

namespace BerserkV3.GameCore.UI
{
    public partial class OverchargeView : RR.UI.FrameSystem.BaseView //Autogenerated
    {
        public static OverchargeView Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        [Header("Controls (auto capture)")]
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform Container = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image Backgound = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform CountChoseElement = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Button DecreaseValueButton = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image Count = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI SelectedCount = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI HeaderText = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Button IncreaseValueButton = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform ButtonsPnl1 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Button BackBtn = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image MaskImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BackgroundImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BorderImage = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI BackText = default;
        #pragma warning restore 0414
        
        protected override void AutoInit()
        {
            Instance = this;
        }
        
        protected override void AutoSubscribe()
        {
            SubscribeOnChanged(Container);
            SubscribeOnChanged(Backgound);
            SubscribeOnChanged(CountChoseElement);
            SubscribeOnChanged(DecreaseValueButton);
            SubscribeOnChanged(Count);
            SubscribeOnChanged(SelectedCount);
            SubscribeOnChanged(IncreaseValueButton);
            SubscribeOnChanged(ButtonsPnl1);
            SubscribeOnChanged(BackBtn);
            SubscribeOnChanged(MaskImage);
            SubscribeOnChanged(BackgroundImage);
            SubscribeOnChanged(BorderImage);
            SubscribeOnChanged(BackText);
            SubscribeOnChanged(HeaderText);
        }
        
        [VisibleInGraph(false)]
        public OverchargeView Build()
        {
            OnBuildSafe(true);
            return this;
        }
        #region Static Methods
        public static void ShowInstance() => Instance.Show();
        public static void HideInstance() => Instance.Hide();
        public static void CloseInstance() => Instance.Close();
        #endregion
    }
}