/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using UnityEngine.UI;
using RR.UI;
using RR.UI.FrameSystem;

namespace RR.UI.Predefined
{
    public partial class RRFrame : BaseView //Autogenerated
    {
        /// <summary>Static instance of the view</summary>
        public static RRFrame Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        [Header("Controls (auto capture)")]
        [AutoGenerated, SerializeField] UnityEngine.UI.Image Title = default;
        [AutoGenerated, SerializeField] TMPro.TextMeshProUGUI TitleTxt = default;
        [AutoGenerated, SerializeField] UnityEngine.RectTransform TMPSubMeshUILiberationSansSDFMaterialLiberationSansSDFAtlas = default;
        [AutoGenerated, SerializeField] UnityEngine.RectTransform TitleBorder = default;
        [AutoGenerated, SerializeField] UnityEngine.RectTransform Body = default;
        [AutoGenerated, SerializeField] UnityEngine.RectTransform OuterBorder = default;
        #pragma warning restore 0414
        
        protected override void AutoInit()
        {
            Instance = this;
        }
        
        protected override void AutoSubscribe()
        {
            SubscribeOnChanged(Title);
            SubscribeOnChanged(TitleTxt);
            SubscribeOnChanged(TMPSubMeshUILiberationSansSDFMaterialLiberationSansSDFAtlas);
            SubscribeOnChanged(TitleBorder);
            SubscribeOnChanged(Body);
            SubscribeOnChanged(OuterBorder);
        }
        
        [VisibleInGraph(false)]
        public RRFrame Build()
        {
            OnBuildSafe(true);
            return this;
        }
    }
}