/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using UnityEngine.UI;
using RR.UI;
using RR.UI.FrameSystem;

namespace RR.UI.Predefined
{
    public partial class RRPopup : BaseView //Autogenerated
    {
        /// <summary>Static instance of the view</summary>
        public static RRPopup Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        [Header("Controls (auto capture)")]
        [AutoGenerated, SerializeField] UnityEngine.UI.Image frameBg = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.Image Title = default;
        [AutoGenerated, SerializeField] TMPro.TextMeshProUGUI TitleTxt = default;
        [AutoGenerated, SerializeField] UnityEngine.RectTransform TMPSubMeshUILiberationSansSDFMaterialLiberationSansSDFAtlas = default;
        [AutoGenerated, SerializeField] UnityEngine.RectTransform Border = default;
        [AutoGenerated, SerializeField] UnityEngine.RectTransform Body = default;
        [AutoGenerated, SerializeField] TMPro.TextMeshProUGUI ContentTxt = default;
        [AutoGenerated, SerializeField] UnityEngine.RectTransform TMPSubMeshUILiberationSansSDFMaterialLiberationSansSDFAtlas1 = default;
        [AutoGenerated, SerializeField] UnityEngine.RectTransform Footer = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.Button CancelBtn = default;
        [AutoGenerated, SerializeField] TMPro.TextMeshProUGUI RRText = default;
        [AutoGenerated, SerializeField] UnityEngine.RectTransform TMPSubMeshUILiberationSansSDFMaterialLiberationSansSDFAtlas2 = default;
        [AutoGenerated, SerializeField] UnityEngine.RectTransform Border1 = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.Button OkBtn = default;
        [AutoGenerated, SerializeField] TMPro.TextMeshProUGUI RRText1 = default;
        [AutoGenerated, SerializeField] UnityEngine.RectTransform TMPSubMeshUILiberationSansSDFMaterialLiberationSansSDFAtlas3 = default;
        [AutoGenerated, SerializeField] UnityEngine.RectTransform Border2 = default;
        [AutoGenerated, SerializeField] UnityEngine.RectTransform FooterBorder = default;
        [AutoGenerated, SerializeField] UnityEngine.RectTransform Border3 = default;
        #pragma warning restore 0414
        
        protected override void AutoInit()
        {
            Instance = this;
        }
        
        protected override void AutoSubscribe()
        {
            SubscribeOnChanged(frameBg);
            SubscribeOnChanged(Title);
            SubscribeOnChanged(TitleTxt);
            SubscribeOnChanged(TMPSubMeshUILiberationSansSDFMaterialLiberationSansSDFAtlas);
            SubscribeOnChanged(Border);
            SubscribeOnChanged(Body);
            SubscribeOnChanged(ContentTxt);
            SubscribeOnChanged(TMPSubMeshUILiberationSansSDFMaterialLiberationSansSDFAtlas1);
            SubscribeOnChanged(Footer);
            SubscribeOnChanged(CancelBtn);
            SubscribeOnChanged(RRText);
            SubscribeOnChanged(TMPSubMeshUILiberationSansSDFMaterialLiberationSansSDFAtlas2);
            SubscribeOnChanged(Border1);
            SubscribeOnChanged(OkBtn);
            SubscribeOnChanged(RRText1);
            SubscribeOnChanged(TMPSubMeshUILiberationSansSDFMaterialLiberationSansSDFAtlas3);
            SubscribeOnChanged(Border2);
            SubscribeOnChanged(FooterBorder);
            SubscribeOnChanged(Border3);
        }
        
        [VisibleInGraph(false)]
        public void Build()
        {
            OnBuildSafe(true);
        }
    }
}