/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using UnityEngine.UI;
using RR.UI;
using RR.UI.FrameSystem;

namespace UI
{
    public partial class BackgroundView : RR.UI.FrameSystem.BaseView //Autogenerated
    {
        public static BackgroundView Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        [Header("Controls (auto capture)")]
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BackgroundImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image TableBase = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image Plane = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BottomRightCorner = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BottomLeftCorner = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image TableBorders = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image TopLeftCorner = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image TopRightCorner = default;
        #pragma warning restore 0414
        
        protected override void AutoInit()
        {
            Instance = this;
        }
        
        protected override void AutoSubscribe()
        {
            SubscribeOnChanged(BackgroundImage);
            SubscribeOnChanged(TableBase);
            SubscribeOnChanged(Plane);
            SubscribeOnChanged(BottomRightCorner);
            SubscribeOnChanged(BottomLeftCorner);
            SubscribeOnChanged(TableBorders);
            SubscribeOnChanged(TopLeftCorner);
            SubscribeOnChanged(TopRightCorner);
        }
        
        [VisibleInGraph(false)]
        public BackgroundView Build()
        {
            OnBuildSafe(true);
            return this;
        }
        #region Static Methods
        public static void ShowInstance() => Instance.Show();
        public static void HideInstance() => Instance.Hide();
        public static void CloseInstance() => Instance.Close();
        #endregion
    }
}