/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using UnityEngine.UI;
using RR.UI;
using RR.UI.FrameSystem;

namespace UI
{
    public partial class ButtonView : RR.UI.FrameSystem.BaseView //Autogenerated
    {
        /// <summary>Static instance of the view</summary>
        public static ButtonView Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        [Header("Controls (auto capture)")]
        [AutoGenerated, SerializeField] UnityEngine.UI.Image MaskImage = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.Image BackgroundImage = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.Image BorderImage = default;
        [AutoGenerated, SerializeField] TMPro.TextMeshProUGUI OKText = default;
        #pragma warning restore 0414
        
        protected override void AutoInit()
        {
            Instance = this;
        }
        
        protected override void AutoSubscribe()
        {
            SubscribeOnChanged(MaskImage);
            SubscribeOnChanged(BackgroundImage);
            SubscribeOnChanged(BorderImage);
            SubscribeOnChanged(OKText);
        }
        
        [VisibleInGraph(false)]
        public ButtonView Build()
        {
            OnBuildSafe(true);
            return this;
        }
    }
}