/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using UnityEngine.UI;
using RR.UI;
using RR.UI.FrameSystem;

namespace UI
{
    public partial class CardTooltipPanel : RR.UI.FrameSystem.BaseView //Autogenerated
    {
        /// <summary>Static instance of the view</summary>
        public static CardTooltipPanel Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        [Header("Controls (auto capture)")]
        [AutoGenerated, SerializeField] UnityEngine.RectTransform DescriptionPanel = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.Image BackArt = default;
        [AutoGenerated, SerializeField] TMPro.TextMeshProUGUI TitleTxt = default;
        [AutoGenerated, SerializeField] TMPro.TextMeshProUGUI TooltipTxt = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.Image Border = default;
        #pragma warning restore 0414
        
        protected override void AutoInit()
        {
            Instance = this;
        }
        
        protected override void AutoSubscribe()
        {
            SubscribeOnChanged(DescriptionPanel);
            SubscribeOnChanged(BackArt);
            SubscribeOnChanged(TitleTxt);
            SubscribeOnChanged(TooltipTxt);
            SubscribeOnChanged(Border);
        }
        
        [VisibleInGraph(false)]
        public CardTooltipPanel Build()
        {
            OnBuildSafe(true);
            return this;
        }
    }
}