/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////

using UnityEngine;
using RR.UI.FrameSystem;

namespace UI
{
	public partial class ConfirmationDialog : RR.UI.FrameSystem.BaseView //Autogenerated
	{
		/// <summary>Static instance of the view</summary>
		public static ConfirmationDialog Instance { get; private set; }
		// Controls
#pragma warning disable 0414
		[Header("Controls (auto capture)")]
		[AutoGenerated, SerializeField] TMPro.TextMeshProUGUI TitleText = default;
		[AutoGenerated, SerializeField] TMPro.TextMeshProUGUI BodyMessageTxt = default;
		[AutoGenerated, SerializeField] UnityEngine.UI.Button CancelBtn = default;
		[AutoGenerated, SerializeField] TMPro.TextMeshProUGUI CancelTxt = default;
		[AutoGenerated, SerializeField] UnityEngine.UI.Button OkBtn = default;
		[AutoGenerated, SerializeField] TMPro.TextMeshProUGUI OkTxt = default;
		[AutoGenerated, SerializeField] UnityEngine.UI.Button CloseBtn = default;
		[AutoGenerated, SerializeField] TMPro.TextMeshProUGUI CloseTxt = default;
#pragma warning restore 0414

		protected override void AutoInit()
		{
			Instance = this;
		}

		protected override void AutoSubscribe()
		{
			SubscribeOnChanged(TitleText);
			SubscribeOnChanged(BodyMessageTxt);
			SubscribeOnChanged(CancelBtn);
			SubscribeOnChanged(CancelTxt);
			SubscribeOnChanged(OkBtn);
			SubscribeOnChanged(OkTxt);
			SubscribeOnChanged(CloseBtn);
			SubscribeOnChanged(CloseTxt);
		}
	}
}