/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////
using UnityEngine;
using UnityEngine.UI;
using RR.UI.FrameSystem;

namespace UI
{
    public partial class CurrentDeckPanel : RR.UI.FrameSystem.BaseView //Autogenerated
    {
        public static CurrentDeckPanel Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        [Header("Controls (auto capture)")]
        [AutoGenerated, SerializeField] protected UnityEngine.UI.RawImage VulcaniteImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Button ProfilePictureButton = default;
        [AutoGenerated, SerializeField] protected UI.HistogramView HistogramView = default;
        [AutoGenerated, SerializeField] protected BerserkV3.Lobby.UI.DeckValueView DeckValueView = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI CardsCountText = default;
        [AutoGenerated, SerializeField] protected LoopVerticalScrollRect LoopVerticalScrollRect = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI InfoText = default;
        #pragma warning restore 0414
        
        protected override void AutoInit()
        {
            Instance = this;
        }
        
        protected override void AutoSubscribe()
        {
            SubscribeOnChanged(VulcaniteImage);
            SubscribeOnChanged(ProfilePictureButton);
            SubscribeOnChanged(HistogramView);
            SubscribeOnChanged(DeckValueView);
            SubscribeOnChanged(CardsCountText);
            SubscribeOnChanged(LoopVerticalScrollRect);
            SubscribeOnChanged(InfoText);
        }
        
        [VisibleInGraph(false)]
        public CurrentDeckPanel Build()
        {
            OnBuildSafe(true);
            return this;
        }
        #region Static Methods
        public static void ShowInstance() => Instance.Show();
        public static void HideInstance() => Instance.Hide();
        public static void CloseInstance() => Instance.Close();
        #endregion
    }
}