/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using UnityEngine.UI;
using RR.UI;
using RR.UI.FrameSystem;

namespace UI
{
    public partial class CustomizationItemView : RR.UI.FrameSystem.BaseView //Autogenerated
    {
        public static CustomizationItemView Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        [Header("Controls (auto capture)")]
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image ItemHighlight = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image AdditionalImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image ItemImage = default;
        #pragma warning restore 0414
        
        protected override void AutoInit()
        {
            Instance = this;
        }
        
        protected override void AutoSubscribe()
        {
            SubscribeOnChanged(ItemHighlight);
            SubscribeOnChanged(AdditionalImage);
            SubscribeOnChanged(ItemImage);
        }
        
        [VisibleInGraph(false)]
        public CustomizationItemView Build()
        {
            OnBuildSafe(true);
            return this;
        }
        #region Static Methods
        public static void ShowInstance() => Instance.Show();
        public static void HideInstance() => Instance.Hide();
        public static void CloseInstance() => Instance.Close();
        #endregion
    }
}