/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using BerserkV3.Common.UIKit;
using UnityEngine.UI;
using RR.UI;
using RR.UI.FrameSystem;

namespace UI
{
    public partial class DeckSelectVulcaniteDialog : Global.View //Autogenerated
    {
        public static DeckSelectVulcaniteDialog Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        [Header("Controls (auto capture)")]
        [AutoGenerated, SerializeField] protected UnityEngine.UI.RawImage CoatImg = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI LandName = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.RawImage PlayerImage = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI NameTxt = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI NameDescription = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform DescriptionContainer = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI EffectTxt = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI LevelTxt = default;
        [AutoGenerated, SerializeField] protected UI.ButtonView BackButton = default;
        [AutoGenerated, SerializeField] protected UI.ButtonView OKButton1 = default;
        [AutoGenerated, SerializeField] protected HexagoneItemView HexagoneItemView = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Button Boreas = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Button Arcadia = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Button Notus = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Button Hades = default;
        #pragma warning restore 0414
        
        protected override void AutoInit()
        {
            Instance = this;
        }
        
        protected override void AutoSubscribe()
        {
	        SubscribeOnChanged(CoatImg);
	        SubscribeOnChanged(LandName);
	        SubscribeOnChanged(PlayerImage);
	        SubscribeOnChanged(NameTxt);
	        SubscribeOnChanged(NameDescription);
	        SubscribeOnChanged(DescriptionContainer);
	        SubscribeOnChanged(EffectTxt);
	        SubscribeOnChanged(LevelTxt);
	        SubscribeOnChanged(BackButton);
	        SubscribeOnChanged(OKButton1);
	        SubscribeOnChanged(HexagoneItemView);
	        SubscribeOnChanged(Boreas);
	        SubscribeOnChanged(Arcadia);
	        SubscribeOnChanged(Notus);
	        SubscribeOnChanged(Hades);
        }
        
        [VisibleInGraph(false)]
        public DeckSelectVulcaniteDialog Build()
        {
            OnBuildSafe(true);
            return this;
        }
        #region Static Methods
        public static void ShowInstance() => Instance.Show();
        public static void HideInstance() => Instance.Hide();
        public static void CloseInstance() => Instance.Close();
        #endregion
    }
}