/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using UnityEngine.UI;
using RR.UI;
using RR.UI.FrameSystem;

namespace UI
{
    public partial class DeckCardsView : RR.UI.FrameSystem.BaseView //Autogenerated
    {
        public static DeckCardsView Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        [Header("Controls (auto capture)")]
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image ContentMask = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image VerticalLine = default;
        [AutoGenerated, SerializeField] protected SearchCardsView SearchInput = default;
        [AutoGenerated, SerializeField] protected UI.CurrentDeckPanel DeckCardListPanel = default;
        [AutoGenerated, SerializeField] protected UI.AllCardsCopyPanel AllCardsCopyPanel = default;
        [AutoGenerated, SerializeField] protected UI.ButtonView BackButton = default;
        [AutoGenerated, SerializeField] protected UI.ButtonView SaveButton = default;
        [AutoGenerated, SerializeField] protected RR.UI.Custom.RRButton BuyCardsButton = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI Text = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image Underline = default;
        [AutoGenerated, SerializeField] protected UI.ButtonView SortButton = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform TitleImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image MaskImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BackgroundImageWhite = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI TitleText = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BorderImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.CanvasGroup FullCardView = default;
        [AutoGenerated, SerializeField] protected UI.HandCardView PlayerHandCard = default;
        #pragma warning restore 0414
        
        protected override void AutoInit()
        {
            Instance = this;
        }
        
        protected override void AutoSubscribe()
        {
            SubscribeOnChanged(ContentMask);
            SubscribeOnChanged(VerticalLine);
            SubscribeOnChanged(SearchInput);
            SubscribeOnChanged(DeckCardListPanel);
            SubscribeOnChanged(AllCardsCopyPanel);
            SubscribeOnChanged(BackButton);
            SubscribeOnChanged(SaveButton);
            SubscribeOnChanged(BuyCardsButton);
            SubscribeOnChanged(Text);
            SubscribeOnChanged(Underline);
            SubscribeOnChanged(SortButton);
            SubscribeOnChanged(TitleImage);
            SubscribeOnChanged(MaskImage);
            SubscribeOnChanged(BackgroundImageWhite);
            SubscribeOnChanged(TitleText);
            SubscribeOnChanged(BorderImage);
            SubscribeOnChanged(FullCardView);
            SubscribeOnChanged(PlayerHandCard);
        }
        
        [VisibleInGraph(false)]
        public DeckCardsView Build()
        {
            OnBuildSafe(true);
            return this;
        }
        #region Static Methods
        public static void ShowInstance() => Instance.Show();
        public static void HideInstance() => Instance.Hide();
        public static void CloseInstance() => Instance.Close();
        #endregion
    }
}