/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using UnityEngine.UI;
using RR.UI;
using RR.UI.FrameSystem;

namespace UI
{
    public partial class DeckPanelItemView : UI.DeckItemView //Autogenerated
    {
        /// <summary>Static instance of the view</summary>
        public static DeckPanelItemView Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        [Header("Controls (auto capture)")]
        [AutoGenerated, SerializeField] UnityEngine.UI.Image BlackImage = default;
        [AutoGenerated, SerializeField] TMPro.TextMeshProUGUI DeckNameText = default;
        [AutoGenerated, SerializeField] TMPro.TextMeshProUGUI CounterText = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.Image BorderImage = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.RawImage LavaImage = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.Image OutlineImg = default;
        [AutoGenerated, SerializeField] TMPro.TextMeshProUGUI LavaTxt = default;
        #pragma warning restore 0414
        
        protected override void AutoInit()
        {
            Instance = this;
        }
        
        protected override void AutoSubscribe()
        {
            SubscribeOnChanged(BlackImage);
            SubscribeOnChanged(DeckNameText);
            SubscribeOnChanged(CounterText);
            SubscribeOnChanged(BorderImage);
            SubscribeOnChanged(LavaImage);
            SubscribeOnChanged(OutlineImg);
            SubscribeOnChanged(LavaTxt);
        }
        
        [VisibleInGraph(false)]
        public DeckPanelItemView Build()
        {
            OnBuildSafe(true);
            return this;
        }
    }
}