/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using UnityEngine.UI;
using RR.UI;
using RR.UI.FrameSystem;

namespace UI
{
    public partial class ErrorDialog : RR.UI.FrameSystem.BaseView //Autogenerated
    {
        public static ErrorDialog Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        [Header("Controls (auto capture)")]
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform TitleImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image MaskImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BackgroundImageWhite = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI TitleText = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BorderImage = default;
        [AutoGenerated, SerializeField] protected UI.ButtonView CopyButton = default;
        [AutoGenerated, SerializeField] protected UI.ButtonView OKButton = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.ScrollRect ScrollView = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image Viewport = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI ErrorText = default;
        #pragma warning restore 0414
        
        protected override void AutoInit()
        {
            Instance = this;
        }
        
        protected override void AutoSubscribe()
        {
            SubscribeOnChanged(TitleImage);
            SubscribeOnChanged(MaskImage);
            SubscribeOnChanged(BackgroundImageWhite);
            SubscribeOnChanged(TitleText);
            SubscribeOnChanged(BorderImage);
            SubscribeOnChanged(CopyButton);
            SubscribeOnChanged(OKButton);
            SubscribeOnChanged(ScrollView);
            SubscribeOnChanged(Viewport);
            SubscribeOnChanged(ErrorText);
        }
        
        [VisibleInGraph(false)]
        public ErrorDialog Build()
        {
            OnBuildSafe(true);
            return this;
        }
        #region Static Methods
        public static void ShowInstance() => Instance.Show();
        public static void HideInstance() => Instance.Hide();
        public static void CloseInstance() => Instance.Close();
        #endregion
    }
}