/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using UnityEngine.UI;
using RR.UI;
using RR.UI.FrameSystem;

namespace UI
{
    public partial class GameTableView : RR.UI.FrameSystem.BaseView //Autogenerated
    {
        public static GameTableView Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        [Header("Controls (auto capture)")]
        [AutoGenerated, SerializeField] protected UI.ActorView Actor_Self = default;
        [AutoGenerated, SerializeField] protected UI.ActorView Actor_Opponent = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform PlayerHandCardPanel = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform OpponentHandCardPanel = default;
        [AutoGenerated, SerializeField] protected UnityEngine.CanvasGroup YourTurnPanelOverlay = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image YourTurnBgImg = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform IndicatorsPool = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Button SettingsBtn = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI VersionTxt = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI CommendLevel = default;
        #pragma warning restore 0414
        
        protected override void AutoInit()
        {
            Instance = this;
        }
        
        protected override void AutoSubscribe()
        {
            SubscribeOnChanged(Actor_Self);
            SubscribeOnChanged(Actor_Opponent);
            SubscribeOnChanged(PlayerHandCardPanel);
            SubscribeOnChanged(OpponentHandCardPanel);
            SubscribeOnChanged(YourTurnPanelOverlay);
            SubscribeOnChanged(YourTurnBgImg);
            SubscribeOnChanged(IndicatorsPool);
            SubscribeOnChanged(SettingsBtn);
            SubscribeOnChanged(VersionTxt);
            SubscribeOnChanged(CommendLevel);
        }
        
        [VisibleInGraph(false)]
        public GameTableView Build()
        {
            OnBuildSafe(true);
            return this;
        }
        #region Static Methods
        public static void ShowInstance() => Instance.Show();
        public static void HideInstance() => Instance.Hide();
        public static void CloseInstance() => Instance.Close();
        #endregion
    }
}