/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using UnityEngine.UI;
using RR.UI;
using RR.UI.FrameSystem;

namespace UI
{
    public partial class GraveyardView : RR.UI.FrameSystem.BaseView //Autogenerated
    {
        public static GraveyardView Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        [Header("Controls (auto capture)")]
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform CardsGrid = default;
        [AutoGenerated, SerializeField] protected UI.HandCardView HandCardView = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Button CloseBtn = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image MaskImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BackgroundImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BorderImage = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI OKText = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI TitleTxt = default;
        #pragma warning restore 0414
        
        protected override void AutoInit()
        {
            Instance = this;
        }
        
        protected override void AutoSubscribe()
        {
            SubscribeOnChanged(CardsGrid);
            SubscribeOnChanged(HandCardView);
            SubscribeOnChanged(CloseBtn);
            SubscribeOnChanged(MaskImage);
            SubscribeOnChanged(BackgroundImage);
            SubscribeOnChanged(BorderImage);
            SubscribeOnChanged(OKText);
            SubscribeOnChanged(TitleTxt);
        }
        
        [VisibleInGraph(false)]
        public GraveyardView Build()
        {
            OnBuildSafe(true);
            return this;
        }
        #region Static Methods
        public static void ShowInstance() => Instance.Show();
        public static void HideInstance() => Instance.Hide();
        public static void CloseInstance() => Instance.Close();
        #endregion
    }
}