/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////

using UnityEngine;
using RR.UI.FrameSystem;

namespace UI
{
	public partial class HorizontalStatisticView : BaseStatisticView //Autogenerated
	{
		public static HorizontalStatisticView Instance { get; private set; }
		// Controls
	#pragma warning disable 0414
		[Header("Controls (auto capture)")]
		[AutoGenerated, SerializeField] protected UnityEngine.UI.Image WholeBackground = default;

		[AutoGenerated, SerializeField] protected UnityEngine.RectTransform ImageLayout = default;
		[AutoGenerated, SerializeField] protected UnityEngine.UI.RawImage Mask = default;
		[AutoGenerated, SerializeField] protected UnityEngine.UI.RawImage Image = default;
		[AutoGenerated, SerializeField] protected UnityEngine.RectTransform TextLayout = default;
		[AutoGenerated, SerializeField] protected UnityEngine.UI.Image TextBackground = default;
		[AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI TextKey = default;
		[AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI TextValue = default;
	#pragma warning restore 0414

		protected override void AutoInit()
		{
			Instance = this;
		}

		protected override void AutoSubscribe()
		{
			SubscribeOnChanged(WholeBackground);
			SubscribeOnChanged(ImageLayout);
			SubscribeOnChanged(Mask);
			SubscribeOnChanged(Image);
			SubscribeOnChanged(TextLayout);
			SubscribeOnChanged(TextBackground);
			SubscribeOnChanged(TextKey);
			SubscribeOnChanged(TextValue);
		}

		[VisibleInGraph(false)]
		public HorizontalStatisticView Build()
		{
			OnBuildSafe(true);
			return this;
		}

	#region Static Methods

		public static void ShowInstance() => Instance.Show();
		public static void HideInstance() => Instance.Hide();
		public static void CloseInstance() => Instance.Close();

	#endregion
	}
}