/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using UnityEngine.UI;
using RR.UI;
using RR.UI.FrameSystem;

namespace UI
{
    public partial class LavaShopView : RR.UI.FrameSystem.BaseView //Autogenerated
    {
        public static LavaShopView Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        [Header("Controls (auto capture)")]
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image Background = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI LavaTxt = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI LavaValueTxt = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image SelectedHeroPanel = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform LandContainer = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.RawImage CoatImg = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI LandName = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform AvatarPanel = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image HexMask = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.RawImage PlayerImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Button ProfilePictureButton = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI NameTxt = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image LevelImg = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI LevelTxt = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform DescriptionContainer = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI LableTxt = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI EffectTxt = default;
        [AutoGenerated, SerializeField] protected UI.ButtonView BackButton = default;
        [AutoGenerated, SerializeField] protected RR.UI.Custom.RRButton BuyButton = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image MaskImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BackgroundImageRed = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BorderImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform TextContainer = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI BuyText = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI PriceText = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI LavaText = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image HeroListPanel = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform VulcanitesContent = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image TopContent = default;
        [AutoGenerated, SerializeField] protected Lobby.Items.PictureButton VulcanitePanel = default;
        [AutoGenerated, SerializeField] protected Lobby.Items.PictureButton VulcanitePanel1 = default;
        [AutoGenerated, SerializeField] protected Lobby.Items.PictureButton VulcanitePanel2 = default;
        [AutoGenerated, SerializeField] protected Lobby.Items.PictureButton VulcanitePanel3 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BottomContent = default;
        [AutoGenerated, SerializeField] protected Lobby.Items.PictureButton VulcanitePanel4 = default;
        [AutoGenerated, SerializeField] protected Lobby.Items.PictureButton VulcanitePanel11 = default;
        [AutoGenerated, SerializeField] protected Lobby.Items.PictureButton VulcanitePanel21 = default;
        [AutoGenerated, SerializeField] protected Lobby.Items.PictureButton VulcanitePanel31 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image LineVertical = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image LineHorizontal = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image Shadow = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform TitleImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image MaskImage1 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BackgroundImageWhite = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI TitleText = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BorderImage1 = default;
        #pragma warning restore 0414
        
        protected override void AutoInit()
        {
            Instance = this;
        }
        
        protected override void AutoSubscribe()
        {
            SubscribeOnChanged(Background);
            SubscribeOnChanged(LavaTxt);
            SubscribeOnChanged(LavaValueTxt);
            SubscribeOnChanged(SelectedHeroPanel);
            SubscribeOnChanged(LandContainer);
            SubscribeOnChanged(CoatImg);
            SubscribeOnChanged(LandName);
            SubscribeOnChanged(AvatarPanel);
            SubscribeOnChanged(HexMask);
            SubscribeOnChanged(PlayerImage);
            SubscribeOnChanged(ProfilePictureButton);
            SubscribeOnChanged(NameTxt);
            SubscribeOnChanged(LevelImg);
            SubscribeOnChanged(LevelTxt);
            SubscribeOnChanged(DescriptionContainer);
            SubscribeOnChanged(LableTxt);
            SubscribeOnChanged(EffectTxt);
            SubscribeOnChanged(BackButton);
            SubscribeOnChanged(BuyButton);
            SubscribeOnChanged(MaskImage);
            SubscribeOnChanged(BackgroundImageRed);
            SubscribeOnChanged(BorderImage);
            SubscribeOnChanged(TextContainer);
            SubscribeOnChanged(BuyText);
            SubscribeOnChanged(PriceText);
            SubscribeOnChanged(LavaText);
            SubscribeOnChanged(HeroListPanel);
            SubscribeOnChanged(VulcanitesContent);
            SubscribeOnChanged(TopContent);
            SubscribeOnChanged(VulcanitePanel);
            SubscribeOnChanged(VulcanitePanel1);
            SubscribeOnChanged(VulcanitePanel2);
            SubscribeOnChanged(VulcanitePanel3);
            SubscribeOnChanged(BottomContent);
            SubscribeOnChanged(VulcanitePanel4);
            SubscribeOnChanged(VulcanitePanel11);
            SubscribeOnChanged(VulcanitePanel21);
            SubscribeOnChanged(VulcanitePanel31);
            SubscribeOnChanged(LineVertical);
            SubscribeOnChanged(LineHorizontal);
            SubscribeOnChanged(Shadow);
            SubscribeOnChanged(TitleImage);
            SubscribeOnChanged(MaskImage1);
            SubscribeOnChanged(BackgroundImageWhite);
            SubscribeOnChanged(TitleText);
            SubscribeOnChanged(BorderImage1);
        }
        
        [VisibleInGraph(false)]
        public LavaShopView Build()
        {
            OnBuildSafe(true);
            return this;
        }
        #region Static Methods
        public static void ShowInstance() => Instance.Show();
        public static void HideInstance() => Instance.Hide();
        public static void CloseInstance() => Instance.Close();
        #endregion
    }
}