/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using UnityEngine.UI;
using RR.UI;
using RR.UI.FrameSystem;

namespace UI
{
    public partial class MenuView : RR.UI.FrameSystem.BaseView //Autogenerated
    {
        public static MenuView Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        [Header("Controls (auto capture)")]
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image FadeImg = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image LogoImg = default;
        [AutoGenerated, SerializeField] protected UnityEngine.CanvasGroup ButtonsPnl = default;
        [AutoGenerated, SerializeField] protected UI.ButtonView PlayBtn = default;
        [AutoGenerated, SerializeField] protected UI.ButtonView DuelsBtn = default;
        [AutoGenerated, SerializeField] protected UI.ButtonView DeckBtn = default;
        [AutoGenerated, SerializeField] protected UI.ButtonView LavaShopBtn = default;
        [AutoGenerated, SerializeField] protected UI.ButtonView ProfileBtn = default;
        [AutoGenerated, SerializeField] protected UI.ButtonView LogOutBtn = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform BannersView = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Button BannerWIdget = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Button BannerWIdget1 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Button BannerWIdget2 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Button BannerWIdget3 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Button LeaderBoardBtn = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Button SettingsButton = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Text Text = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI OnlineText = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform TMPSubMeshUIBADGRUNGEAtlasMaterialAcmeRegularSDFAtlas = default;
        #pragma warning restore 0414
        
        protected override void AutoInit()
        {
            Instance = this;
        }
        
        protected override void AutoSubscribe()
        {
            SubscribeOnChanged(FadeImg);
            SubscribeOnChanged(LogoImg);
            SubscribeOnChanged(ButtonsPnl);
            SubscribeOnChanged(PlayBtn);
            SubscribeOnChanged(DuelsBtn);
            SubscribeOnChanged(DeckBtn);
            SubscribeOnChanged(LavaShopBtn);
            SubscribeOnChanged(ProfileBtn);
            SubscribeOnChanged(LogOutBtn);
            SubscribeOnChanged(BannersView);
            SubscribeOnChanged(BannerWIdget);
            SubscribeOnChanged(BannerWIdget1);
            SubscribeOnChanged(BannerWIdget2);
            SubscribeOnChanged(BannerWIdget3);
            SubscribeOnChanged(LeaderBoardBtn);
            SubscribeOnChanged(SettingsButton);
            SubscribeOnChanged(Text);
            SubscribeOnChanged(OnlineText);
            SubscribeOnChanged(TMPSubMeshUIBADGRUNGEAtlasMaterialAcmeRegularSDFAtlas);
        }
        
        [VisibleInGraph(false)]
        public MenuView Build()
        {
            OnBuildSafe(true);
            return this;
        }
        #region Static Methods
        public static void ShowInstance() => Instance.Show();
        public static void HideInstance() => Instance.Hide();
        public static void CloseInstance() => Instance.Close();
        #endregion
    }
}