/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using UnityEngine.UI;
using RR.UI;
using RR.UI.FrameSystem;

namespace UI
{
	public partial class MulliganCardView : RR.UI.FrameSystem.BaseView //Autogenerated
	{
		public static MulliganCardView Instance { get; private set; }
		// Controls
#pragma warning disable 0414
		[Header("Controls (auto capture)")]
		[AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI ExchangeTxt = default;
		[AutoGenerated, SerializeField] protected UI.HandCardView HandCardView = default;
#pragma warning restore 0414
        
		protected override void AutoInit()
		{
			Instance = this;
		}
        
		protected override void AutoSubscribe()
		{
			SubscribeOnChanged(ExchangeTxt);
			SubscribeOnChanged(HandCardView);
		}
        
		[VisibleInGraph(false)]
		public MulliganCardView Build()
		{
			OnBuildSafe(true);
			return this;
		}
		#region Static Methods
		public static void ShowInstance() => Instance.Show();
		public static void HideInstance() => Instance.Hide();
		public static void CloseInstance() => Instance.Close();
		#endregion
	}
}