/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using UnityEngine.UI;
using RR.UI;
using RR.UI.FrameSystem;

namespace UI
{
    public partial class OpponentManaPanel : BaseView //Autogenerated
    {
        /// <summary>Static instance of the view</summary>
        public static OpponentManaPanel Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        [Header("Controls (auto capture)")]
        [AutoGenerated, SerializeField] UnityEngine.RectTransform ManaTextPanel = default;
        [AutoGenerated, SerializeField] TMPro.TextMeshProUGUI ManaValueTxt = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.Image ManaIconImage = default;
        #pragma warning restore 0414
        
        protected override void AutoInit()
        {
            Instance = this;
        }
        
        protected override void AutoSubscribe()
        {
            SubscribeOnChanged(ManaTextPanel);
            SubscribeOnChanged(ManaValueTxt);
            SubscribeOnChanged(ManaIconImage);
        }
        
        [VisibleInGraph(false)]
        public OpponentManaPanel Build()
        {
            OnBuildSafe(true);
            return this;
        }
    }
}