/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using UnityEngine.UI;
using RR.UI;
using RR.UI.FrameSystem;

namespace UI
{
    public partial class OpponentHandCardView : UI.MonoEntityBaseView //Autogenerated
    {
        public static OpponentHandCardView Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        [Header("Controls (auto capture)")]
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image CardShirtImage = default;
        #pragma warning restore 0414
        
        protected override void AutoInit()
        {
        }
        
        protected override void AutoSubscribe()
        {
            SubscribeOnChanged(CardShirtImage);
        }
        
        [VisibleInGraph(false)]
        public OpponentHandCardView Build()
        {
            OnBuildSafe(true);
            return this;
        }
        #region Static Methods
        public static void ShowInstance() => Instance.Show();
        public static void HideInstance() => Instance.Hide();
        public static void CloseInstance() => Instance.Close();
        #endregion
    }
}