/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using BerserkV3.Lobby.UI;
using UnityEngine.UI;
using RR.UI;
using RR.UI.FrameSystem;

namespace UI
{
    public partial class PlayerDecksView : RR.UI.FrameSystem.BaseView //Autogenerated
    {
        public static PlayerDecksView Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        [Header("Controls (auto capture)")]
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image ContentMask = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform DecksPanel = default;
        [AutoGenerated, SerializeField] protected DeckButtonView DeckButton = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image VerticalLine = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image VerticalDividingLine = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform SelectedDeckPanel = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI DeckTitleText = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform AvatarPanel = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image HexMask = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.RawImage  PlayerImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Button ProfilePictureButton = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI NameTxt = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform DescriptionContainer = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI LableTxt = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform TMPSubMeshUIBADGRUNGEAtlasMaterialAcmeRegularSDFAtlas = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI EffectTxt = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image LevelImg = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI LevelTxt = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform Buttons = default;
        [AutoGenerated, SerializeField] protected UI.ButtonView DeleteButton = default;
        [AutoGenerated, SerializeField] protected UI.ButtonView EditButton = default;
        [AutoGenerated, SerializeField] protected UI.ButtonView BackButton = default;
        [AutoGenerated, SerializeField] protected UI.ButtonView NewButton = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform TitleImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image MaskImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BackgroundImageWhite = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI TitleText = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BorderImage = default;
        #pragma warning restore 0414
        
        protected override void AutoInit()
        {
            Instance = this;
        }
        
        protected override void AutoSubscribe()
        {
            SubscribeOnChanged(ContentMask);
            SubscribeOnChanged(DecksPanel);
            SubscribeOnChanged(DeckButton);
            SubscribeOnChanged(VerticalLine);
            SubscribeOnChanged(VerticalDividingLine);
            SubscribeOnChanged(SelectedDeckPanel);
            SubscribeOnChanged(DeckTitleText);
            SubscribeOnChanged(AvatarPanel);
            SubscribeOnChanged(HexMask);
            SubscribeOnChanged(PlayerImage);
            SubscribeOnChanged(ProfilePictureButton);
            SubscribeOnChanged(NameTxt);
            SubscribeOnChanged(DescriptionContainer);
            SubscribeOnChanged(LableTxt);
            SubscribeOnChanged(TMPSubMeshUIBADGRUNGEAtlasMaterialAcmeRegularSDFAtlas);
            SubscribeOnChanged(EffectTxt);
            SubscribeOnChanged(LevelImg);
            SubscribeOnChanged(LevelTxt);
            SubscribeOnChanged(Buttons);
            SubscribeOnChanged(DeleteButton);
            SubscribeOnChanged(EditButton);
            SubscribeOnChanged(BackButton);
            SubscribeOnChanged(NewButton);
            SubscribeOnChanged(TitleImage);
            SubscribeOnChanged(MaskImage);
            SubscribeOnChanged(BackgroundImageWhite);
            SubscribeOnChanged(TitleText);
            SubscribeOnChanged(BorderImage);
        }
        
        [VisibleInGraph(false)]
        public PlayerDecksView Build()
        {
            OnBuildSafe(true);
            return this;
        }
        #region Static Methods
        public static void ShowInstance() => Instance.Show();
        public static void HideInstance() => Instance.Hide();
        public static void CloseInstance() => Instance.Close();
        #endregion
    }
}