/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using UnityEngine.UI;
using RR.UI;
using RR.UI.FrameSystem;

namespace UI
{
    public partial class PlayedCardsView : RR.UI.FrameSystem.BaseView //Autogenerated
    {
        public static PlayedCardsView Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        [Header("Controls (auto capture)")]
        [AutoGenerated, SerializeField] protected UI.HandCardView PlayerHandCard = default;
        #pragma warning restore 0414
        
        protected override void AutoInit()
        {
            Instance = this;
        }
        
        protected override void AutoSubscribe()
        {
            SubscribeOnChanged(PlayerHandCard);
        }
        
        [VisibleInGraph(false)]
        public PlayedCardsView Build()
        {
            OnBuildSafe(true);
            return this;
        }
    }
}