/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using UnityEngine.UI;
using RR.UI;
using RR.UI.FrameSystem;

namespace UI
{
    public partial class PlayerManaPanel : RR.UI.FrameSystem.BaseView //Autogenerated
    {
        /// <summary>Static instance of the view</summary>
        public static PlayerManaPanel Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        [Header("Controls (auto capture)")]
        [AutoGenerated, SerializeField] UnityEngine.RectTransform ManaTextPanel = default;
        [AutoGenerated, SerializeField] TMPro.TextMeshProUGUI ManaValueTxt = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.Image ManaIconImage = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.Image LavaGlow = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.Image ManaDotsPanel = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.Image ManaSlot0 = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.Image ManaSlotFilledImg = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.Image LavaGlow1 = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.Image ManaSlot1 = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.Image ManaSlotFilledImg1 = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.Image LavaGlow2 = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.Image ManaSlot2 = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.Image ManaSlotFilledImg2 = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.Image LavaGlow3 = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.Image ManaSlot3 = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.Image ManaSlotFilledImg3 = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.Image LavaGlow4 = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.Image ManaSlot4 = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.Image ManaSlotFilledImg4 = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.Image LavaGlow5 = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.Image ManaSlot5 = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.Image ManaSlotFilledImg5 = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.Image LavaGlow6 = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.Image ManaSlot6 = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.Image ManaSlotFilledImg6 = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.Image LavaGlow7 = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.Image ManaSlot7 = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.Image ManaSlotFilledImg7 = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.Image LavaGlow8 = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.Image ManaSlot8 = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.Image ManaSlotFilledImg8 = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.Image LavaGlow9 = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.Image ManaSlot9 = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.Image ManaSlotFilledImg9 = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.Image LavaGlow10 = default;
        #pragma warning restore 0414
        
        protected override void AutoInit()
        {
            Instance = this;
        }
        
        protected override void AutoSubscribe()
        {
            SubscribeOnChanged(ManaTextPanel);
            SubscribeOnChanged(ManaValueTxt);
            SubscribeOnChanged(ManaIconImage);
            SubscribeOnChanged(LavaGlow);
            SubscribeOnChanged(ManaDotsPanel);
            SubscribeOnChanged(ManaSlot0);
            SubscribeOnChanged(ManaSlotFilledImg);
            SubscribeOnChanged(LavaGlow1);
            SubscribeOnChanged(ManaSlot1);
            SubscribeOnChanged(ManaSlotFilledImg1);
            SubscribeOnChanged(LavaGlow2);
            SubscribeOnChanged(ManaSlot2);
            SubscribeOnChanged(ManaSlotFilledImg2);
            SubscribeOnChanged(LavaGlow3);
            SubscribeOnChanged(ManaSlot3);
            SubscribeOnChanged(ManaSlotFilledImg3);
            SubscribeOnChanged(LavaGlow4);
            SubscribeOnChanged(ManaSlot4);
            SubscribeOnChanged(ManaSlotFilledImg4);
            SubscribeOnChanged(LavaGlow5);
            SubscribeOnChanged(ManaSlot5);
            SubscribeOnChanged(ManaSlotFilledImg5);
            SubscribeOnChanged(LavaGlow6);
            SubscribeOnChanged(ManaSlot6);
            SubscribeOnChanged(ManaSlotFilledImg6);
            SubscribeOnChanged(LavaGlow7);
            SubscribeOnChanged(ManaSlot7);
            SubscribeOnChanged(ManaSlotFilledImg7);
            SubscribeOnChanged(LavaGlow8);
            SubscribeOnChanged(ManaSlot8);
            SubscribeOnChanged(ManaSlotFilledImg8);
            SubscribeOnChanged(LavaGlow9);
            SubscribeOnChanged(ManaSlot9);
            SubscribeOnChanged(ManaSlotFilledImg9);
            SubscribeOnChanged(LavaGlow10);
        }
        
        [VisibleInGraph(false)]
        public PlayerManaPanel Build()
        {
            OnBuildSafe(true);
            return this;
        }
    }
}