/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using UnityEngine.UI;
using RR.UI;
using RR.UI.FrameSystem;

namespace UI
{
    public partial class ProfilePageView : PageView //Autogenerated
    {
        public static ProfilePageView Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        [Header("Controls (auto capture)")]
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform UserLayout = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.RawImage AvatarMask = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.RawImage AvatarImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform UserStatsLayout = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI FavoriteDeckText = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform FavoriteDeckGide = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform FavoriteDeckLayout = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Button SeeMoreButton = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI SeeMoreText = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform FavoritsLayout = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform InGameLayout = default;
        [AutoGenerated, SerializeField] protected UI.ButtonView CloseButton = default;
        #pragma warning restore 0414
        
        protected override void AutoInit()
        {
            Instance = this;
        }
        
        protected override void AutoSubscribe()
        {
            SubscribeOnChanged(UserLayout);
            SubscribeOnChanged(AvatarMask);
            SubscribeOnChanged(AvatarImage);
            SubscribeOnChanged(UserStatsLayout);
            SubscribeOnChanged(FavoriteDeckText);
            SubscribeOnChanged(FavoriteDeckGide);
            SubscribeOnChanged(FavoriteDeckLayout);
            SubscribeOnChanged(SeeMoreButton);
            SubscribeOnChanged(SeeMoreText);
            SubscribeOnChanged(FavoritsLayout);
            SubscribeOnChanged(InGameLayout);
            SubscribeOnChanged(CloseButton);
        }
        
        [VisibleInGraph(false)]
        public ProfilePageView Build()
        {
            OnBuildSafe(true);
            return this;
        }
        #region Static Methods
        public static void ShowInstance() => Instance.Show();
        public static void HideInstance() => Instance.Hide();
        public static void CloseInstance() => Instance.Close();
        #endregion
    }
}