/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using UnityEngine.UI;
using RR.UI;
using RR.UI.FrameSystem;
using UI;

namespace UI
{
    public partial class ProfileView : RR.UI.FrameSystem.BaseView //Autogenerated
    {
        public static ProfileView Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        [Header("Controls (auto capture)")]
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform TabLayout = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform ProfileTab = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform Mask = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Button TabProfileButton = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image TabProfileSelected = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI Text = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform StatisticsTab = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform MaskImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Button TabStatisticsButton = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image TabStatisticsSelected = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI Text1 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform CustomisationTab = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform MaskImage1 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Button TabCustomisationButton = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image TabCustomisationSelected = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI Text2 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform FavoriteDeckTab = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform MaskImage2 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Button TabFavoriteDeckButton = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image TabFavoriteDeckSelected = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI Text3 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image Background = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform TitleLayout = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image MaskImage3 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image TitleBackground = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI TitleText = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BorderImage = default;
        [AutoGenerated, SerializeField] protected UI.ProfilePageView ProfilePage = default;
        [AutoGenerated, SerializeField] protected UI.StatisticsPageView StatisticsPage = default;
        [AutoGenerated, SerializeField] protected CustomisationPageView CustomisationPage = default;
        [AutoGenerated, SerializeField] protected FavoriteDeckPageView FavoriteDeckPage = default;
        [AutoGenerated, SerializeField] protected VulcaniteStatisticView VulcaniteStatisticView = default;
        [AutoGenerated, SerializeField] protected VerticalStatisticView VerticalStatisticView = default;
        [AutoGenerated, SerializeField] protected HorizontalStatisticView HorizontalStatisticView = default;
        [AutoGenerated, SerializeField] protected CardStatisticView CardStatisticView = default;
        #pragma warning restore 0414
        
        protected override void AutoInit()
        {
            Instance = this;
        }
        
        protected override void AutoSubscribe()
        {
            SubscribeOnChanged(TabLayout);
            SubscribeOnChanged(ProfileTab);
            SubscribeOnChanged(Mask);
            SubscribeOnChanged(TabProfileButton);
            SubscribeOnChanged(TabProfileSelected);
            SubscribeOnChanged(Text);
            SubscribeOnChanged(StatisticsTab);
            SubscribeOnChanged(MaskImage);
            SubscribeOnChanged(TabStatisticsButton);
            SubscribeOnChanged(TabStatisticsSelected);
            SubscribeOnChanged(Text1);
            SubscribeOnChanged(CustomisationTab);
            SubscribeOnChanged(MaskImage1);
            SubscribeOnChanged(TabCustomisationButton);
            SubscribeOnChanged(TabCustomisationSelected);
            SubscribeOnChanged(Text2);
            SubscribeOnChanged(FavoriteDeckTab);
            SubscribeOnChanged(MaskImage2);
            SubscribeOnChanged(TabFavoriteDeckButton);
            SubscribeOnChanged(TabFavoriteDeckSelected);
            SubscribeOnChanged(Text3);
            SubscribeOnChanged(Background);
            SubscribeOnChanged(TitleLayout);
            SubscribeOnChanged(MaskImage3);
            SubscribeOnChanged(TitleBackground);
            SubscribeOnChanged(TitleText);
            SubscribeOnChanged(BorderImage);
            SubscribeOnChanged(ProfilePage);
            SubscribeOnChanged(StatisticsPage);
            SubscribeOnChanged(CustomisationPage);
            SubscribeOnChanged(FavoriteDeckPage);
            SubscribeOnChanged(VulcaniteStatisticView);
            SubscribeOnChanged(VerticalStatisticView);
            SubscribeOnChanged(HorizontalStatisticView);
            SubscribeOnChanged(CardStatisticView);
        }
        
        [VisibleInGraph(false)]
        public ProfileView Build()
        {
            OnBuildSafe(true);
            return this;
        }
        #region Static Methods
        public static void ShowInstance() => Instance.Show();
        public static void HideInstance() => Instance.Hide();
        public static void CloseInstance() => Instance.Close();
        #endregion
    }
}