/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using UnityEngine.UI;
using RR.UI;
using RR.UI.FrameSystem;

namespace UI
{
    public partial class RoundButtonView : RR.UI.FrameSystem.BaseView //Autogenerated
    {
        public static RoundButtonView Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        [Header("Controls (auto capture)")]
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform ButtonPanel = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Button EndTurnBtn = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI EndTurnTxt = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image TimerImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.CanvasGroup EnemyTurnPanel = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image EndTurnImage = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI EndTurnTxt1 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image TimerImage1 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.CanvasGroup ChangingPanel = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image EndTurnImage1 = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI EndTurnTxt2 = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI TimerTxt = default;
        [AutoGenerated, SerializeField] protected UnityEngine.CanvasGroup ChangeImage = default;
        #pragma warning restore 0414
        
        protected override void AutoInit()
        {
            Instance = this;
        }
        
        protected override void AutoSubscribe()
        {
            SubscribeOnChanged(ButtonPanel);
            SubscribeOnChanged(EndTurnBtn);
            SubscribeOnChanged(EndTurnTxt);
            SubscribeOnChanged(TimerImage);
            SubscribeOnChanged(EnemyTurnPanel);
            SubscribeOnChanged(EndTurnImage);
            SubscribeOnChanged(EndTurnTxt1);
            SubscribeOnChanged(TimerImage1);
            SubscribeOnChanged(ChangingPanel);
            SubscribeOnChanged(EndTurnImage1);
            SubscribeOnChanged(EndTurnTxt2);
            SubscribeOnChanged(TimerTxt);
            SubscribeOnChanged(ChangeImage);
        }
        
        [VisibleInGraph(false)]
        public RoundButtonView Build()
        {
            OnBuildSafe(true);
            return this;
        }
        #region Static Methods
        public static void ShowInstance() => Instance.Show();
        public static void HideInstance() => Instance.Hide();
        public static void CloseInstance() => Instance.Close();
        #endregion
    }
}