/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using UnityEngine.UI;
using RR.UI;
using RR.UI.FrameSystem;

namespace UI
{
    public partial class SettingsView : RR.UI.FrameSystem.BaseView //Autogenerated
    {
        public static SettingsView Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        [Header("Controls (auto capture)")]
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform Container = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image Background = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform TitleImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image MaskImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BackgroundImage = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI TitleText = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BorderImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform ButtonsPnl = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform VisualRoot = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform ArenaBox = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image ArenaPanel = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI ArenaTitle = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI ArenaHint = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Button Theme_classic = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image Glow = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image PreviewFrame = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.RawImage BgPreview = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.RawImage BoardPreview = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI classic_Name = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI classic_Active = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Button Theme_boreas = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image Glow1 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image PreviewFrame1 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.RawImage BgPreview1 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.RawImage BoardPreview1 = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI boreas_Name = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI boreas_Active = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Button Theme_arcadia = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image Glow2 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image PreviewFrame2 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.RawImage BgPreview2 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.RawImage BoardPreview2 = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI arcadia_Name = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI arcadia_Active = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Button Theme_hades = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image Glow3 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image PreviewFrame3 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.RawImage BgPreview3 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.RawImage BoardPreview3 = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI hades_Name = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI hades_Active = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Button Theme_notus = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image Glow4 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image PreviewFrame4 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.RawImage BgPreview4 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.RawImage BoardPreview4 = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI notus_Name = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI notus_Active = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Button Theme_colosseum = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image Glow5 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image PreviewFrame5 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.RawImage BgPreview5 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.RawImage BoardPreview5 = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI colosseum_Name = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI colosseum_Active = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform LayoutBox = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI LayoutLabel = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI LayoutHint = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Button LayoutToggle = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI ToggleLabel = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform AudioRoot = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform MusicContainer = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Slider MusicSlider = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image Background1 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image Image = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform HandleSlideArea = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform Handle = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image Handle1 = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI MusicLabel = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform AudioContainer = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Slider AudioSlider = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image Background2 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image Image1 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform HandleSlideArea1 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform Handle2 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image Handle11 = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI AudioLabel = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform FooterRoot = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform ButtonsPanel = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Button RestartTutorBtn = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image MaskImage1 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BackgroundImage1 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BorderImage1 = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI OKText = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Button CloseBtn = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image MaskImage2 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BackgroundImage2 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BorderImage2 = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI OKText1 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform TabBar = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Button VisualTab = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI VisualTab_Lbl = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image VisualTab_Line = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Button AudioTab = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI AudioTab_Lbl = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image AudioTab_Line = default;
        #pragma warning restore 0414
        
        protected override void AutoInit()
        {
            Instance = this;
        }
        
        protected override void AutoSubscribe()
        {
            SubscribeOnChanged(Container);
            SubscribeOnChanged(Background);
            SubscribeOnChanged(TitleImage);
            SubscribeOnChanged(MaskImage);
            SubscribeOnChanged(BackgroundImage);
            SubscribeOnChanged(TitleText);
            SubscribeOnChanged(BorderImage);
            SubscribeOnChanged(ButtonsPnl);
            SubscribeOnChanged(VisualRoot);
            SubscribeOnChanged(ArenaBox);
            SubscribeOnChanged(ArenaPanel);
            SubscribeOnChanged(ArenaTitle);
            SubscribeOnChanged(ArenaHint);
            SubscribeOnChanged(Theme_classic);
            SubscribeOnChanged(Glow);
            SubscribeOnChanged(PreviewFrame);
            SubscribeOnChanged(BgPreview);
            SubscribeOnChanged(BoardPreview);
            SubscribeOnChanged(classic_Name);
            SubscribeOnChanged(classic_Active);
            SubscribeOnChanged(Theme_boreas);
            SubscribeOnChanged(Glow1);
            SubscribeOnChanged(PreviewFrame1);
            SubscribeOnChanged(BgPreview1);
            SubscribeOnChanged(BoardPreview1);
            SubscribeOnChanged(boreas_Name);
            SubscribeOnChanged(boreas_Active);
            SubscribeOnChanged(Theme_arcadia);
            SubscribeOnChanged(Glow2);
            SubscribeOnChanged(PreviewFrame2);
            SubscribeOnChanged(BgPreview2);
            SubscribeOnChanged(BoardPreview2);
            SubscribeOnChanged(arcadia_Name);
            SubscribeOnChanged(arcadia_Active);
            SubscribeOnChanged(Theme_hades);
            SubscribeOnChanged(Glow3);
            SubscribeOnChanged(PreviewFrame3);
            SubscribeOnChanged(BgPreview3);
            SubscribeOnChanged(BoardPreview3);
            SubscribeOnChanged(hades_Name);
            SubscribeOnChanged(hades_Active);
            SubscribeOnChanged(Theme_notus);
            SubscribeOnChanged(Glow4);
            SubscribeOnChanged(PreviewFrame4);
            SubscribeOnChanged(BgPreview4);
            SubscribeOnChanged(BoardPreview4);
            SubscribeOnChanged(notus_Name);
            SubscribeOnChanged(notus_Active);
            SubscribeOnChanged(Theme_colosseum);
            SubscribeOnChanged(Glow5);
            SubscribeOnChanged(PreviewFrame5);
            SubscribeOnChanged(BgPreview5);
            SubscribeOnChanged(BoardPreview5);
            SubscribeOnChanged(colosseum_Name);
            SubscribeOnChanged(colosseum_Active);
            SubscribeOnChanged(LayoutBox);
            SubscribeOnChanged(LayoutLabel);
            SubscribeOnChanged(LayoutHint);
            SubscribeOnChanged(LayoutToggle);
            SubscribeOnChanged(ToggleLabel);
            SubscribeOnChanged(AudioRoot);
            SubscribeOnChanged(MusicContainer);
            SubscribeOnChanged(MusicSlider);
            SubscribeOnChanged(Background1);
            SubscribeOnChanged(Image);
            SubscribeOnChanged(HandleSlideArea);
            SubscribeOnChanged(Handle);
            SubscribeOnChanged(Handle1);
            SubscribeOnChanged(MusicLabel);
            SubscribeOnChanged(AudioContainer);
            SubscribeOnChanged(AudioSlider);
            SubscribeOnChanged(Background2);
            SubscribeOnChanged(Image1);
            SubscribeOnChanged(HandleSlideArea1);
            SubscribeOnChanged(Handle2);
            SubscribeOnChanged(Handle11);
            SubscribeOnChanged(AudioLabel);
            SubscribeOnChanged(FooterRoot);
            SubscribeOnChanged(ButtonsPanel);
            SubscribeOnChanged(RestartTutorBtn);
            SubscribeOnChanged(MaskImage1);
            SubscribeOnChanged(BackgroundImage1);
            SubscribeOnChanged(BorderImage1);
            SubscribeOnChanged(OKText);
            SubscribeOnChanged(CloseBtn);
            SubscribeOnChanged(MaskImage2);
            SubscribeOnChanged(BackgroundImage2);
            SubscribeOnChanged(BorderImage2);
            SubscribeOnChanged(OKText1);
            SubscribeOnChanged(TabBar);
            SubscribeOnChanged(VisualTab);
            SubscribeOnChanged(VisualTab_Lbl);
            SubscribeOnChanged(VisualTab_Line);
            SubscribeOnChanged(AudioTab);
            SubscribeOnChanged(AudioTab_Lbl);
            SubscribeOnChanged(AudioTab_Line);
        }
        
        [VisibleInGraph(false)]
        public SettingsView Build()
        {
            OnBuildSafe(true);
            return this;
        }
        #region Static Methods
        public static void ShowInstance() => Instance.Show();
        public static void HideInstance() => Instance.Hide();
        public static void CloseInstance() => Instance.Close();
        #endregion
    }
}