/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using UnityEngine.UI;
using RR.UI;
using RR.UI.FrameSystem;

namespace UI
{
    public partial class StatisticsPageView : UI.PageView //Autogenerated
    {
        public static StatisticsPageView Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        [Header("Controls (auto capture)")]
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform ButtonsLayout = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Button Player1Button = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image MaskImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BackgroundImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image Player1OverlayImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BorderImage = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI Player1Text = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Button Player2Button = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image MaskImage1 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BackgroundImage1 = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image Player2OverlayImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image BorderImage1 = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI Player2Text = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.ScrollRect ScrollView = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform Viewport = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image Content = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Scrollbar ScrollbarVertical = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform SlidingArea = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image Handle = default;
        [AutoGenerated, SerializeField] protected UI.ButtonView CloseButton = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI VulcaniteWinrates = default;
        #pragma warning restore 0414
        
        protected override void AutoInit()
        {
            Instance = this;
        }
        
        protected override void AutoSubscribe()
        {
            SubscribeOnChanged(ButtonsLayout);
            SubscribeOnChanged(Player1Button);
            SubscribeOnChanged(MaskImage);
            SubscribeOnChanged(BackgroundImage);
            SubscribeOnChanged(Player1OverlayImage);
            SubscribeOnChanged(BorderImage);
            SubscribeOnChanged(Player1Text);
            SubscribeOnChanged(Player2Button);
            SubscribeOnChanged(MaskImage1);
            SubscribeOnChanged(BackgroundImage1);
            SubscribeOnChanged(Player2OverlayImage);
            SubscribeOnChanged(BorderImage1);
            SubscribeOnChanged(Player2Text);
            SubscribeOnChanged(ScrollView);
            SubscribeOnChanged(Viewport);
            SubscribeOnChanged(Content);
            SubscribeOnChanged(ScrollbarVertical);
            SubscribeOnChanged(SlidingArea);
            SubscribeOnChanged(Handle);
            SubscribeOnChanged(CloseButton);
            SubscribeOnChanged(VulcaniteWinrates);
        }
        
        [VisibleInGraph(false)]
        public StatisticsPageView Build()
        {
            OnBuildSafe(true);
            return this;
        }
        #region Static Methods
        public static void ShowInstance() => Instance.Show();
        public static void HideInstance() => Instance.Hide();
        public static void CloseInstance() => Instance.Close();
        #endregion
    }
}