/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using UnityEngine.UI;
using RR.UI;
using RR.UI.FrameSystem;

namespace UI
{
    public partial class TableCardView : UI.EntityView //Autogenerated
    {
        /// <summary>Static instance of the view</summary>
        public static TableCardView Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        [Header("Controls (auto capture)")]
        [AutoGenerated, SerializeField] UnityEngine.RectTransform EntityContainer = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.Image TargetImg = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.Image CardArtMask = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.RawImage CarArtImg = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.Image CardBorder = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.Image CardStat_AtkImg = default;
        [AutoGenerated, SerializeField] TMPro.TextMeshProUGUI CardStatAtkTxt = default;
        [AutoGenerated, SerializeField] UnityEngine.UI.Image CardStat_HPImg = default;
        [AutoGenerated, SerializeField] TMPro.TextMeshProUGUI CardStatHPTxt = default;
        [AutoGenerated, SerializeField] UnityEngine.RectTransform TooltipHolder = default;
        [AutoGenerated, SerializeField] UI.CardTooltipPanel TooltipPanel = default;
        #pragma warning restore 0414
        
        protected override void AutoInit()
        {
            Instance = this;
        }
        
        protected override void AutoSubscribe()
        {
            SubscribeOnChanged(EntityContainer);
            SubscribeOnChanged(TargetImg);
            SubscribeOnChanged(CardArtMask);
            SubscribeOnChanged(CarArtImg);
            SubscribeOnChanged(CardBorder);
            SubscribeOnChanged(CardStat_AtkImg);
            SubscribeOnChanged(CardStatAtkTxt);
            SubscribeOnChanged(CardStat_HPImg);
            SubscribeOnChanged(CardStatHPTxt);
            SubscribeOnChanged(TooltipHolder);
            SubscribeOnChanged(TooltipPanel);
        }
        
        [VisibleInGraph(false)]
        public TableCardView Build()
        {
            OnBuildSafe(true);
            return this;
        }
    }
}