/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using UnityEngine.UI;
using RR.UI;
using RR.UI.FrameSystem;

namespace UI
{
    public partial class TableActiveZonePanel : BaseView //Autogenerated
    {
        /// <summary>Static instance of the view</summary>
        public static TableActiveZonePanel Instance { get; private set; }
        // Controls
        
        protected override void AutoInit()
        {
            Instance = this;
        }
        
        protected override void AutoSubscribe()
        {
        }
        
        [VisibleInGraph(false)]
        public TableActiveZonePanel Build()
        {
            OnBuildSafe(true);
            return this;
        }
    }
}