/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using UnityEngine.UI;
using RR.UI;
using RR.UI.FrameSystem;

namespace UI
{
    public partial class VulcaniteStatisticView : UI.BaseStatisticView //Autogenerated
    {
        public static VulcaniteStatisticView Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        [Header("Controls (auto capture)")]
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image WholeBackground = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform ImageLayout = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.RawImage Mask = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.RawImage Image = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.RawImage BorderImage = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform TextLayout = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image TextBackground = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI TextKey = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI TextValue = default;
        #pragma warning restore 0414
        
        protected override void AutoInit()
        {
            Instance = this;
        }
        
        protected override void AutoSubscribe()
        {
            SubscribeOnChanged(WholeBackground);
            SubscribeOnChanged(ImageLayout);
            SubscribeOnChanged(Mask);
            SubscribeOnChanged(Image);
            SubscribeOnChanged(BorderImage);
            SubscribeOnChanged(TextLayout);
            SubscribeOnChanged(TextBackground);
            SubscribeOnChanged(TextKey);
            SubscribeOnChanged(TextValue);
        }
        
        [VisibleInGraph(false)]
        public VulcaniteStatisticView Build()
        {
            OnBuildSafe(true);
            return this;
        }
        #region Static Methods
        public static void ShowInstance() => Instance.Show();
        public static void HideInstance() => Instance.Hide();
        public static void CloseInstance() => Instance.Close();
        #endregion
    }
}