/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using UnityEngine.UI;
using RR.UI;
using RR.UI.FrameSystem;

namespace BerserkV3.Common.TutorialSystem
{
    public partial class UITutorialWelcome : RR.UI.FrameSystem.BaseView //Autogenerated
    {
        public static UITutorialWelcome Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        [Header("Controls (auto capture)")]
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform Container = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image Background = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI HeaderText = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI BodyText = default;
        [AutoGenerated, SerializeField] protected BerserkV3.Common.UIKit.ComplexButton AcceptButton = default;
        [AutoGenerated, SerializeField] protected BerserkV3.Common.UIKit.ComplexButton DeclineButton = default;
        #pragma warning restore 0414
        
        protected override void AutoInit()
        {
            Instance = this;
        }
        
        protected override void AutoSubscribe()
        {
            SubscribeOnChanged(Container);
            SubscribeOnChanged(Background);
            SubscribeOnChanged(HeaderText);
            SubscribeOnChanged(BodyText);
            SubscribeOnChanged(AcceptButton);
            SubscribeOnChanged(DeclineButton);
        }
        
        [VisibleInGraph(false)]
        public UITutorialWelcome Build()
        {
            OnBuildSafe(true);
            return this;
        }
        #region Static Methods
        public static void ShowInstance() => Instance.Show();
        public static void HideInstance() => Instance.Hide();
        public static void CloseInstance() => Instance.Close();
        #endregion
    }
}