/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using UnityEngine.UI;
using RR.UI;
using RR.UI.FrameSystem;

namespace BerserkV3.Common.TutorialSystem
{
    public partial class UITutorialGeneric : RR.UI.FrameSystem.BaseView //Autogenerated
    {
        public static UITutorialGeneric Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        [Header("Controls (auto capture)")]
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform FullRectHint = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.RawImage ScalablePlaceHolder = default;
        [AutoGenerated, SerializeField] protected BerserkV3.Common.UIKit.ComplexButton NextButton = default;
        #pragma warning restore 0414
        
        protected override void AutoInit()
        {
            Instance = this;
        }
        
        protected override void AutoSubscribe()
        {
            SubscribeOnChanged(FullRectHint);
            SubscribeOnChanged(ScalablePlaceHolder);
            SubscribeOnChanged(NextButton);
        }
        
        [VisibleInGraph(false)]
        public UITutorialGeneric Build()
        {
            OnBuildSafe(true);
            return this;
        }
        #region Static Methods
        public static void ShowInstance() => Instance.Show();
        public static void HideInstance() => Instance.Hide();
        public static void CloseInstance() => Instance.Close();
        #endregion
    }
}