using RR.Core.Extensions;
using RR.UI.Custom;
using RR.UI.FrameSystem.Animations;
using RR.UI.FrameSystem.Utils;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using UnityEngine;
using UnityEngine.UI;

namespace RR.UI.FrameSystem
{
	public abstract class BaseView : MonoBehaviour, IBaseViewInternal
	{
		public ViewAnimations Animations = new ViewAnimations();
		public ViewSounds Sounds = new ViewSounds();

		/// <summary>Show the view at start of scene </summary>
		[Header("Layout")]
		[Tooltip("Show the view at start of scene")]
		public bool ShowAtStart;
		/// <summary>Auto close opened neighbor views inside my parent</summary>
		[Tooltip("Close opened neighbor views inside my parent when the view is showing")]
		public bool Concurrent;
		/// <summary>When it is closing - close all children views</summary>
		[Tooltip("When it is closing - close all children views")]
		public bool AutoCloseChildren = true;
		/// <summary>Hide owner when opened</summary>
		[Tooltip("Hide owner when opened")]
		public bool HideOwner;
		/// <summary>Auto create fullscreen fade, modal window imitation</summary>
		[Tooltip("Auto create fullscreen fade, modal window imitation")]
		public bool FullscreenFade;
		/// <summary>Priority in Back stack. Higher priorities will be closed firstly. Value IgnoreBack will disable Back processing.</summary>
		[Tooltip("Priority in Back stack. Higher priorities will be closed firstly. Value IgnoreBack will disable Back processing.")]
		public BackPrority BackPrority = BackPrority.IgnoreBack;
		[Tooltip("Drag&Drop mode for the view")]
		public DragMode DragMode = DragMode.None;

#if UNITY_EDITOR
		[Header("Script Options")]
		[Tooltip("Parameters passed to Build method")]
		public string SignatureOfBuildMethod;
#endif

		[Header("Other")]
		[Tooltip("Button pressing causes OnChanged method")]
		public bool ButtonsCallOnChanged = false;
		[Tooltip("OnChanged method causes Rebuild method")]
		public bool OnChangedCallRebuild = false;
		[Tooltip("Do not pass gestures to owners")]
		public bool SuppressAnyGesturesForOwners = false;
		[Tooltip("Do not close the view by Back command")]
		public bool SuppressBack = false;
		[Tooltip("Allows UIManager.IsBlockingInteration")]
		public bool IsBlockingInteration = false;

		/// <summary>Logical visibility of the view</summary>
		public VisibleState VisibleState => visibleState;
		/// <summary>Current owner of the view</summary>
		public BaseView Owner { get; set; }
		/// <summary>Currently opened children of the view</summary>
		public List<BaseView> OpenedChildren { get; private set; } = new List<BaseView>();
		/// <summary>Owner for created children</summary>
		public BaseView OwnerForChild => AutoCloseChildren ? this : Owner;
		/// <summary>Data is changed</summary>
		public event Action Changed = delegate { };
		/// <summary>My RectTransform</summary>
		public RectTransform RectTransform => transform as RectTransform;
		public CanvasGroup CanvasGroup => transform.GetOrAddComponent<CanvasGroup>();
		/// <summary>The first parent Canvas rendering me</summary>
		public Canvas Canvas => transform.GetComponentInParent<Canvas>();
		/// <summary>True if the view was dynamically created from prefab</summary>
		public bool IsDynamicallyCreated { get; private set; } = false;

		public AnimationPlayer.AnimatedItem CurrentAnimation { get; set; }


		#region Private fields

		private Coroutine rebuildCoroutine;
		private int updatingCounter = 0;
		/// <summary>Components cache</summary>
		private Dictionary<(Component, Type), Component> componentCache;
		private VisibleState visibleState = VisibleState.Closed;

		private bool isInitialized = false;

		#endregion

		/// <summary>This method is called when script firstly activated. The Start is called for both static and dynamic views.</summary>
		protected virtual void Start()
		{
			AutoSubscribe();
		}

		private void Awake()
		{
			OnAwake();
		}

		/// <summary>
		/// Called after unity Awake executed on this.
		/// </summary>
		protected virtual void OnAwake() { }

		/// <summary>Called only once for view when scene loaded. This method is not called for dynamically created views</summary>
		public virtual void Initialize()
		{
			if (isInitialized || IsDynamicallyCreated)
				return;

			isInitialized = true;

			gameObject.SetActive(ShowAtStart);
			visibleState = ShowAtStart ? VisibleState.Visible : VisibleState.Closed;
			
			AutoInit();
			OnInit();
		}

		/// <summary>This method is called for static views at scene was loaded</summary>
		protected virtual void OnInit()
		{

			//override this method if needed make something after scene was loaded
		}

		protected virtual void AutoInit()
		{
			//this method is overridden in autogenerated script
		}


		protected virtual void AutoSubscribe()
		{
			//this method is overridden in autogenerated script
		}

		public IEnumerable<BaseView> GetMeAndMyOwners()
		{
			yield return this;

			if (Owner != null)
				foreach (var owner in Owner.GetMeAndMyOwners())
					yield return owner;
		}

		#region Show/Close/Hide

		/// <summary>Show the view</summary>
		[VisibleInGraph()]
		public void Show(BaseView owner = null, Action onAnimationDone = null, bool noAnimation = false, bool closeChildrenIfOpened = false, bool concurrentAnimation = false)
		{
			UIManager.Show(this, owner, onAnimationDone, noAnimation, closeChildrenIfOpened, concurrentAnimation);
		}

		[VisibleInGraph(false)]
		public void Show()
		{
			UIManager.Show(this, null, null, false, false);
		}

		/// <summary>Close the view and all children views</summary>
		[VisibleInGraph()]
		public void Close(Action onAnimationDone = null, bool noAnimation = false, bool concurrentAnimation = false)
		{
			UIManager.Close(this, onAnimationDone, noAnimation, concurrentAnimation);
		}

		/// <summary>Close the view and all children views</summary>
		[VisibleInGraph(false)]
		public void Close()
		{
			UIManager.Close(this, null, false);
		}

		/// <summary>Show the view if closed or hidden, close otherwise</summary>
		[VisibleInGraph()]
		public void ShowOrClose(BaseView owner, Action onAnimationDone = null, bool noAnimation = false, bool concurrentAnimation = false)
		{
			UIManager.ShowOrClose(this, owner, onAnimationDone, noAnimation, concurrentAnimation);
		}

		/// <summary>Make the view invisible, but do not close children</summary>
		[VisibleInGraph(false)]
		public void Hide(Action onAnimationDone = null, bool noAnimation = false, bool concurrentAnimation = false)
		{
			UIManager.Hide(this, onAnimationDone, noAnimation, concurrentAnimation);
		}

		[VisibleInGraph(false)]
		public void Hide()
		{
			UIManager.Hide(this, null, false);
		}
		/// <summary>Close all children and show the view with previous Owner</summary>
		[VisibleInGraph(true)]
		public void Reopen(Action onAnimationDone = null, bool noAnimation = false, bool concurrentAnimation = false)
		{
			UIManager.Reopen(this, onAnimationDone, noAnimation);
		}

		/// <summary>Close last view in Back stack</summary>
		[VisibleInGraph(false)]
		public virtual void Back(Action onAnimationDone = null)
		{
			//close
			Close(onAnimationDone);
		}

		[VisibleInGraph(false)]
		public void CloseAllChildren()
		{
			UIManager.CloseAllChildren(this);
		}

		#endregion

		#region ShowCoroutine, ShowAsync

		/// <summary>Shows the view and wait while it will be closed</summary>
		public IEnumerator ShowCoroutine(BaseView owner, Action onAnimationDone = null, bool noAnimation = false, bool closeChildrenIfOpened = false)
		{
			Show(owner, onAnimationDone, noAnimation, closeChildrenIfOpened);
			while (VisibleState != VisibleState.Closed)
				yield return null;
		}

		/// <summary>Shows the view and wait while it will be closed</summary>
		public async Task ShowAsync(BaseView owner, Action onAnimationDone = null, bool noAnimation = false, bool closeChildrenIfOpened = false)
		{
			Show(owner, onAnimationDone, noAnimation, closeChildrenIfOpened);

			// TODO: 2918 Remove TaskEx - replace with states
			await TaskEx.WaitWhile(() => VisibleState != VisibleState.Closed);
		}

		#endregion

		#region Build (MVVM like pattern)

		/// <summary>Assign data to UI controls, interface updating. 
		/// This method can be overrided and assumes copying data to UI controls
		/// </summary>
		/// <remarks>Usually this method is calling by owner class to build the view. 
		/// Building assumes passing data to View and copying data to UI controls.
		/// This method also can be multiply called during View life. Ususally it is called when user changes value of controls or press buttons.
		/// Also you can call this method manually to update view (also you can use Rebuild calling).
		/// </remarks>
		/// <param name="isFirstBuild">True if outside class passed new data to View and full rebuild required. 
		/// False - means that Data is changed slightly, and you need just refresh View.</param>
		protected virtual void OnBuild(bool isFirstBuild)
		{
			//override this method and copy data to UI controls here
		}

		/// <summary>OnChanged is automatically called when value of controls was changed by user or buttons were pressed.
		/// This method can be overridden, and assumes copying data from UI controls to target data object.</summary>
		protected virtual void OnChanged()
		{
			//
			//override this method and copy data from UI controls to data object
			//

			if (updatingCounter > 0)
				return;//prevent infinite updating loop

			if (rebuildCoroutine == null)
				rebuildCoroutine = StartCoroutine(OnChangedRaw());
		}

		[VisibleInGraph]
		public virtual void Rebuild()
		{
			OnBuildSafe(false);
		}

		private IEnumerator OnChangedRaw()
		{
			//wait while all callbacks are executed
			yield return new WaitForEndOfFrame();

			try
			{
				updatingCounter++;

				//call Rebuild to update interface
				if (OnChangedCallRebuild)
					Rebuild();

				//call event
				Changed?.Invoke();
			}
			finally
			{
				updatingCounter--;
				rebuildCoroutine = null;
			}
		}

		protected void OnBuildSafe(bool isFirstCall)
		{
			try
			{
				updatingCounter++;
				OnBuild(isFirstCall);
			}
			finally
			{
				updatingCounter--;
			}
		}

		#endregion

		#region Grab components

#if UNITY_EDITOR

		private void Reset()
		{
			GrabComponents(true);
		}

#endif

		/// <summary>Find components inside me and assign to my fields</summary>
		public void GrabComponents(bool forced = false)
		{
			var components = SceneInfoGrabber<BaseView>.GrabInfo(this.transform, false);
			var type = this.GetType();

			foreach (var pair in components)
			{
				var fieldName = pair.Key;
				var fi = type.GetField(fieldName, BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance);
				if (fi == null)
				{
					if (SceneInfoGrabber<BaseView>.IsSpecialName(fieldName))
						Debug.LogWarning("Field not found: " + fieldName);
					continue;
				}

				if (!forced) //do not reassign
				{
					var obj = fi.GetValue(this);
					if (obj as UnityEngine.Object != null)
						continue;
				}

				var component = pair.Value;
				var compType = pair.Value.GetType();
				if (fi.FieldType.IsAssignableFrom(compType))
					fi.SetValue(this, component);
				else
					Debug.LogWarning("Type of field is not compatible: " + fieldName);
			}
		}

		internal void GrabViews(Dictionary<string, BaseView> views)
		{
			var type = this.GetType();

			foreach (var pair in views)
			{
				var fieldName = pair.Key;
				var fi = type.GetField(fieldName, BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance);
				if (fi == null)
					continue;

				if (fi.GetValue(this) != null) //do not reassign
					continue;

				var component = pair.Value;
				var compType = pair.Value.GetType();
				if (fi.FieldType.IsAssignableFrom(compType))
					fi.SetValue(this, component);
				else
					Debug.LogWarning("Type of field is not compatible: " + fieldName);
			}
		}

		#endregion

		#region Component helpers

		//subscribe Click/OnChanged
		protected void Subscribe(Button bt, Action act)
		{
			bt?.onClick.AddListener(() => { if (updatingCounter == 0) act?.Invoke(); });
		}

		protected void Subscribe(InputField comp, Action<string> act)
		{
			comp?.onValueChanged.AddListener(v => { if (updatingCounter == 0) act?.Invoke(v); });
		}

		protected void Subscribe(TMPro.TMP_InputField comp, Action<string> act)
		{
			comp?.onValueChanged.AddListener(v => { if (updatingCounter == 0) act?.Invoke(v); });
		}

		protected void Subscribe(Slider comp, Action<float> act)
		{
			comp?.onValueChanged.AddListener(v => { if (updatingCounter == 0) act?.Invoke(v); });
		}

		protected void Subscribe(Dropdown comp, Action<int> act)
		{
			comp?.onValueChanged.AddListener(v => { if (updatingCounter == 0) act?.Invoke(v); });
		}

		protected void Subscribe(TMPro.TMP_Dropdown comp, Action<int> act)
		{
			comp?.onValueChanged.AddListener(v => { if (updatingCounter == 0) act?.Invoke(v); });
		}

		protected void Subscribe(Toggle comp, Action<bool> act)
		{
			comp?.onValueChanged.AddListener(v => { if (updatingCounter == 0) act?.Invoke(v); });
		}

		protected void OnToggleIsOn(Toggle comp, Action act)
		{
			comp?.onValueChanged.AddListener(v => { if (updatingCounter == 0 && v) act.Invoke(); });
		}

		protected void Subscribe(BaseView view, Action act)
		{
			view.Changed += act;
		}

		protected void Subscribe(Gesture gesture, Action act)
		{
			Gestured += info =>
			{
				if (info.Gesture == gesture)
				{
					info.IsHandled = true;
					act();
				}
			};
		}

		//subscribe OnChanged method
		protected void SubscribeOnChanged(Button bt)
		{
			bt?.onClick.AddListener(() => { OnAnyButtonPressed(bt); if (ButtonsCallOnChanged && updatingCounter == 0) OnChanged(); });
		}

		protected void SubscribeOnChanged(RRButton bt)
		{
			((Button)bt)?.onClick.AddListener(() => { OnAnyButtonPressed(bt); if (ButtonsCallOnChanged && updatingCounter == 0) OnChanged(); });
			bt?.OnHover.AddListener(() => { OnAnyButtonOverlayed(bt); if (ButtonsCallOnChanged && updatingCounter == 0) OnChanged(); });
		}

		protected void SubscribeOnChanged(InputField comp)
		{
			comp?.onValueChanged.AddListener(v => { if (updatingCounter == 0) OnChanged(); });
		}

		protected void SubscribeOnChanged(TMPro.TMP_InputField comp)
		{
			comp?.onValueChanged.AddListener(v => { if (updatingCounter == 0) OnChanged(); });
		}

		protected void SubscribeOnChanged(Slider comp)
		{
			comp?.onValueChanged.AddListener(v => { if (updatingCounter == 0) OnChanged(); });
		}

		protected void SubscribeOnChanged(Dropdown comp)
		{
			comp?.onValueChanged.AddListener(v => { if (updatingCounter == 0) OnChanged(); });
		}

		protected void SubscribeOnChanged(Toggle comp)
		{
			comp?.onValueChanged.AddListener(v => { if (updatingCounter == 0) OnChanged(); });
		}

		protected void SubscribeOnChanged(Component comp)
		{
			//nothing (this method for autogenerated script)
		}

		//Set color
		protected void Set(Graphic comp, Color color)
		{
			comp.color = color;
		}

		protected void Set(Component comp, Color color)
		{
			var c0 = Get<Image>(comp);
			if (c0) c0.color = color;
			var c1 = Get<RawImage>(comp);
			if (c1) c1.color = color;
		}

		//Set text
		protected void Set(InputField comp, string text)
		{
			comp.SetTextWithoutNotify(text);
		}

		protected void Set(TMPro.TMP_InputField comp, string text)
		{
			comp.SetTextWithoutNotify(text);
		}

		protected void Set(Text comp, string text)
		{
			comp.text = text;
		}

		protected void Set(TMPro.TextMeshProUGUI comp, string text)
		{
			comp.SetText(text);
		}

		protected void Set(TMPro.TextMeshProUGUI comp, int text)
		{
			comp.SetText(text.ToString());
		}

		protected void Set(TMPro.TextMeshProUGUI comp, float text)
		{
			comp.SetText(text.ToString(CultureInfo.InvariantCulture));
		}

		protected void Set(TMPro.TextMeshProUGUI comp, double text)
		{
			comp.SetText(text.ToString(CultureInfo.InvariantCulture));
		}

		protected void Set(Component comp, string text)
		{
			var c1 = Get<TMPro.TextMeshProUGUI>(comp);
			if (c1)
			{
				c1.SetText(text);
				return;
			}

			var c0 = Get<Text>(comp);
			if (c0) c0.text = text;
		}

		//Set bool
		protected void Set(Toggle comp, bool val)
		{
			comp.SetIsOnWithoutNotify(val);
		}

		//Set int
		protected void Set(Slider comp, int val)
		{
			comp.SetValueWithoutNotify(val);
		}

		protected void Set(Dropdown comp, int val)
		{
			comp.SetValueWithoutNotify(val);
		}

		//Set float
		protected void Set(Slider comp, float val)
		{
			comp.SetValueWithoutNotify(val);
		}

		//Set sprite/texture
		protected void Set(Image comp, Sprite sprite)
		{
			comp.sprite = sprite;
		}

		protected void Set(RawImage comp, Texture texture)
		{
			comp.texture = texture;
		}

		protected void Set(Component comp, Sprite sprite)
		{
			var c0 = Get<Image>(comp);
			if (c0) c0.sprite = sprite;
		}

		protected void Set(Component comp, Texture texture)
		{
			var c0 = Get<RawImage>(comp);
			if (c0) c0.texture = texture;
		}

		//set active
		protected void SetActive(Component comp, bool active)
		{
			comp.gameObject.SetActive(active);
		}

		//set Interactable
		public void SetInteractable(Selectable comp, bool interactable)
		{
			comp.interactable = interactable;
		}

		//get string
		protected string GetString(InputField comp)
		{
			return comp?.text;
		}

		protected string GetString(TMPro.TMP_InputField comp)
		{
			return comp?.text;
		}

		//get float
		protected float GetFloat(Slider comp)
		{
			return comp.value;
		}

		//get int
		protected int GetInt(Dropdown comp)
		{
			return comp.value;
		}

		//get bool
		protected bool GetBool(Toggle comp)
		{
			return comp.isOn;
		}

		/// <summary>Get component of type T (used cache)</summary>
		protected T Get<T>(Component component, bool onlyChildren = false) where T : Component
		{
			if (componentCache == null)
				componentCache = new Dictionary<(Component, Type), Component>();

			var key = (component, typeof(T));

			if (!componentCache.TryGetValue(key, out var comp))
			{
				if (onlyChildren)
					comp = componentCache[key] = component.GetComponentsInChildren<T>(true).FirstOrDefault(c => c.gameObject != component.gameObject);
				else
					comp = componentCache[key] = component.GetComponentInChildren<T>(true);
			}

			return (T)comp;
		}

		#endregion

		#region Instantiate prefabs

		protected new T Instantiate<T>(T prefab) where T : UnityEngine.Object
		{
			if (prefab is BaseView bv)
			{
				//spawn BaseView in same parent
				var res = GameObject.Instantiate(prefab, bv.transform.parent);
				return res;
			}

			//default spawn for other types
			return GameObject.Instantiate(prefab);
		}

		[VisibleInGraph(false)]
		public virtual BaseView Clone()
		{
			var clone = Instantiate(this);
			return clone;
		}

		#endregion

		#region Gestures

		public event Action<GestureInfo> Gestured;

		public virtual void OnGesture(GestureInfo info)
		{
			Gestured?.Invoke(info);
		}

		#endregion

		#region Drag&Drop

		public event Action<BaseView, BaseView> Dropped;
		public event Action<BaseView> StartDrag;

		/// <summary>This method is calling when other view is dragged over the view</summary>
		public virtual bool CanDropIn(BaseView draggedView)
		{
			//override this method and return True if you want to allow drag&drop other view into this view
			return false;
		}

		/// <summary>This method is calling when other view try drop into the view</summary>
		public virtual void DropIn(BaseView draggedView)
		{
			//override this method and return True if you want accept dragged view into this view
		}

		/// <summary>This method is calling when my children is moved to other view</summary>
		public virtual void DropOut(BaseView draggedView, BaseView acceptor)
		{
			//override this method and return True if you want accept dragged view into this view
		}

		/// <summary>This method is calling when the view is successfully dropped into other view</summary>
		public virtual void OnDropped(BaseView acceptor)
		{
			Dropped?.Invoke(this, acceptor);
		}

		/// <summary>This method is calling when the view is not accepted and must be destroyed or returned back to starting spot</summary>
		public virtual void OnDropCancelled()
		{

		}

		/// <summary>This method is calling when the view start dragging</summary>
		public virtual void OnStartDrag()
		{
			StartDrag?.Invoke(this);
		}

		#endregion

		#region Events

		/// <summary>VisibleState of the view was changed</summary>
		public event Action<VisibleState> VisibleStateChanged;
		/// <summary>View became shown and visible</summary>
		public event Action Shown;
		/// <summary>View became closed</summary>
		public event Action Closed;
		/// <summary>View became hidden</summary>
		public event Action Hidden;
		/// <summary>View became closed and disabled</summary>
		public event Action ClosedAndDisabled;
		/// <summary>View became hidden and disabled</summary>
		public event Action HiddenAndDisabled;
		/// <summary>Fired when any button of the View is pressed</summary>
		public event Action<Button> AnyButtonPressed;

		protected virtual void OnVisibleStateChanged(VisibleState newState)
		{
			switch (newState)
			{
				case VisibleState.Visible:
					OnShown();
					Shown?.Invoke();
					break;
				case VisibleState.Closed:
					OnClosed();
					Closed?.Invoke();
					break;
				case VisibleState.Hidden:
					OnHidden();
					Hidden?.Invoke();
					break;
			}

			VisibleStateChanged?.Invoke(newState);
		}

		protected virtual void OnShown() { }
		protected virtual void OnClosed() { }
		protected virtual void OnHidden() { }

		protected virtual void OnDisable()
		{
			switch (VisibleState)
			{
				case VisibleState.Closed: ClosedAndDisabled?.Invoke(); break;
				case VisibleState.Hidden: HiddenAndDisabled?.Invoke(); break;
			}
		}

		protected virtual void OnAnyButtonPressed(Button bt)
		{
			if (Sounds.PlayButtonClickSound)
				UIManager.PlayButtonSound(this);

			AnyButtonPressed?.Invoke(bt);
		}

		protected virtual void OnAnyButtonOverlayed(Button bt)
		{
			if (Sounds.PlayButtonHoverSound)
				UIManager.PlayOverlaySound(this);
		}

		#endregion

		#region IBaseViewInternal

		public void SetVisibleState(VisibleState state)
		{
			if (visibleState != state)
			{
				visibleState = state;
				OnVisibleStateChanged(state);
			}
		}

		public void SetDynamicallyCreated(bool val)
		{
			IsDynamicallyCreated = val;
		}

		#endregion
	}

	[Serializable]
	public class ViewAnimations
	{
		public AnimationLink ShowAnimation;
		public AnimationLink CloseAnimation;
		public AnimationLink HideAnimation;
	}

	/// <summary>Internal interface of BaseView</summary>
	interface IBaseViewInternal
	{
		void SetVisibleState(VisibleState state);
		void SetDynamicallyCreated(bool val);
	}

	[Serializable]
	public enum BackPrority
	{
		IgnoreBack = 0,
		Lowest = 1,
		Low = 2,
		Normal = 3,
		High = 4,
		Highest = 5
	}

	[Serializable]
	public enum DragMode
	{
		None, Move, Copy
	}

	[Serializable]
	public enum VisibleState
	{
		Closed, Visible, Hidden
	}

	[AttributeUsage(AttributeTargets.Field)]
	public class AutoGeneratedAttribute : Attribute
	{
	}

	[AttributeUsage(AttributeTargets.Method)]
	public class VisibleInGraphAttribute : Attribute
	{
		public bool Visible { get; set; } = true;

		public VisibleInGraphAttribute(bool visible = true)
		{
			Visible = visible;
		}
	}

	[Serializable]
	public class ViewSounds
	{
		public AudioClip BackgroundSound;
		public OwnerSoundMode OwnerSoundMode = OwnerSoundMode.Normal;
		public AudioClip ShowSound;
		public AudioClip CloseSound;
		[Tooltip("Play default sound on button click")]
		public bool PlayButtonClickSound = true;
		public bool PlayButtonHoverSound = false;
	}

	[Serializable]
	public enum OwnerSoundMode
	{
		Normal, Mute, Fade
	}
}