/////////////////////////////////////////
// === THIS IS AUTOGENERATED CODE ===  //
//       do not change directly        //
/////////////////////////////////////////
using System;
using UnityEngine;
using System.Collections.Generic;
using UnityEngine.UI;
using RR.UI;
using RR.UI.FrameSystem;

namespace RR.Game.TutorialSystem.Presentation.UI
{
    public partial class TutorHintView : RR.UI.FrameSystem.BaseView //Autogenerated
    {
        public static TutorHintView Instance { get; private set; }
        // Controls
        #pragma warning disable 0414
        [Header("Controls (auto capture)")]
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image Unmask = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Button TutorHider = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform TutorHintBG = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image Arrow = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image Frame = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI TutorHintTitle = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Image HintTitleDecor = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI TutorHintText = default;
        [AutoGenerated, SerializeField] protected UnityEngine.RectTransform ButtonsBar = default;
        [AutoGenerated, SerializeField] protected UnityEngine.UI.Button AcceptButton = default;
        [AutoGenerated, SerializeField] protected TMPro.TextMeshProUGUI AcceptText = default;
        #pragma warning restore 0414
        
        protected override void AutoInit()
        {
            Instance = this;
        }
        
        protected override void AutoSubscribe()
        {
            SubscribeOnChanged(Unmask);
            SubscribeOnChanged(TutorHider);
            SubscribeOnChanged(TutorHintBG);
            SubscribeOnChanged(Arrow);
            SubscribeOnChanged(Frame);
            SubscribeOnChanged(TutorHintTitle);
            SubscribeOnChanged(HintTitleDecor);
            SubscribeOnChanged(TutorHintText);
            SubscribeOnChanged(ButtonsBar);
            SubscribeOnChanged(AcceptButton);
            SubscribeOnChanged(AcceptText);
        }
        
        [VisibleInGraph(false)]
        public TutorHintView Build()
        {
            OnBuildSafe(true);
            return this;
        }
        #region Static Methods
        public static void ShowInstance() => Instance.Show();
        public static void HideInstance() => Instance.Hide();
        public static void CloseInstance() => Instance.Close();
        #endregion
    }
}